<?php

include_once('vsite_cc.features.inc');

function vsite_cc_vsite_widgets() {

  return array(
    'vsite_cc_widget' => array (
      'module' => 'creativecommons',
      'delta' => 'node_license',
      'weight' => 0,
      'region' => false,
      'status' => 0,
      'label' => t('Creative Commons License'),
      'type' => 'context_ui',
    )
  );
}

function vsite_cc_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, '_node_form') !== FALSE) {
    if (!vsite_cc_block_enabled('vsite_cc_widget')) {
      unset($form['creativecommons']);
    }
  }
}

function vsite_cc_block_enabled($name) {
  $vsite = vsite_get_vsite();
  if(!$vsite)  return false;
  
  $contexts = $vsite->controllers->context->get();

  foreach ($contexts as $cont_name => $data) {
    if (strpos($cont_name, 'block') !== FALSE && strpos($cont_name, $vsite->group->og_theme) !== FALSE) {
      if ($data['blocks'][$name]['region'] != FALSE) {
        return true;
      }
    }
  }

  return false;
}