<?php

function vsite_menus_init(){
   drupal_add_css(drupal_get_path('module', 'vsite_menus') .'/theme/vsite_menus.css');
}

/**
 * Implementation of hook_spaces_settings().
 */
function vsite_menus_spaces_settings(){
  return array(
    'menus' => array(
      'class' => 'vsite_menus_menus', 
      'file' => drupal_get_path('module', 'vsite_menus') . '/includes/vsite_menus.menus.inc' 
    ) 
  );
}

/**
 * Implements hook_menu_node_insert().
 */
function vsite_menus_menu_node_insert($item, $node) {
  require_once(drupal_get_path('module', 'vsite_menus') .'/vsite_menus.menus.inc');
  vsite_include('vsiteapi');
  $site = vsite_get_vsite();
  $a_scholar_types = vsite_content_types();
  
  if($site && array_key_exists($node->type,$a_scholar_types) && ($item->menu_name == variable_get('scholar_primary_menu',false) || $item->menu_name == variable_get('scholar_secondary_menu',false))){
    
    $s_menu_key = $item->menu_name == variable_get('scholar_primary_menu',false)?'primary':'secondary';
    
    $site->settings['menus']['menu_items'][$item->mlid] = array('menu' => $s_menu_key, 'weight' => $item->weight);
    
    $site->settings['menus'] = vsite_menus_menus::create_menus($site->settings['menus']); 
    
    spaces_save($site);
  }elseif ($site && array_key_exists($item->mlid,$site->settings['menus']['menu_items'])){
    unset($site->settings['menus']['menu_items'][$item->mlid]);
    $site->settings['menus'] = vsite_menus_menus::create_menus($site->settings['menus']); 
    spaces_save($site);
  }
}

/**
 * Implements hook_menu_node_update().
 */
function vsite_menus_menu_node_update($item, $node) {
  vsite_menus_menu_node_insert($item,$node);
}

/**
 * Implements hook_menu_node_delete().
 */
function vsite_menus_menu_node_delete($item, $node) {
  require_once(drupal_get_path('module', 'vsite_menus') .'/vsite_menus.menus.inc');
  vsite_include('vsiteapi');
  $site = vsite_get_vsite();
  $a_scholar_types = vsite_content_types();
  
  if ($site && array_key_exists($node->type,$a_scholar_types) && array_key_exists($item->mlid,$site->settings['menus']['menu_items'])){
    unset($site->settings['menus']['menu_items'][$item->mlid]);
    $site->settings['menus'] = vsite_menus_menus::create_menus($site->settings['menus']); 
    spaces_save($site);
  }
}

/**
 * Return the menu tree object for a scholar site, adapted for the current page
 *
 * @param string $s_menu  (primary / secondary)
 * @param boolean $b_html (return formated html?)
 * @param boolean $b_check_expanded (allow expanded menus? slightly slower)
 */
function vsite_menus_get_menu_tree($s_menu = 'primary', $b_html = true, $b_check_expanded = false){
  $space = vsite_get_vsite();
  
  if(!$space) return ($b_html)?"":false;
  
  switch ($s_menu){
    case 'secondary':
      $a_settings_menu = array_key_exists('menus',$space->settings)?$space->settings['menus']['secondary']:false;
      $s_def_menu = 'scholar_secondary_menu';
    break;
    case 'primary':
    default:
      $a_settings_menu = array_key_exists('menus',$space->settings)?$space->settings['menus']['primary']:false;
      $s_def_menu = 'scholar_primary_menu';
  }
  
  if(!$a_settings_menu){
    $a_tree = menu_tree_page_data(variable_get($s_def_menu,false));
    foreach ($a_tree as $k => $tree) {
      if($tree['below']) $a_tree[$k]['below'] = false;
    }
    
    return menu_tree_output($a_tree);
  }//send default
  
  $n_found = 0;   
  if($b_check_expanded){
    $a_full_page_expanded = array_merge( menu_tree_page_data(variable_get('scholar_primary_menu',false)), 
                                         menu_tree_page_data(variable_get('scholar_secondary_menu',false)));
                                        
    //We must unfortunatly loop through the page data once to get the
    //correct expanded trees, the menu module does not provide an easy
    //way of retrieving a individual menu_node's tree (expanded)
    foreach ($a_full_page_expanded as $a_tree) {
      if(!in_array($a_tree['link']['mlid'],$a_settings_menu)) continue;
      $n_found++;
      $a_settings_menu[array_search($a_tree['link']['mlid'],$a_settings_menu)] = $a_tree;
      if($n_found >= count($a_settings_menu)) break;
      break;
    }
  }
  
  if($n_found < count($a_settings_menu)){
    foreach ($a_settings_menu as $n_key => $n_mlid) {
      if(!is_int($n_mlid)) continue;
      $a_settings_menu[$n_key] = array('link' => menu_link_load($n_mlid), 'below' => false);
    }
  }
  
  
  if(!$b_html) return $a_settings_menu;
  
  return menu_tree_output($a_settings_menu);
}

/**
 * Implementation of hook_theme().
 */
function vsite_menus_theme($cache, $type, $theme, $path) {
  $path = drupal_get_path('module', 'vsite_menus') ;
  
  $items['vsite_menus_radios'] = array(
    'arguments' => array('element' => NULL,'disabled' => array()),
    'path' => $path,
    'file' => 'menu_theme.inc',
  );
  
  return $items;
}

function vsite_menus_form_alter(&$form, $form_state, $form_id){
  vsite_include('vsiteapi');
  $a_scholar_types = vsite_content_types();
  $o_scholar = vsite_get_vsite();
  
  if($o_scholar && array_key_exists($form['type']['#value'],$a_scholar_types)){
    $a_primary = menu_load(variable_get('scholar_primary_menu',false));
    $a_secondary = menu_load(variable_get('scholar_secondary_menu',false));
      
    $form['menu']['parent']['#options'] = array(
      variable_get('scholar_primary_menu',false).":0" => t($a_primary['title']),
      variable_get('scholar_secondary_menu',false).":0" => t($a_secondary['title']),
    );
    unset($form['menu']['hidden']);
  }
}

/**
 * Iplementation of hook block
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 */
function vsite_menus_block($op = 'list', $delta = 0, $edit = array()) {
  if(!user_access('access content')) return;
  
  $blocks = array();
  if ($op == 'list') {
    $blocks[] = array('info' => t('Scholar primary menu'),
                      'cache' => BLOCK_CACHE_PER_PAGE); 
    $blocks[] = array('info' => t('Scholar secondary menu'),
                      'cache' => BLOCK_CACHE_PER_PAGE);  
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        $block['subject'] = t(''); // intentionally left empty for now.
        $block['content'] =vsite_menus_get_menu_tree('primary');
        return $block ;
      case 1:
        $block['subject'] = t(''); // intentionally left empty for now.
        $block['content'] = vsite_menus_get_menu_tree('secondary');
        return $block;
    }
  }
}

/**
 * Implementation of hook_vsite_widgets
 * @return array
 */
function vsite_menus_vsite_widgets(){
  
  return array(
    'vsite_menus_0' => array(
      'module' => 'vsite_menus',
      'delta' => '0',
      'weight' => 20,
      'region' => 'navbar',
      'status' => '0',
      'label' => 'Scholar primary menu',
      'type' => 'context_ui',
    ),
    'vsite_menus_1' => array(
      'module' => 'vsite_menus',
      'delta' => '1',
      'weight' => 20,
      'region' => 'left',
      'status' => '0',
      'label' => 'Scholar secondary menu',
      'type' => 'context_ui',
    ),
  );
}

