<?php

// $Id$

/**
  * Implementation of hook_help().
  */
function vsite_help_help($path) {
  switch ($path) {
    case 'cp/features':
      return theme('advanced_help_topic', 'vsite_help', 'Features');
    case 'cp/news':
      return theme('advanced_help_topic', 'vsite_help', 'Getting-news');
    case 'cp/settings/bio':
      return theme('advanced_help_topic', 'vsite_help', 'Bio-settings');
    case 'cp/settings/front':
      return theme('advanced_help_topic', 'vsite_help', 'Front-page-settings');
    case 'cp/support':
      return theme('advanced_help_topic', 'vsite_help', 'Get-support');
  }
}

