<?php
function vsite_help_help($path) {
  switch ($path) {
    case 'cp/content':
      return theme('advanced_help_topic', 'vsite_help', 'Managing-Your-Content');
    case 'cp/content/files':
      return theme('advanced_help_topic', 'vsite_help', 'Managing-Files-and-Images');
    case 'cp/content/taxonomy':
      return theme('advanced_help_topic', 'vsite_help', 'Categorizing-Your-Content');
    case 'cp/features':
      return theme('advanced_help_topic', 'vsite_help', 'Features');
    case 'cp/news':
      return theme('advanced_help_topic', 'vsite_help', 'Getting-Project-News');
    case 'cp/settings':
      return theme('advanced_help_topic', 'vsite_help', 'Manage-Basic-Site-Information');
    case 'cp/settings/front':
      return theme('advanced_help_topic', 'vsite_help', 'Setting-up-your-web-sites-front-page');
    case 'cp/settings/generic':
      return theme('advanced_help_topic', 'vsite_help', 'Other-settings');
    case 'cp/settings/layout':
      return theme('advanced_help_topic', 'vsite_help', 'Site-layout');
    case 'cp/settings/menus':
      return theme('advanced_help_topic', 'vsite_help', 'Manage-Menus');
    case 'cp/settings/theme':
      return theme('advanced_help_topic', 'vsite_help', 'Change-the-look-of-your-site');
    case 'cp/support':
      return theme('advanced_help_topic', 'vsite_help', 'Getting-Support');
    case 'cp/users':
      return theme('advanced_help_topic', 'vsite_help', 'Managing-Your-Users');
  }
}

function vsite_help_step_form(&$element, $form_id, $callback) {
    foreach (element_children($element) as $child) {
      vsite_help_step_form($element[$child], $form_id . ':' . $child, $callback);
    }
    $callback($element, $form_id);
}

function vsite_help_form_alter(&$form, $form_state, $form_id) {
  vsite_help_step_form($form, $form_id, 'vsite_help_help_link');
  $form['#description'] = isset($form['#description']) ? vsite_help_get_from_key('form', $form_id) . ' ' . $form['#description'] : vsite_help_get_from_key('form', $form_id);
}

function vsite_help_get_from_key($key) {
  static $helpkeys = array(
    'spaces_features_form:features:scholar_announcements' => array('module' => 'vsite_help', 'file' => 'Announcement-feature'),
    'spaces_features_form:features:scholar_biocv' => array('module' => 'vsite_help', 'file' => 'CV---Bio-feature'),
    'spaces_features_form:features:scholar_blog' => array('module' => 'vsite_help', 'file' => 'Blog-feature'),
    'spaces_features_form:features:scholar_dvn' => array('module' => 'vsite_help', 'file' => 'Dataverse-feature'),
    'spaces_features_form:features:scholar_feeds' => array('module' => 'vsite_help', 'file' => 'Feed-feature'),
    'spaces_features_form:features:scholar_image_gallery' => array('module' => 'vsite_help', 'file' => 'Photo-Gallery-feature'),
    'spaces_features_form:features:scholar_links' => array('module' => 'vsite_help', 'file' => 'Links-feature'),
    'spaces_features_form:features:scholar_publications' => array('module' => 'vsite_help', 'file' => 'Publications-feature'),
    'spaces_features_form:features:scholar_software' => array('module' => 'vsite_help', 'file' => 'Software-feature'),
  );
  return isset($helpkeys[$key]) ? $helpkeys[$key] : FALSE;
}

function vsite_help_help_link(&$element, $form_id) {
  if (isset($element['#type']) && !in_array($element['#type'], array('button', 'image_button', 'submit', 'markup', 'token', 'hidden', 'form', 'value', 'weight'))) {
    if ($result = vsite_help_get_from_key($form_id)) {
      $link = theme('advanced_help_topic', $result['module'], $result['file']);
      if ($element['#type'] == 'fieldset') {
        drupal_add_css(drupal_get_path('module', 'vsite_help') . '/vsite_help.css');
        $link = preg_replace('/class="(.+?)"/', 'class="\1 vsite_help-nofloat"', $link);
      }
      $element['#description'] = isset($element['#description']) ? $link . ' ' . $element['#description'] : $link;
    }
  }
}

