<?php

include_once('iqss_project.features.inc');

function iqss_project_theme(){
  
  $path = drupal_get_path('module', 'iqss_project') . '/theme';
  
  //top bocks
  $items['project_slideshow'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-slideshow',
    'path' => $path,
  );
  
    $items['project_big_text'] = array(
    'arguments' => array(),
    'template' => 'project-big-text',
    'path' => $path,
  );
  
  //middle blocks
  $items['project_create'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-create',
  'path' => $path,
  );
  
  $items['project_maintain'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-maintain',
  'path' => $path,
  );

  $items['project_control'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-control',
    'path' => $path,
  );
  
  $items['project_collaborate'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-collaborate',
    'path' => $path,
  );
  
  //bottom block
    $items['project_site_examples'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-site-examples',
    'path' => $path,
  );
  
  return $items;
 }

 function iqss_project_preprocess_project_site_examples(&$vars){
  $vars['sites'] = array();
  $view = views_get_view('iqss_project_sites');
  $view->init();
  $view->set_display('block_1');

  $view->display['block_1']->handler->options['items_per_page'] = 6;  // not working

  $view->execute();

  $results = array_slice($view -> result, 0, 6);
  foreach ( $results as $result ) {
    $sid = $result -> nid;
    $vsite = spaces_load('og', $sid, FALSE);
    $og_node = $vsite -> group;

    $vars['sites'][]= array(
      'headline' => $og_node -> title,
      'sub_headline' => $og_node -> og_description,
      'photo' =>  theme_vsite_logo($vsite, $s_logo_field = "field_vsite_logo", $preset = 'iqss_project_front_logo', $alt = '' , $title = '', $attributes = array(), $bypass_browser_cache =false, $b_as_link = TRUE),
    );
  }
}
 
function iqss_project_menu(){
  $items = array();
 
  // nodeautocomplete callback for scholar 
  $items['iqss_scholar_home'] = array(
    'type' => MENU_CALLBACK, 
    'title' => 'Scholars\'s Web Sites Project', 
    'page callback' => 'iqss_project_homepage', 
    'access arguments' => array(
      'access content' 
    ), 
  );
  
  return $items;
}


function iqss_project_homepage(){
	
  $s_content = '<div id="content-row-1">'.theme('project_big_text').'</div>';
  $s_content .= '<div id="content-row-2">'.theme('project_create') . theme('project_maintain') . theme('project_control') . theme('project_collaborate'). '</div>' ;

  return $s_content;
  
}