<?php

include_once('scholar_announcements.features.inc');

/**
 * Implementation of hook_strongarm()
 */
function scholar_announcements_strongarm(){
  $conf = array();

  // Disable preview button
  $conf["show_preview_changes_announcement"] = FALSE;
  $conf["show_diff_inline_announcement"] = FALSE;  
 
  $conf['node_options_announcement'] = array('status', 'revision');
  $conf['upload_announcement'] = TRUE;
 
  // Comments
  $conf['comment_announcement'] = COMMENT_NODE_DISABLED;
 
  // Pathauto (optional) settings
  $conf["pathauto_node_announcement_pattern"] = "[space-og-path]/announcements/[title-raw]";
  
  // submitted info
  $conf['node_submitted_info_announcement'] = TRUE;
 
  return $conf;
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_announcements_context_links_alter(&$links) {
  if (!empty($links['announcement'])) {
    $links['announcement']['query'] = drupal_get_destination();
  }
}

/**
 * hook vsite_widgets
 */
function scholar_announcements_vsite_widgets(){
  $items = array();
  $items['views_scholar_announcements-block_1'] = array(
        'module' => 'views',
        'delta' => 'scholar_announcements-block_1',
        'weight' => -21,
        'region' => false,
        'status' => '0',
        'label' => 'Latest Announcements',
        'type' => 'context_ui',
      );
  return $items;
}