<?php

include_once('scholar_software.features.inc');

/**
 * Implementation of hook_strongarm().
 */
function scholar_software_strongarm() {
  return array(
    'content_extra_weights_scholar_software_project' => array (
      'title' => '-5',
      'body_field' => '5',
      'revision_information' => '6',
      'comment_settings' => '7',
      'menu' => '8',
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function scholar_software_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'scholar_software') .'/views',
  );
}

/**
 * Implementation of hook_link().
 */
function scholar_software_link($type, $object, $teaser = FALSE) {
  // Only allow releases to be added if packaging method is 0 => 'Manual'.
  $links = array();
  if ($type == 'node' && $object->type == 'scholar_software_project' && empty($object->field_scholar_software_method[0]['value'])) {
    $item = menu_get_item('node/add/scholar_software-release');
    if ($item && $item['access']) {
      $links['scholar_software-add-release'] = array(
        'title' => t('Add new @release', array('@release' => strtolower($item['title']))),
        'href' => 'node/add/scholar_software-release',
      );
    }
  }
  return $links;
}

/**
 * Implementation of hook_nodeapi().
 */
function scholar_software_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'view' && $node->type == 'scholar_software_project' && menu_get_object()->nid === $node->nid) {
    $url = url("scholar_software", array('purl' => array('disabled' => TRUE), 'absolute' => TRUE));
    $project = check_plain($node->field_scholar_software_name[0]['value']);
    $node->content['project_info'] = array(
      '#type' => 'fieldset',
      'info' => array(
        '#access' => node_access('update', $node),
        '#title' => t("For <code>@project.info</code>", array('@project' => $project)),
        '#type' => 'item',
        '#value' => "<code>project status url = {$url}</code>",
      ),
      '#weight' => -10,
    );
  }
  else if ($op == 'presave' && $node->type == 'scholar_software_project') {
    if (empty($node->field_scholar_software_method[0]['value'])) {
      $node->field_scholar_software_repository[0]['value'] = '';
    }
  }
  else if ($op == 'presave' && $node->type == 'scholar_software_release') {
    $node->title = scholar_software_generate_version($node);

    // If this release is recommended, set all other ones to not recommended.
    if ($node->field_scholar_software_recommend[0]['value'] == 1) {
      $view = views_get_view('scholar_software_releases');
      $view->set_arguments(array($node->field_scholar_software_project[0]['nid']));
      $view->execute('block_1');
      foreach ($view->result as $data) {
        if (!isset($node->nid) || $data->nid != $node->nid) {
          $release = node_load($data->nid);
          $release->field_scholar_software_recommend[0]['value'] = 0;
          node_save($release);
        }
      }
    }
  }
  else if ($op == 'view' && $node->type == 'scholar_software_release') {
    drupal_add_css(drupal_get_path('module', 'scholar_software') . '/scholar_software.css');
    $download_url = url($node->field_scholar_software_file[0]['filepath'], array('purl' => array('disabled' => TRUE), 'absolute' => TRUE));
    $contents = file_exists($node->field_scholar_software_file[0]['filepath']) ? file_get_contents($node->field_scholar_software_file[0]['filepath']) : '';
    $info = array();
    $info[] = t('Download: !url', array('!url' => l($download_url, $download_url, array('absolute' => TRUE))));
    $info[] = t('md5 hash: !md5', array('!md5' => md5($contents)));
    $info[] = t('Size: !size', array('!size' => format_size($node->field_scholar_software_file[0]['filesize'])));
    $node->content['scholar_software_info'] = array(
      '#type' => 'fieldset',
      'content' => array(
        '#type' => 'markup',
        '#value' => theme('item_list', $info, NULL, 'ul', array('id' => 'scholar_software-release-info')),
      ),
      '#weight' => -10,
    );
    $project = node_load($node->field_scholar_software_project[0]['nid']);
    drupal_set_breadcrumb(array(l(t('Home'), NULL), l($project->title, 'node/' . $project->nid)));
  }
}

/**
 * Option field callback for version options.
 */
function scholar_software_cck_options($type = 'major') {
  switch ($type) {
    case 'major':
      $major = range(0, 50);
      unset($major[0]);
      return $major;

    case 'method':
      return array(
        0 => t('Manual upload'),
        'rbuild' => t('rbuild repository'),
      );

    case 'patch':
      return range(0, 50);

    case 'recommended':
      return array(t('Not recommended'), t('Recommended'));

    case 'security':
      return array(t('Not a security release'), t('Security release'));

  }
}

/**
 * Parse a package name into values: core, major, patch and extra.
 */
function scholar_software_parse_package_name($package_filename) {
  // example: scholar_software-6.x-2.0-rc3.tar.gz
  if (preg_match('/^(?<project>\w+)-(?<core>\d+\.x)-(?<major>\d+)\.(?<patch>\d+)-?(?<extra>\w+)?\.(tar\.gz|tgz)$/', $package_filename, $matches)) {
    return $matches;
  };
  return array();
}

/**
 * Parse a package name into values: core, major, patch and extra.
 */
function scholar_software_parse_tag_name($tag) {
  // example: drupal-6--1-0-alpha1
  if (preg_match('/^(?P<project>\w+)-(?P<core>\d+)--(?P<major>\d+)-(?P<patch>\d+)-?(?P<extra>\w+)?$/', $tag, $matches)) {
    $parsed = array_intersect_key($matches, array('core' => '', 'major' => '', 'patch' => '', 'extra' => ''));
    if (!empty($parsed)) {
      $parsed['core'] = "{$parsed['core']}.x";
      $parsed['original'] = $tag;
      $parsed['version'] = "{$parsed['core']}-{$parsed['major']}.{$parsed['patch']}" . (!empty($parsed['extra']) ? "-{$parsed['extra']}" : '');
      return $parsed;
    }
  }
  return array();
}

/**
 * Implementation of hook_form_alter() for scholar_software_project_node_form.
 */
function scholar_software_form_scholar_software_project_node_form_alter(&$form, $form_state) {
  drupal_add_js(drupal_get_path('module', 'scholar_software') . '/scholar_software.js');
  $form['#validate'][] = 'scholar_software_project_node_form_validate';
}

/**
 * Validate handler for scholar_software_project_node_form.
 */
function scholar_software_project_node_form_validate($form, &$form_state) {
  // Ensure repository URL is set if using a non-manual method.
  if (!empty($form_state['values']['field_scholar_software_method'][0]['value']) && empty($form_state['values']['field_scholar_software_repository'][0]['value'])) {
    form_set_error($form_state['values']['field_scholar_software_repository'][0]['_error_element'], t('Please provide a valid repository URL for this project.'));
  }
}

/**
 * Implementation of hook_form_alter() for scholar_software_release_node_form.
 */
function scholar_software_form_scholar_software_release_node_form_alter(&$form, $form_state) {
  drupal_add_css(drupal_get_path('module', 'scholar_software') . '/scholar_software.css');
  $form['title'] = array(
    '#type' => 'value',
    '#value' => 'VOID',
  );
  $form['#submit'][] = 'scholar_software_release_node_form_submit';
}

/**
 * Submit handler for scholar_software_release_node_form.
 */
function scholar_software_release_node_form_submit($form, &$form_state) {
  // Only do something, if the user clicked the preview button.
  if (isset($form_state['clicked_button']['#submit']) && in_array('node_form_build_preview', $form_state['clicked_button']['#submit'])) {
    $node = node_submit($form_state['values']);
    $node->title = scholar_software_generate_version($node);
    $form_state['values'] = (array) $node;
  }
}

/**
 * Generate a standard version string from a node object.
 * @TODO: Merge this or make use of it in scholar_software_handler_field_release_tag::render().
 */
function scholar_software_generate_version($node, $raw = FALSE) {
  $project = node_load($node->field_scholar_software_project[0]['nid']);
  $major = $node->field_versionmajor[0]['value'];
  $patch = $node->field_versionpatch[0]['value'];
  $extra = $node->field_versionextra[0]['value'];
  $version = "{$major}.{$patch}" . (!empty($extra) ? "-{$extra}" : '');
  return $raw ? $version : "{$project->title} $version";
}
