<?php

include_once('scholar.features.inc');
/**
 * hook strongarm
 */
function scholar_strongarm(){
  $conf = array();

  // User settings
  $conf['user_register'] = 0; // No registration is allowed; this is a closed group

  $conf['spaces_default_presets'] = array(
    'og' => 'scholar',
    //'user' => '',
    //'site' => ''
  );

  $conf['spaces_disabled_presets'] = array(
    'og' => array (
            'private' => 1,
            'controlled' => 1,
            'public' => 1,
        )
  );
  
 $conf['vsite_installation_name'] = 'scholar';
  
  return $conf;
}

function scholar_spaces_presets(){
  $items = array();
  vsite_include('vsiteapi');
  $options = vsite_content_types();

  $items['scholar'] = array(
    'name' => 'Scholar site preset', 
    'description' => 'Scholar site preset', 
    'type' => 'og', 
    'preset' => array(
      'features' => array(
        'scholar_publications' => '2',
        'scholar_front' => '2', 
        'scholar_biocv' => '2', 
        'scholar_classes' => '2', 
        'scholar_pages' => '2', 
        'scholar_image_gallery' => '0', 
        'scholar_reader' => '0', 
        'scholar_announcements' => '0', 
        'scholar_blog' => '0', 
        'scholar_dvn' => '0', 
        'scholar_links' => '0', 
        'scholar_software' => '0' 
      ), 
      'settings' => array(
        'theme' => array(
          'maintheme' => 'scholar_theme_01', 
          'flavor' => '0' 
        ), 

        'front' => array(
          'frontpage' => 'feature', 
          'node_options' => $options 
        ), 
        
        'activity' => array(
          'ignore_insert' => '1', 
          'ignore_update' => '1' 
        ), 
        
        'generic' => array(
          'admin_menu' => 0, 
          'contact_form' => 1, 
          'contact_form_anonymous' => 1, 
          'shield' => drupal_get_path('module', 'vsite_generic_settings') . "/theme/shields/harvard_shield.png" 
        ), 
        
        'site' => array(
          'headline' => "", 
          'sub_heading' => "" 
        ),
        
      ), 
      
      'locked' => array(
        'features' => array(
          'scholar_front' => 1,
        ) 
      ), 
      'weights' => array(
        'scholar_publications' => '-10', 
        'scholar_biocv' => '-9', 
        'scholar_classes' => '-8', 
        'scholar_pages' => '-7', 
        'scholar_image_gallery' => '-6', 
        'scholar_reader' => '-5', 
        'scholar_announcements' => '-4', 
        'scholar_blog' => '-3', 
        'scholar_dvn' => '-2', 
        'scholar_links' => '-1', 
        'scholar_software' => '0' 
      ), 
      'og' => array(
        'og_selective' => '3', 
        'og_register' => 0, 
        'og_directory' => 1, 
        'og_private' => 0 
      ) 
    ) 
  );
  
  return $items;
}

/**
 * Implementation of hook_form_alter()
 **/
function scholar_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'vsite_node_form':
      //Customize the "Site Information" form
      if(arg(0) != 'cp') break;

      $form['title']['#title'] = "Main Headline:";
      $form['title']['#description'] = "Usually: First and Last name ex.(John Q. Smith)";
      $form['og_description']['#title'] = "Sub Headline:";
      $form['og_description']['#description'] = "Usually: Title ex.(Director of Mathematics)";
      $form['field_vsite_address'][0]['#title'] = "Address Line";
      $form['field_vsite_address'][0]['#description'] = "Usually: Your Address ex.(Cambridge, MA 02118)";
      
    break;
    default:
    	
  }
}
