<?php

/**
 * hook strongarm
 */
function scholar_strongarm(){
  $conf = array();

  // User settings
  $conf['user_register'] = 0; // No registration is allowed; this is a closed group

  $conf['spaces_default_presets'] = array(
    'og' => 'scholar',
    //'user' => '',
    //'site' => ''
  );

  $conf['spaces_disabled_presets'] = array(
    'og' => array (
            'private' => 1,
            'controlled' => 1,
            'public' => 1,
        )
  );
  
  return $conf;
}

/**
 * hook spaces_presets
 */
function vsite_spaces_presets(){
  $items = array();
  vsite_include('vsiteapi');
  $options = vsite_content_types();
  $items['scholar'] = array(
    'name' => 'Scholar site preset', 
    'description' => 'Scholar site preset', 
    'preset' => array(
      'features' => array(
        'scholar_publications' => '2', 
        'scholar_biocv' => '2', 
        'scholar_classes' => '2', 
        'scholar_pages' => '2' 
      ), 
      'locked' => array(
        'features' => array(
          'scholar_links' => 0, 
          'scholar_announcements' => 0, 
          'scholar_blog' => 0 
        ), 
        'settings' => array(
          'home' => 0 
        ) 
      ), 
      'og' => array(
        'og_selective' => '3', 
        'og_register' => 0, 
        'og_directory' => 1, 
        'og_private' => 0 
      ) 
    ), 
    'type' => 'og' 
  );
  
  //Put default settings here
  $items['scholar']['preset']['settings'] = array(
    'home' => 'blog', 
    'front' => array(
      'frontpage' => 'feature', 
      'node_options' => $options 
    ), 
    'theme' => 'scholar_theme_01',  // TODO make this settings for the site-wide admin to chose
    'generic' => array(
      'admin_menu' => 0, 
      'contact_form' => 1, 
      'contact_form_anonymous' => 1, 
      'shield' => drupal_get_path('module', 'vsite_generic_settings') . "/theme/shields/harvard_shield.png" 
    ) 
  );
  
  $items['scholar']['preset']['settings']['site'] = array(
    'headline' => "", 
    'sub_heading' => "" 
  );
  
  return $items;
}




function scholar_menu(){
  $items = array();
  $items['admin/settings/scholar'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Scholar settings',
    'description' => 'Setting for scholars.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scholar_settings_form'),
    'file' => 'scholar.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'weight' => 10,
  );

  $items['admin/settings/scholar/settings'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scholar_settings_form'),
    'file' => 'scholar.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'weight' => 0,
  );
  return $items;
}



/**
* Implementation of hook_mail_alter().
*/
function scholar_mail_alter(&$message) {

	switch ($message['id']) {
    //Edit the UCreate Email Message
		case 'ucreate_ucreate-create':
      	$params['subject'] = t('An account has been created for you at the !site', array('!site_name' => variable_get('site_name', 'Scholar\'s Web Sites Project')));
      	$a_body_parts = split("================================================",$message['body'],2);
      	$s_personal_message = (count($a_body_parts) == 2)?trim($a_body_parts[0]):"";

      	//Get the just created user
      	$n_new_user = db_result(db_query('SELECT u.uid FROM {users} u ORDER BY u.created DESC LIMIT 1'));
      	$o_user = user_load($n_new_user);
     	  $password = user_password();
     	  $edit = array('pass' => $password);
     	  $o_profile = content_profile_load('vsite_users_profile',$n_new_user);
     	  user_save($o_user,$edit);

      	$a_msg_variables = array(
      	  '!personal_message' => strlen($s_personal_message)?$s_personal_message."\n================================================\n\n":"",
			    '!username' => $o_user->name,
			    '!site' => variable_get('site_name', 'Scholar\'s Web Sites Project'),
			    '!login_url' => user_pass_reset_url($o_user),
			    '!uri' => $base_url,
			    '!uri_brief' => preg_replace('!^https?://!', '', $base_url),
			    '!mailto' => $o_user->mail,
			    '!date' => format_date(time(), 'medium', '', NULL, $message['language']->language),
			    '!login_uri' => url('user', array('absolute' => TRUE, 'language' => $message['language'])),
			    '!edit_uri' => url('user/'. $o_user->uid .'/edit', array('absolute' => TRUE, 'language' => $message['language'])),
      	  '!password' => $password,
      	  '!firstname' => $o_profile->vsite_users_first_name[0],
			  );

			  //This is unused: Alternatively using the following username and temporary password:\n\nUsername: !username\nTemporary password: !password\n\nAfter logging in, you will be redirected to !edit_uri so you can change your password.\n\n

      	$message['body'] = t("Dear !firstname,\n\nA site owner at the !site has created an account for you. You may now log in by either clicking through on the following link or pasting it into your browser:\n\n !login_url\n\n(Note: This is a one-time login; it can be used only once.)\n\n\Sincerely,\nThe !site Team", $a_msg_variables);

    break;
  }

}

/**
 * Implementation of hook_form_alter()
 **/
function scholar_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'vsite_node_form':
      //Customize the "Site Information" form
      if(arg(0) != 'cp') break;

      $form['title']['#title'] = "Main Headline:";
      $form['title']['#description'] = "Usually: First and Last name ex.(John Q. Smith)";
      $form['og_description']['#title'] = "Sub Headline:";
      $form['og_description']['#description'] = "Usually: Title ex.(Director of Mathematics)";
      $form['field_vsite_address'][0]['#title'] = "Address Line";
      $form['field_vsite_address'][0]['#description'] = "Usually: Your Address ex.(Cambridge, MA 02118)";
      
    break;
    default:
    	
  }
}
