<?php

include_once('scholar_blog.features.inc');


function scholar_blog_scholar_vocabulary_defaults() {
  return array (
    0 => array (
    'name' => 'blog_categories', 
    'content_types' => array ('blog' => 1), 
    'properties' => array (), 
    'terms' => array (
      0 => array (
    	'name' => 'Government', 
    	'desription' => 'Government', 
    	'properties' => array () 
      ), 
      1 => array (
    	'name' => 'Methodology', 
    	'desription' => 'Methodology', 
    	'properties' => array () 
      ),
      2 => array (
    	'name' => 'Social computing', 
    	'desription' => 'Social computing', 
    	'properties' => array () 
      ),

      3 => array (
    	'name' => 'Social Networking', 
    	'desription' => 'Social Networking', 
    	'properties' => array () 
      ) 
    ) 
  ) 
 );
}