<?php

function scholarproject_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Scholar project slideshow');
      $blocks[1]['info'] = t('Scholar project big text');
      $blocks[2]['info'] = t('Scholar project tips - Create');
      $blocks[3]['info'] = t('Scholar project tips - Maintain');
      $blocks[4]['info'] = t('Scholar project tips - Control');
      $blocks[5]['info'] = t('Scholar project tips - Collaborate');
      $blocks[6]['info'] = t('Scholar project site examples');
      return $blocks;
      
    case 'view':
      switch ($delta) {
        case 0:
          $block = scholarproject_block_slideshow_view();
          break;
        case 1:
          $block = scholarproject_block_big_text_view();
          break;
        case 2:
          $block = scholarproject_create_view();
          break;
        case 3:
          $block = scholarproject_maintain_view();
          break;
        case 4:
          $block = scholarproject_control_view();
          break;
        case 5:
          $block = scholarproject_collaborate_view();
          break;
        case 6:
          $block = scholarproject_block_site_example_view();
          break;
      }
      return $block;
  }
}

function scholarproject_theme($existing, $type, $themeexisting, $type, $theme, $path){
  
  $path = drupal_get_path('module', 'scholarproject') . '/theme';
  
  //top bocks
  $items['project_slideshow'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-slideshow',
    'path' => $path,
  );
  
    $items['project_big_text'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-big-text',
    'path' => $path,
  );
  
  //middle blocks
  $items['project_create'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-create',
  'path' => $path,
  );
  
  $items['project_maintain'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-maintain',
  'path' => $path,
  );

  $items['project_control'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-control',
    'path' => $path,
  );
  
  $items['project_colaborate'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-colaborate',
    'path' => $path,
  );
  
  //bottom block
    $items['project_site_examples'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-site-examples',
    'path' => $path,
  );
  
  return $items;
 }

function scholarproject_block_slideshow_view(){
  return theme('project_slideshow');
}

function scholarproject_block_big_text_view(){
  return theme('project_big_text');
}

function scholarproject_block_create_view(){
  return theme('project_create');
}

function scholarproject_block_maintain_view(){
  return theme('project_maintain');
}

function scholarproject_block_control_view(){
  return theme('project_control');
}

function scholarproject_block_collaborate_view(){
  return theme('project_collaborate');
}

function scholarproject_block_site_example_view(){
  return theme('project_site_examples');
}