<?php

include_once('scholar_projects_front.features.inc');


function scholar_projects_front_context_active_contexts_alter(&$contexts){
  dpm($contexts); 
}


/**
 * hook block
 */
function scholar_projects_front_block($op = 'list', $delta = 0, $edit = array()){
  switch ($op) {
    case 'list' :
      $blocks[0]['info'] = t('row 1');
      $blocks[1]['info'] = t('row 2');
      $blocks[2]['info'] = t('row 3');
      //$blocks[3]['info'] = t('scholar project front block');
      return $blocks;
    case 'view' :
      switch ($delta) {
        case 0 :
          $block = scholar_projects_front_row1();
          break;
        case 1 :
          $block = scholar_projects_front_row2();
          break;

        case 2 :
          $block = scholar_projects_front_row3();
          break;
        case 3 :
          $block = scholar_projects_front_row4();
          break;

      }

      return $block;
  }
}

function scholar_projects_front_row1(){
  $block = array();
  $block['subject'] = '';
  $block['content'] = '<div id="content-row-1">' . theme('project_big_text') . '</div>';
  return $block;
}

function scholar_projects_front_row2(){
  $block = array();
  $block['subject'] = '';
  $block['content'] = '<div id="content-row-2">' . theme('project_create') . theme('project_maintain') . theme('project_control') . theme('project_collaborate') . '</div>' ;
  
  return $block;
}

function scholar_projects_front_row3(){
  $block = array();
  $block['subject'] = '';
  $output = '<h3>New Sites</h3>
  <div id="search-person">'. drupal_get_form('scholar_projects_front_search_sites_form') .'</div>
  <div id="new-sites">';
  $block['content'] =  '<div id="content-row-3">' . $output . theme('project_site_examples') . '</div>';
  return $block;
}

function scholar_projects_front_row4(){
  $block = array();
  $block['subject'] = '';
  $block['content'] = theme('project_site_examples');
  return $block;
}


function scholar_projects_front_theme(){
  
  $path = drupal_get_path('module', 'scholar_projects_front') . '/theme';
  
  //top bocks
  $items['project_slideshow'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-slideshow',
    'path' => $path,
  );
  
    $items['project_big_text'] = array(
    'arguments' => array(),
    'template' => 'project-big-text',
    'path' => $path,
  );
  
  //middle blocks
  $items['project_create'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-create',
  'path' => $path,
  );
  
  $items['project_maintain'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-maintain',
  'path' => $path,
  );

  $items['project_control'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-control',
    'path' => $path,
  );
  
  $items['project_collaborate'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-collaborate',
    'path' => $path,
  );
  
  //bottom block
    $items['project_site_examples'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-site-examples',
    'path' => $path,
  );
  
  return $items;
 }

 
 /// the example sites  ... not used for now
 function scholar_projects_front_preprocess_project_site_examples(&$vars){
  $vars['sites'] = array();
  $view = views_get_view('scholar_projects_front_sites');
  $view->init();
  $view->set_display('block_1');

  $view->display['block_1']->handler->options['items_per_page'] = 6;  // not working

  $view->execute();

  $results = array_slice($view -> result, 0, 6);
  foreach ( $results as $result ) {
    $sid = $result -> nid;
    $vsite = spaces_load('og', $sid, FALSE);
    $og_node = $vsite -> group;

//    if(!$vsite || !$vsite->settings['logo'] && !$vsite->settings['logo']['current_logo']){
//      $s_image_path = drupal_get_path('module','vsite_design')."/theme/images/default_logo.jpg";
//    }else{
//      $s_image_path = $vsite->settings['logo']['current_logo'];
//    }//Default image?
//
    $vars['sites'][]= array(
      'headline' => $og_node -> title,
      'sub_headline' => $og_node -> og_description,
      'photo' =>  theme_vsite_design_logo($vsite, $preset = 'scholar_projects_front_front_logo', $alt = '' , $title = '', $attributes = array(), $bypass_browser_cache =false, $b_as_link = TRUE),

      //'photo' => theme('imagecache', 'scholar_projects_front_front_logo', $s_image_path, $alt, $title,  $attributes),
    );
  }
}
 
function scholar_projects_front_menu(){
  $items = array();
 
  // nodeautocomplete callback for scholar 
  $items['scholar_projects_home'] = array(
    'type' => MENU_CALLBACK, 
    'title' => 'Scholars\'s Web Sites Project', 
    'page callback' => 'scholar_projects_front_homepage', 
    'access arguments' => array(
      'access content' 
    ), 
  );
  
  return $items;
}


function scholar_projects_front_homepage(){
  $vars['row1'] = scholar_projects_front_row1();
  $vars['row2'] = scholar_projects_front_row2();
  return $vars['row1']['content'] . $vars['row2']['content'];
  $vars['row1'] = theme('project_big_text');
  $vars['row2'] = theme('project_create') . theme('project_maintain') . theme('project_control') . theme('project_collaborate') ;
  $vars['row3'] = theme('project_site_examples');
  
  return theme('node',$vars);
}