<?php

function scholar_projects_front_theme(){

  $path = drupal_get_path('module', 'scholar_projects_front') . '/theme';

  //top bocks

  $items['project_top_links'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-top-links',
    'path' => $path,
  );

  $items['project_slideshow'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-slideshow',
    'path' => $path,
  );

    $items['project_big_text'] = array(
    'arguments' => array(),
    'template' => 'project-big-text',
    'path' => $path,
  );

  //middle blocks
  $items['project_create'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-create',
  'path' => $path,
  );

  $items['project_wordout'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-wordout',
  'path' => $path,
  );

  $items['project_control'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-control',
    'path' => $path,
  );

  $items['project_events'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-events',
    'path' => $path,
  );

  //bottom block
    $items['project_site_examples'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-site-examples',
    'path' => $path,
  );

  return $items;
 }


 /// the example sites  ... not used for now
 function scholar_projects_front_preprocess_project_site_examples(&$vars){
  $vars['sites'] = array();
  $view = views_get_view('scholar_projects_front_sites');
  $view->init();
  $view->set_display('block_1');

  $view->display['block_1']->handler->options['items_per_page'] = 6;  // not working

  $view->execute();

  $results = array_slice($view -> result, 0, 6);
  foreach ( $results as $result ) {
    $sid = $result -> nid;
    $vsite = spaces_load('og', $sid, FALSE);
    $og_node = $vsite -> group;

    $vars['sites'][]= array(
      'headline' => $og_node -> title,
      'sub_headline' => $og_node -> og_description,
      'photo' =>  theme_vsite_design_logo($vsite, $preset = 'scholar_projects_front_front_logo', $alt = '' , $title = '', $attributes = array(), $bypass_browser_cache =false, $b_as_link = TRUE),

      //'photo' => theme('imagecache', 'scholar_projects_front_front_logo', $s_image_path, $alt, $title,  $attributes),
    );
  }
}

function scholar_projects_front_menu(){
  $items = array();

  // nodeautocomplete callback for scholar
  $items['scholar_projects_home'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Scholars\'s Web Sites Project',
    'page callback' => 'scholar_projects_front_homepage',
    'access arguments' => array(
      'access content'
    ),
  );

  return $items;
}


function scholar_projects_front_homepage(){

  return '<div id="content-row-1">' .
           theme('project_big_text') .
         '</div>' .
         '<div id="content-row-2">' .
           theme('project_create') .
           theme('project_wordout') .
           theme('project_control') .
           theme('project_events') .
         '</div>' ;
}
/**
 * Implementation of hook_preprocess_page()
 */
function scholar_projects_front_preprocess_page(&$vars){
  if (!module_exists('scholarregister')) return;
  global $user;

  //we always allow admin and users with "vsite create access" to see site registration button.
  //and we allow anonymous users to create a new user account and new site
  if ( node_access('create', variable_get('scholar_content_type', 'vsite' )) || in_array('anonymous user', $user -> roles)) {
    $allow = TRUE;
  }

  // all authenticated users
  else{
    // site-owners
    if ($vsites = vsite_get_vsite_by_owner($user->uid)){
      $allow = scholarregister_vsite_exists_access($vsites);
      $site_link = (count($vsites) > 1) ? 'user' : $vsites[0] -> purl;
    }
    //  non-site owners
    else{
      $allow = TRUE;
    }
  }
  //link for front page button
    $vars['front_button_link'] = ($allow) ? l('Get your web site!', 'site/register') : l('Go to your site', $site_link);
  $vars['front_top_links'] = theme('project_top_links');
}
