<?php 

/**
 * implementation of hook_menu()
 */
function pathauto_ajax_menu() {
	$items['pathauto_ajax/alias_js'] = array(
		'page callback' => 'pathauto_ajax_alias_js',
		'type' => 'MENU_CALLBACK',
		'access arguments' => array('access content'),
	);
	return $items;
}

/**
 * implementation of hook_form_alter()
 */
function pathauto_ajax_form_alter(&$form, $form_state, $form_id) {

  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id && isset($form['path']['pathauto_perform_alias'])) {
  	drupal_add_js(drupal_get_path('module', 'pathauto_ajax') . '/pathauto_ajax.js');
  }
  	/*
  	//attach ahah event.  currently targets checkbox.
		$form['path']['pathauto_perform_alias']['#ahah'] = array(
			'event' => 'click',
			'wrapper' => 'edit-path',
			'effect' => 'fade',
			'path' => 'pathauto_ajax/alias_js',
			'method' => 'replace',
		);
	}*/
	
	//		dsm($form['path']);
}

function pathauto_ajax_alias_js() {
	
	//see http://drupal.org/node/331941 for filling this out further
	$output = 'helloworld';
	drupal_json(array('status' => TRUE, 'data' => $output));
}