<?php

/**
 * Implementation of hook_views_api().
 */
function vsite_views_api(){
  return array(
    'api' => 2 
  );
}

/**
 * finds all the view declared in files ending with ".views"
 */
function vsite_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'vsite'), '.view');
  foreach ($files as $absolute => $file) {
    require $absolute;
    if (isset($view)) {
      $views[$view -> name] = $view;
    }
  }
  return $views;
}



/** API functions **/


/**
 * API function for getting the active site
 */
function vsite_get_vsite(){
  $space = spaces_get_space();
  $scholar_content_type = variable_get('scholar_content_type', 'scholarsite');
  if ($space && $space -> type == 'og' && $space -> group -> type == $scholar_content_type ){
    return $space;
  }
  else {
    return NULL;
  }
}


/**
 * API function for testing wether we are on the front page of a vsite
 * TODO there are different ways of doing this
 * - as a full context "context_vsite_home" which has bloocks etc
 * - set context in hook init and then get it here
 */
function vsite_is_front(){
  $vsite = vsite_get_vsite();
  $active_menu = menu_get_item();
  return ($vsite && $active_menu['path'] == 'home') ? TRUE : FALSE;
}