<?php

function scholar_register_strongarm(){
  $conf = array();
  //allow users to register accounts
  $conf['user_register'] = 1;  
  return $conf;
}

function scholar_register_mail_alter(&$message){
  //echo "<pre>"; print_r($message); die;
   if ($message['id'] == 'user_register_no_approval_required') { 
 
  }
}

/**
 * Implementation of hook_user.
 */
function scholar_register_user($op, &$edit, &$account, $category = NULL){
  switch ($op) {
    case 'login' :
      // if is a site owner ...
      if ($vsite = scholar_register_siteowner_path($account)) {
        //For login lets send them to thier domain
        if($vsite->settings['generic']['vsite_domain']) $vsite->purl_provider = 'vsite_domain';

        // if is logging in for the first time or need to reset password
        if (($account->login == 0) || (arg(0) == 'user' && arg(1) == 'reset')) {
          purl_goto("cp/users", array(
          'purl' => array(
          'provider' => $vsite->purl_provider,
          'id' => $vsite->sid
          )
          ));
        }
        else {
          // redirect them to their home page
          $vsite->redirect('home');
        }
      }
      break;
  }
}

function scholar_register_form_alter(&$form, $form_state, $form_id){
    if ($form_id == 'user_register'){    

    $path = drupal_get_path('module', 'scholar_register');
    drupal_add_css($path .'/scholar_register.css', 'module', 'all', FALSE);      
    
        //change email field description
    $form['mail']['#description'] =  t('A valid e-mail address is required. All e-mails from the Scholar Web Sites Project will be sent to this address.');    
    
      global $base_url;
  // domain name
  $form['domain'] = array(
      '#type' => 'textfield', 
      '#title' => t('Your Domain Name'), 
      '#required' => TRUE, 
      '#field_prefix' => $base_url . '/', 
      '#size' => 20, 
      '#weight' => 10,
      '#default_value' => $form_values['name'], 
      '#description' => t('Example the choice of \'jdoe\' would result in domain name: %site. Your choice must be at least four characters long, and comprise of alphanumeric characters only.', array(
          '%site' => $base_url . '/jdoe' 
      )), 
  );    
 
    $form['#validate'][] = 'scholar_register_signup_form_validate';
    $form['#submit'][] = 'scholar_register_signup_form_submit';
    }  	
}

/**
 * validation callback for the registration form
 */
function scholar_register_signup_form_validate($form, &$form_state){
  if (isset($form_state['values']['notify'])){
    //unset($form_state['values']['notify']);
  }
}

/**
 * the submit handler for the registration form
 */
function scholar_register_signup_form_submit($form, &$form_state) {

  $name = $form_state ['values'] ['name'];
  $mail = $form_state ['values'] ['mail'];
  $domain = $form_state ['values'] ['domain'];

  //load the user
  $user = user_load(array('name' => $name));



  install_include(array('user'));
  //add role to user account
  $rid = install_get_rid(variable_get('scholar_manager_role', 'scholar admin'));
  install_add_user_to_role($user -> uid, $rid);

  // 2. create the site
  $vsite = scholar_register_vsite_create($name, $mail, $domain);

  if (!$vsite){
    // TODO - need somthing here
  }
  else{
    // 3. send e-mail to the user with one-time login link
    scholar_register_notify_user($vsite, $user);
  }
}

/**
 * Function returns vsite object when passed user object if user owns vsite
 * otherwise returns false
 */

function scholar_register_siteowner_path($account){
  
  // if is a site owner redirec to her site home page
  //dpm($account -> og_groups);
  if (isset($account->og_groups) && is_array($account->og_groups)) {
    foreach ( $account->og_groups as $group ) {
      //dpm($group);
      if ($group['uid'] == $account->uid) {
        $vsite = spaces_load("og", $sid = $group['nid'], $is_active = FALSE);
        return $vsite;
      }
    }
  }
  return false;
}


function scholar_register_notify_user($vsite, $user){
  global $language;
  $params = array();
  $from = variable_get('site_mail', ini_get('sendmail_from'));

     //add vsite and user object
   $params['vsite'] = $vsite;
   $params['user'] = $user;
  
  $params['subject'] = t("A Scholars' Web Site has been created for you", array(
    '!site_name' => variable_get('site_name', 'Scholar\'s Web Sites Project')
  ));

  $scholar_site_url =  $site_url = url("node/" . $vsite -> sid, $options = array('absolute' => TRUE));
  $timestamp = time();
  
  $msg_variables = array(
    // '!personal_message' => strlen($s_personal_message) ? $s_personal_message . "\n================================================\n\n" : "",
    '!username' => $user->name,
    '!site' => variable_get('site_name', "Scholars' Web Sites Project"),
    '!scholar_site_url' => $scholar_site_url,
    //'!login_url' => url("user/reset/$user->uid/$timestamp/". user_pass_rehash($user->pass, $timestamp, $user->login), array('absolute' => TRUE)),
    '!login_url' => user_pass_reset_url($user),
    '!uri' => $base_url,
    '!uri_brief' => preg_replace('!^https?://!', '', $base_url),
    '!mailto' => $user->mail,
    '!date' => format_date(time(), 'medium', '', NULL, $message['language']->language),
    '!login_uri' => url('user', array(
      'absolute' => TRUE,
      'language' => $message['language']
    )),
    '!site_url' => url('node/' . $vsite->sid),
    '!edit_uri' => url('user/' . $user->uid . '/edit', array(
      'absolute' => TRUE,
      'language' => $message['language']
    )),
    '!scholar_edit_url' => url($vsite -> purl . "/cp/users/myaccount", array('absolute' => TRUE)),
    '!password' => $password
  );


  $body .= t("Hi !username,\n\nYour web site at !site has been activated.\n\nYour web site url is !scholar_site_url \n\nYou may now log in by clicking on this link or copying and pasting it in your browser: \n\n !login_url \n\nThis is a one-time login, so it can be used only once. After logging in, you will be redirected to !scholar_edit_url so you can change your password. Once you have set your own password, you will be able to log in to !login_uri in the future with username:\n\n!username\n\nWe hope you will enjoy your new web site.\n\n Sincerely,\nThe !site Team", $msg_variables);

  $params['body'] = $body;
  if (! drupal_mail('scholar_register', 'scholar-register-notify', $user->mail, $language, $params, $from)) {
    drupal_set_message(t('Error sending notification mail to user.'), 'error');
  }

}

function scholar_register_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
  
  //these values be used with any mail alter hooks
 $message['vsite'] = $params['vsite'];
 $message['user'] = $params['user'];
}


/**
 * Create a scholar vsite
 */
function scholar_register_vsite_create($name, $mail, $domain){
  vsite_include('vsiteapi');
  return vsite_vsite_create($name, $mail, $domain);
}


/** Validation functions **/

function scholar_register_validate_name($name){
  if ($error = user_validate_name($name)){
    return $error;
  }
  elseif (_scholar_register_domain_exists($name) || _scholar_register_name_exists($name)){
    return "username \"$name\" is taken";
  }
}

function scholar_register_validate_domain($domain){
  if ($error = user_validate_name($domain)){  // the same validation as the username
    return $error;
  }
  elseif (_scholar_register_domain_exists($domain) || _scholar_register_name_exists($domain)){
    return "domain \"$domain\" is taken";
  }
}

function _scholar_register_domain_exists($domain){
  // check domain availability
  $query = "SELECT value FROM {purl} WHERE value='%s'";
  $existing_purl = db_result(db_query($query, $domain));

  return $existing_purl ? TRUE : FALSE;
}

function _scholar_register_name_exists($name){
  // check domain availability
  $query = "SELECT name FROM {users} WHERE name='%s'";
  $existing_name = db_result(db_query($query, $name));

  return $existing_name ? TRUE : FALSE;
}

function _scholar_register_mail_exists($mail){
  // check domain availability
  $query = "SELECT mail FROM {users} WHERE mail='%s'";
  $existing_mail = db_result(db_query($query, $mail));

  return $existing_mail ? TRUE : FALSE;
}


function _scholar_register_vsite_error(){
  return ctools_ajax_command_replace('#submit-suffix', 'The web site cannot be created. Please fix the errors and try again.');
  //ctools_ajax_render($commands);
}