<?php

function vsite_users_menu(){
  $items = array();
  
  $items['cp/users'] = array(
    'title' => 'Users',
    'page callback' => 'cp_route', 
    'weight' => 2, 
  );
  
  $items['cp/users/myaccount'] = array(
    'title' => 'My account',
    'page callback' => 'vsite_users_myaccount',
    'file' => 'vsite_users.pages.inc',
    'weight' => 0, // should be the first one
  );
  
  $items['cp/users/members'] = array(
    'title' => 'Members',
    'page callback' => 'vsite_users_members',
    'file' => 'vsite_users.pages.inc',
    'weight' => 1, // should be the first one
  );  
  
  // make them all part of 'cp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'cp';
    $items[$path]['access callback'] = 'cp_access_cp'; 
  }
  return $items;
}