<?php

/**
 * Implements hook_menu
 */
function vsite_users_menu(){
  $items = array();
  
  $items['cp/users'] = array(
    'title' => 'Users',
    'page callback' => 'cp_route', 
    'weight' => 2, 
  );
  
  $items['cp/users/myaccount'] = array(
    'title' => 'My Account',
    'page callback' => 'vsite_user_edit',
    'access callback' => 'vsite_user_edit_access',
    'file path' => drupal_get_path('module', 'user'),
    'file' => 'user.pages.inc',
  );
  
  $items['cp/users/myaccount/edit'] = array(
    'title' => 'My Account',
    'page callback' => 'vsite_user_edit',
    'access callback' => 'vsite_user_edit_access',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file path' => drupal_get_path('module', 'user'),
    'file' => 'user.pages.inc',
  );
  
  $items['cp/users/myaccount/personal'] = array(
    'title' => 'Personal Information',
    'page callback' => 'vsite_user_content_profile_edit_page',
    'page arguments' => array('vsite_users_profile'),
    'access callback' => 'vsite_user_edit_access',
    'weight' => 1,
    'file' => 'node.pages.inc',
    'file path' => drupal_get_path('module', 'node'),
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['cp/users/members'] = array(
    'title' => 'Members',
    'page callback' => 'vsite_users_members',
    'file' => 'vsite_users.pages.inc',
    'weight' => 1, // should be the first one
  );  
  
  // make them all part of 'cp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'cp';
    $items[$path]['access callback'] = 'cp_access_cp'; 
  }
  return $items;
}

/**
 * Return the owner of the vsite
 * @return user
 */
function vsite_user_edit(){
	$vsite = vsite_get_vsite();
  if(!$vsite) return false;
  
  return user_edit(user_load($vsite->group->uid));
}

/**
 * Return the owner of the vsite
 * @return user
 */
function vsite_user_edit_access(){
	$vsite = vsite_get_vsite();
  if(!$vsite) return false;
  
  return user_edit_access(user_load($vsite->group->uid));
}

/**
 * Function that loads the content profile form for a site
 * @return form
 */
function vsite_user_content_profile_edit_page($s_type){
	$vsite = vsite_get_vsite();
	if(!$vsite) return false;
	
	return content_profile_page_edit($s_type,user_load($vsite->group->uid));
}

/**
 * Change the form theme to ours without the extra node settings displayed 
 */
function vsite_users_theme() {

    $themes = array(
        'vsite_users_profile_node_form' => array(
            'arguments' => array('form' => NULL),
            'path' => drupal_get_path('module', 'vsite_users').'/theme',
            'file' => 'vsite_users.theme.inc',
        ),
    );
    return( $themes );
}

/**
 * For the content profile form:
 * - Hide the preview and delete buttons
 * - Save as the site owner 
 */
function vsite_users_form_vsite_users_profile_node_form_alter(&$form, &$form_state){
	if(isset($form['#redirect'])) unset($form['#redirect']);
	
	if(isset($form['buttons']['submit'])){
		$form['buttons']['submit']['#submit'][] = 'vsite_users_form_vsite_users_profile_node_submit';
	}
	
	$form['buttons']['preview']['#access'] = FALSE;
  $form['buttons']['delete']['#access'] = FALSE;
	
	$vsite = vsite_get_vsite();
  if($vsite && isset($form['uid'])){
    $form['uid']['#value'] = $vsite->group->uid;
  }
  
  // Set the author value - note that this works only for admins.
  if ($vsite && ($user = user_load($vsite->group->uid))) {
    $form['author']['name']['#default_value'] = $user->name;
    $form['name'] = array('#type' => 'value', '#value' => $user->name);
  }
}

/**
 * In CP keep the form from redirecting to the node 
 */
function vsite_users_form_vsite_users_profile_node_submit($form, &$form_state){
	if(isset($form_state['redirect'])) unset($form_state['redirect']); //No Redirect for you
}

/**
 * Implementation of hook_user().
 */
function vsite_users_user($op, &$edit, &$account, $category = NULL) {
  global $user;

  switch ($op) {
    case 'load':
    	$node = content_profile_load('vsite_users_profile', $account->uid);
      $account->content['content_profile'] = content_profile_show_profiles($account->uid);
      $t = content_profile_get_types('names');
    break;
  }
}

