<?php

/* API */

function vsite_contextual_init() {
  if (user_is_logged_in()) {
    drupal_add_css(drupal_get_path('module', 'vsite_contextual').'/vsite_contextual.css');
  }
}

/**
 * Retrieve the admin links for a given object.
 */
function vsite_contextual_get_admin_links($type, $object){

  $links = module_invoke_all('vsite_admin_link', $type, $object);
  drupal_alter('vsite_admin_link', $links, $type, $object);

  return $links;
}

/* IMPLEMENTATIONS */

/**
 * Implementation of hook_scholar_admin_link() on behalf of the node module.
 */
function node_vsite_admin_link($type, $object){
  $links = array();
  if ($type == 'node') {
    $path = "node/{$object->nid}/edit";
    $item = menu_get_item($path);
    if ($item && $item['access']) {

      $links['node-edit'] = array(
        'title' => t('Edit'),
        'href' => $path,
        'attributes' => array(
          'class' => 'icon-edit'
        ),
        'query' => array(
          'destination' => $_GET['q']
        )
      );
    }
    $path = "node/{$object->nid}/delete";
    $item = menu_get_item($path);
    if ($item && $item['access']) {
      $links['node-delete'] = array(
        'title' => t('Delete'),
        'href' => "node/{$object->nid}/delete",
        'attributes' => array(
          'class' => 'icon-delete'
        ),
        'query' => array(
          'destination' => $_GET['q']
        )
      );
    }
  }
  return $links;
}

/*
 * Implementation of hook_vsite_admin_link
 */
function block_vsite_admin_link($type, $object) {
  $links = array();
  if ($type != 'block') return;

  $links['block-test'] = array(
    'title' => t('Block Test'),
    'href' => 'test',
  );

  // if this block comes from Views, the admin links will overlap
  // merge them into one set of links
  if ($object->module == 'views') {
    $view_name = explode('-',$object->delta);
    // get view from id
    $view = views_get_view($view_name[0]);
    // get links from id
    $links = array_merge($links, vsite_contextual_get_admin_links('view', $view));
  }

  return $links;
}

function views_vsite_admin_link($type, $object) {
  $links = array();
  if ($type != 'view') return;

  $links['views-test'] = array(
    'title' => t('Views Test'),
    'href' => 'test',
  );

  return $links;
}

function block_vsite_admin_link_alter(&$links, $type, $object) {
  static $views = array();

  if ($type == 'view') {

  }
}

/* PREPROCESS FUNCTIONS */

function vsite_contextual_preprocess_node(&$vars) {
  $node = &$vars['node'];
  // node admin links (see hook_vsite_admin_link)
  if ($links = vsite_contextual_get_admin_links('node', $node)) {
    drupal_add_css(drupal_get_path('module', 'vsite_contextual').'/vsite_contextual.css');
    $vars['vsite_admin_links'] = theme('ctools_dropdown', "Admin", $links , false, 'vsite-admin');
  }
}

function vsite_contextual_preprocess_block(&$vars) {
  $block = &$vars['block'];
  if ($links = vsite_contextual_get_admin_links('block', $block)) {
    drupal_add_css(drupal_get_path('module', 'vsite_contextual').'/vsite_contextual.css');
    $block->content .= theme('ctools_dropdown', "", $links , false, 'vsite-admin');
  }
}

function vsite_contextual_preprocess_view_views(&$vars) {
  $view = &$vars['view'];
  if ($links = vsite_contextual_get_admin_links('view', $view)) {
    drupal_add_css(drupal_get_path('module', 'vsite_contextual').'/vsite_contextual.css');
    $vars['pager'] .= theme('ctools_dropdown', "", $links , false, 'vsite-admin');
  }
}