<?php

function og_views_custom_menu(){
  $items = array();
  $items['try'] = array(    // view_name, type, og
    'title' => 'try',
    'page callback' => 'og_custom_view_try',
    'access arguments' => array('access content'),
  );
  
  $items['viewscustom/%/%/%/%ctools_js'] = array(    // view_name, type, og
    'title' => 'Customize view',
    'page callback' => 'og_custom_view_callback',
    'page arguments' => array(1,2,3,4),
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function og_custom_view_try(){
  dialog_add_js();
 return l('Simple test', 'viewscustom/somename/footer/2/nojs', array('attributes' => array('class' => 'ctools-use-dialog')));
}

function og_custom_view_callback($view_name, $type, $nid, $js = FALSE){
  $form_id = 'og_custom_view_form';
  
  switch ($type) {
    case 'header':
      $title = t('Change Header');
      break;
    case 'title':
      $title = t('Change title');
      break;
    case 'footer':
      $title = t('Change footer');
      break;
  }
  
  if ($js) {
    ctools_include('ajax');
    $form_state = array(
      'ajax' => TRUE, 
      'title' => $title, 
    );
    
  $form_state['t'] = 'header';
  $form_state['args'] = array(array('type' => 'header'));
    
    $output = dialog_form_wrapper($form_id, $form_state);
    if (empty($output)) {
      //$output[] = dialog_command_display('Welcome','xxxx');
      $output[] = ctools_ajax_command_redirect('user');
    }

    ctools_ajax_render($output);
  
  } else {
  
  return drupal_get_form($form_id,'header');
  }
}



function og_custom_view_form($form_id,$t){
  dpm($t);
  $form = array();
  $form[$t['type']] = array(
    '#type' => 'textarea', 
    '#title' => t('bar'), 
  );
  
  $form['submit'] = array(
   '#type' => 'submit', 
   '#value' => t('Import')
  );
  
  return $form;
}


function og_custom_view_form_submit($form, &$form_state){
  dpm($form_state);
}

/**
 * save an entry in the database
 * @param unknown_type $nid
 * @param unknown_type $view_name
 * @param unknown_type $type
 * @param unknown_type $value
 */
function og_custom_view_set($nid, $view_name, $type, $value){
  
  $table = 'og_custom_view';
  $record = new stdClass();
  $record -> nid = $nid;
  $record -> view_name = $view_name;
  $record -> type = $type;
  $record -> value = $value;
  
  if (!og_custom_view_get($nid, $view_name, $type, $value)){
    drupal_write_record($table, $object);
  }
  else {
    drupal_write_record($table, $object, array('nid', 'view_name', 'type'));
  }
}

/**
 * get an entry from the database
 * @param unknown_type $nid
 * @param unknown_type $view_name
 * @param unknown_type $type
 */
function og_custom_view_get($nid, $view_name, $type){
  $sql = "SELECT value FROM {og_views_custom} WHERE nid=%d AND view_name='%s' AND type='%s'";
  $result = db_result(db_query($sql, $nid, $view_name, $type));
  return $result;
}

