<?php 

/*
 * dash submodule
 * provides sword destination to make deposits to harvard dash
 */

/* impelmentation of hook_sword_submodule */
function example_sword_submodule() {
	$module = new stdClass();
	$module->name = 			'example';
	$module->title =			'Example';
	$module->location = 	'http://example.com/';
	$module->username = 	'jsagotsky@iq.harvard.edu';
	$module->password =   'password';
	$module->root_in  =   '/tmp/sword';
	$module->subdir_in =  'example';
	$module->root_out =   '/tmp/sword';
	$module->file_out =   'example_files.zip';

	return $module;
}
