<?php

include_once('os_wysiwyg_fields.features.inc');

function os_wysiwyg_fields_wysiwyg_fields_add_js($type) {
  switch ($type) {
    case 'node_form':
      if (file_exists($js = drupal_get_path('module', 'os_wysiwyg_fields') . "/theme/os_wysiwyg_fields.js")) {
        drupal_add_js($js);
      }
  }
}

function os_wysiwyg_fields_field_formatter_info() {
  return array(
    'os_file_description' => array(
      'label' => t('OS: File Description'),
      'field types' => array('filefield'),
      'description' => t('Display File Description as Link to File'),
    ),
  );
}

function os_wysiwyg_fields_theme() {
  return array(
    'os_wysiwyg_fields_formatter_os_file_description' => array (
      'arguments' => array(
        'element' => null,
      )
    )
  );
}

function theme_os_wysiwyg_fields_formatter_os_file_description($element) {
  $item = $element['#item'];
  return '<a href="'.$GLOBALS['base_path'].$item['filepath'].'">'.$item['data']['description'].'</a>';
}

function os_wysiwyg_fields_insert_styles() {
  return array(
    'os_file_description' => array(
      'label' => t('File Description'),
      'weight' => -10,
    ),
  );
}

function os_wysiwyg_fields_insert_content($item, $style, $widget) {
  $item['data']['description'] = $item['data']['description'] == '' ? '__description__' : $item['data']['description'];

  $element = array(
    '#formatter' => $style['name'],
    '#item' => $item,
  );

  return theme('os_wysiwyg_fields_formatter_' . $element['#formatter'], $element);
}

function os_wysiwyg_fields_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] != 'node-form') return;

  // look for filefields with wysiwyg somewhere in there
  // add prerender to change weights of buttons around
  foreach (array('field_os_inline_files', 'field_os_inline_image') as $field) {
    if (!is_array($form[$field])) continue;
    foreach ($form[$field] as $delta => $data) {
      if (is_numeric($delta)) {
        $form[$field][$delta]['#pre_render'][] = 'os_wysiwyg_fields_inline_field_prerender';
      }
    }
  }
  // remove extra oembed field
  if (is_null($form['nid']['#value'])) {
    unset($form['field_os_inline_oembed'][1]);
  }
}

function os_wysiwyg_fields_inline_field_prerender($elements) {
  if (isset($elements['insert']))
    $elements['insert']['#weight'] = 100;

  if ($elements['#field_name'] == 'field_os_inline_files' && $elements['#post']['op'] == 'Upload' && is_array($elements['#value'])) {
    $elements['#default_value']['data']['description'] = $elements['#value']['filename'];
    $elements['data']['description']['#value'] = $elements['#value']['filename'];
  }
  return $elements;
}

function os_wysiwyg_fields_preprocess_oembed(&$vars) {

}
