<?php

include_once('scholar_reader.features.inc');

function scholar_reader_init(){
  drupal_add_css(drupal_get_path('module', 'scholar_reader') .'/theme/scholar-reader.css');
}

function scholar_reader_menu() {
  $menu = array();

  $menu['features/scholar_reader'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scholar_reader_settings'),
    'access callback' => module_exists('spaces') ? 'spaces_access_admin' : 'user_access',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'scholar_reader.pages.inc',
  );

  return $menu;
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_reader_context_links_alter(&$links) {
  if (!empty($links['feed'])) {
    $links['feed']['query'] = drupal_get_destination();
  }
}

/**
 * hook vsite_sidgets

 */
function scholar_reader_vsite_widgets(){
  $items = array();
  $items['views-scholar_reader-block_1'] = array(
        'module' => 'views',
        'delta' => 'scholar_reader-block_1',
        'weight' => 20,
        'region' => false,
        'status' => '0',
        'label' => 'List of Feeds',
        'type' => 'context_ui',
      );

  $items['views-scholar_reader-block_2'] = array(
        'module' => 'views',
        'delta' => 'scholar_reader-block_2',
        'weight' => 21,
        'region' => false,
        'status' => '0',
        'label' => 'Latest feed items',
        'type' => 'context_ui',
  );

  $items['scholar_reader-my_twitter_feed'] = array(
        'module' => 'scholar_reader',
        'delta' => 'my_twitter_feed',
        'weight' => 20,
        'region' => false,
        'status' => '0',
        'label' => 'Twitter Feed',
        'type' => 'context_ui',
      );

  return $items;
}


/**
 * Implementation of hook_data_views_handlers_alter().
 */
function scholar_reader_data_views_handlers_alter(&$handlers) {
  dpm($handlers);
  $handlers['field']['scholar_reader_handler_field_description'] = 'scholar_reader_handler_field_description';
}


/**
 * Implementation of hook_form_alter().
 * Used to add validation to the feed addition
 */
function scholar_reader_form_alter(&$form, $form_state, $form_id) {
  // Content type form.
  if ($form_id == 'feed_node_form' && $form['type']['#value'] == 'feed') {
    $form['#validate'][] = 'scholar_reader_feed_validate';

    if(!$form['#vertical_tabs']) $form['#vertical_tabs'] = array();
    $form['#vertical_tabs']['feeds'] = 0; //Disable vert. tabs
  }
}

/**
 * Validate the feed
 *
 * @param $form
 * @param $form_state
 */
function scholar_reader_feed_validate($form, &$form_state) {
  if (!strlen($form_state['values']['feeds']['FeedsHTTPFetcher']['source'])) {
    return;
  }

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = trim($form_state['values']['feeds']['FeedsHTTPFetcher']['source']);

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = str_ireplace("feed:http://","http://",$form_state['values']['feeds']['FeedsHTTPFetcher']['source']); //For Safari Users

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = str_ireplace("feed://","http://",$form_state['values']['feeds']['FeedsHTTPFetcher']['source']); //For Safari Users

  $success = (valid_url($form_state['values']['feeds']['FeedsHTTPFetcher']['source'],true) && ($status = drupal_http_request($form_state['values']['feeds']['FeedsHTTPFetcher']['source'])) && !strlen($status->error));
  if(!$success){
  	form_error($form, t('Can\'t connect to '.$form_state['values']['feeds']['FeedsHTTPFetcher']['source'].'. Invalid feed URL, please check that the URL is valid.'), 'error');
  }
}

/**
 * Define the scholar reader blocks with hook block
 */
function scholar_reader_block($op = 'list', $delta = false, $edit = array()) {
  if ($op == 'list') {
    $blocks['my_twitter_feed']['info'] = t('Twitter Updates');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 'my_twitter_feed':
        return _scholar_reader_twitter_wgt();
    }
  }
}


/**
 * Renders twitter block for users
 */
function _scholar_reader_twitter_wgt(){

	if(!($vsite = vsite_get_vsite()) || !$vsite->access_feature($op = 'view', 'scholar_reader')) return array();

	//Do they have their feed set?
	$s_twitter = variable_get('scholar_reader_twitter_username', NULL);
	if(!strlen($s_twitter)) return array();

	//Fix this? Probably a better way of getting the twitter id..
  $twitterid = str_replace("from:",'',$s_twitter);
	$output = twitter_pull_render ($s_twitter);
	if (strpos($twitterid, '#') !== 0) {
    $output .= '<div class="twitter-followme">' . l('Follow me on Twitter','http://twitter.com/' . $twitterid) .'</div>';
	}
	return array('subject' => "Twitter Updates",'content' => $output);
}
