<?php

function vsite_front_init(){
  $active_menu = menu_get_item();
  if ($active_menu['path'] == 'cp/settings/front'){
    drupal_add_css(drupal_get_path('module', 'vsite_front') .'/theme/vsite_front.css');
  }
}

function vsite_front_menu(){
  $items = array();
  $items['home'] = array(
    'type' => MENU_CALLBACK,
    'title' => '',
    'page callback' => 'vsite_front_home',
    'file' => 'vsite_front.pages.inc',
    'access arguments' => array('access content'),
    'weight' => 0,
  );
  return $items;
}

/**
 * Implementation of hook_spaces_settings().
 */
function vsite_front_spaces_settings(){
  return array(
    'front' => array(
      'class' => 'vsite_front_settings_front', 
      'file' => drupal_get_path('module', 'vsite_front') . '/includes/vsite_front.settings.inc' 
    ) 
  );
}

/**
 * Implementation of hook_views_api().
 */
function vsite_front_views_api(){
  return array(
    'api' => 2 
  );
}

/**
 * Implementation of hook flag_default_flags
 * @return array - default flag
 */
function vsite_front_flag_default_flags(){
  scholar_include('scholarapi');
  $scholar_types = array_keys(scholar_content_types());
  
  $flags = array();
  $flags[] = array(
    'content_type' => 'node', 
    'name' => 'frontpage', 
    'title' => 'Save to Front Page', 
    'types' => $scholar_types, 
    'roles' => array(
      0 => '2' 
    ), 
    'global' => TRUE, 
    'flag_short' => 'Save to Front Page', 
    'flag_long' => 'Save to Front Page', 
    'flag_confirmation' => 'Saved to Front Page', 
    'unflag_short' => 'Remove from Front Page', 
    'unflag_long' => 'Remove from Front Page', 
    //   'unflag_confirmation' => 'Are you sure you want to remove?',
    'status' => TRUE, 
    'show_on_page' => FALSE, 
    'show_on_teaser' => FALSE, 
    'show_on_form' => FALSE, 
    'link_type' => 'toggle',  //normal, toggle, confirm
    'locked' => array(
      'name', 
      'show_on_page', 
      'show_on_teaser', 
      'show_on_form', 
      'global' 
    ) 
  );
  
  return $flags;
}