<?php

include_once('scholar_links.features.inc');

/**
* Implementation of hook_strongarm().
*/
function scholar_links_strongarm() {
  //module_load_include('inc', 'scholar_link', 'includes/scholar_link.settings_default');
  $conf = array();
  
  // standard group post
  $conf['og_content_type_usage_link'] = 'group_post_standard';
  
  // no comments
  $conf['comment_link'] = 0;
  
  // no diff, no preview 
  $conf['show_preview_changes_link'] = 0;
  $conf['show_diff_inline_link'] = 0;
  
  // vertical tab settings
  /*
  $conf['vertical_tabs_fieldsets_link'] =
    array ('menu','scholartaxonomy','revision_information');

  array (
    'menu' => TRUE,
    'scholartaxonomy' => TRUE,
    'author' => FALSE,
    'options' => FALSE,
    'path' => FALSE,
    'comment_settings' => TRUE,
    'og_nodeapi' => FALSE,
    'revision_information' => FALSE,
  );
*/
  
  // make it part of the features menu
  $conf['menu_primary_links_source'] = 'features';
  
  // publish by default
  $conf['node_options_link'] = array('status');
  /*
    'status' => TRUE,
    'promote' => FALSE,
    'sticky' => FALSE,
    'revision' => FALSE,
  );
  */
  /*
    array (
    0 => 'status',
    'status' => false,
    'promote' => false,
    'sticky' => false,
    'revision' => false,
  ),
   */
  
  return $conf;
}
