<?php

/**
 * @file
 * OS SimpleViews utility library.
 *
 * Provides some wrapper functions to programatically manipulate a given view
 * - Based on the simpleviews module
 * 
 * @todo
 * - configure nr of items
 */


/**
 * Default values for the view object 
 */
function os_simpleviews_default_data(){
  return array(
    'filter' => 'all nodes',  // @todo get the current context and the node type(s) associated with it, make that the default
    'style' => 'teasers', 
    'sort' => 'newest', 
    'argument' => '' 
  );
}

/**
 * Builds the view
 * @param $simpleview
 */
function os_simpleviews_build_view($simpleview = array()){
  $simpleview += os_simpleviews_default_data();
  module_load_include('inc', 'os_simpleviews', 'os_simpleviews');
  return _os_simpleviews_build_view($simpleview);
}

/**
 * Build the record editing chunk, in a reusable fashion.
 */
function os_simpleviews_get_edit_form($simpleview = array()){
  $simpleview += os_simpleviews_default_data();
  
  //$form['#theme'] = 'os_simpleviews_edit_form';  //@todo provide a theme hook or remove this
  

  $form['filter'] = array(
    '#type' => 'select', 
    '#title' => t('Display'), 
    '#options' => array(
      'all' => t('All posts') 
    ), 
    '#required' => TRUE, 
    '#default_value' => $simpleview['filter'] 
  );
  
  // os/vsite integration
  vsite_include('vsiteapi');
  $node_options = vsite_content_types();
  drupal_alter('vsite_content_types', $node_options);
  
  //$form['filter']['#options'] = array();
  

  foreach ( $node_options as $type => $name ) {
    $form['filter']['#options']['node:' . $type] = t('!type posts', array(
      '!type' => $name 
    ));
  }
  
  $form['sort'] = array(
    '#type' => 'select', 
    '#title' => t('Sorted'), 
    '#options' => array(
      'newest' => t('Newest first'), 
      'oldest' => t('Oldest first'), 
      'a-z' => t('By title') 
    ), 
    '#required' => TRUE, 
    '#default_value' => $simpleview['sort'] 
  );
  if (module_exists('statistics')) {
    $form['sort']['#options']['popular'] = t('By number of hits');
  }
  if (module_exists('votingapi')) {
    $form['sort']['#options']['top-rated'] = t('By rating');
  }
  
  $form['style'] = array(
    '#type' => 'select', 
    '#title' => t('As a'), 
    '#options' => array(
      //'full' => t('List of full posts'),
      'teasers' => t('List of teasers'), 
      'titles' => t('List of titles') 
    )//'grid' => t('Grid of thumbnails'),
    , 
    '#required' => TRUE, 
    '#default_value' => $simpleview['style'] 
  );
  
  drupal_alter('simpleview_reusable_form', $form, $simpleview);
  
  return $form;
}

/**
 * Implementation of hook_boxes_plugins().
 */
function os_simpleviews_boxes_plugins(){
  $info = array();
  
  $info['os_simpleviews_boxes_listing'] = array(
    'title' => 'Listing',  // i.e. view
    'description' => 'List of posts', 
    'tags' => array(
      'Content' 
    ), 
    'handler' => array(
      'class' => 'os_simpleviews_boxes_listing', 
      'file' => 'os_simpleviews_boxes_listing.inc', 
      'path' => drupal_get_path('module', 'os_simpleviews') . '/plugins', 
      'parent' => 'os_boxes_default' 
    ) 
  );
  
  return $info;
}