<?php

include_once('scholar_project.features.inc');

function scholar_project_theme(){
  
  $path = drupal_get_path('module', 'scholar_project') . '/theme';
  
  //top bocks
  $items['project_slideshow'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-slideshow',
    'path' => $path,
  );
  
    $items['project_big_text'] = array(
    'arguments' => array(),
    'template' => 'project-big-text',
    'path' => $path,
  );
  
  //middle blocks
  $items['project_create'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-create',
  'path' => $path,
  );
  
  $items['project_maintain'] = array(
  'arguments' => array('tree' => array()),
  'template' => 'project-maintain',
  'path' => $path,
  );

  $items['project_control'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-control',
    'path' => $path,
  );
  
  $items['project_collaborate'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-collaborate',
    'path' => $path,
  );
  
  //bottom block
    $items['project_site_examples'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'project-site-examples',
    'path' => $path,
  );
  
  return $items;
 }

function scholar_project_preprocess_project_site_examples(&$vars){
  $vars['sites'] = array();
  $view = views_get_view('scholar_project_sites');
  $view->init();
  $view->set_display('block_1');
  //dpm($view);
  $view->display['block_1']->handler->options['items_per_page'] = 6;  // not working

  $view->execute();

  $results = array_slice($view -> result, 0, 6);
  foreach ( $results as $result ) {
    $sid = $result -> nid;
    $vsite = spaces_load('og', $sid, FALSE);
    $og_node = $vsite -> group;

    if(!$vsite || !$vsite->settings['logo'] && !$vsite->settings['logo']['current_logo']){
    	$s_image_path = drupal_get_path('module','vsite_design')."/theme/images/default_logo.jpg";
    }else{
    	$s_image_path = $vsite->settings['logo']['current_logo'];
    }//Default image?
    
    $vars['sites'][]= array(
      'headline' => $og_node -> title,
      'sub_headline' => $og_node -> og_description,
      'photo' =>  theme_vsite_design_logo($vsite, $preset = 'scholar_project_front_logo', $alt = '' , $title = '', $attributes = array(), $bypass_browser_cache =false, $b_as_link = TRUE),
    
      //'photo' => theme('imagecache', 'scholar_project_front_logo', $s_image_path, $alt, $title,  $attributes),
    );
  }
}


function scholar_project_preprocess_page(&$vars){
  if (drupal_is_front_page()){
    $vars['row1'] = theme('project_big_text');
    $vars['row2'] = theme('project_create') . theme('project_maintain') . theme('project_control') . theme('project_collaborate') ;
    $vars['row3'] = theme('project_site_examples');
    $block = views_page($view_name = 'scholar_project_sites', $display = 'block_1');
   // $vars['row3'] = $block['content'];
    
  }
}