<?php

include_once('scholar_project.features.inc');

function scholar_project_preprocess_page($vars){
  $vars['body_classes'] .= ' scholar-projects-distro';
}

/**
 * Define the project blocks with hook block
 */
function scholar_project_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Project site logo');
    $blocks[1]['info'] = t('Project site info');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        return _scholar_project_logo_wdgt();
      case 1:
       return _scholar_project_basicinfo_wdgt();
    }
  }
}

/**
 * Define the avalible vsite widgets
 * @return array
 */
function scholar_project_vsite_widgets(){

  return array(
    'scholar_project-0' => array(
      'module' => 'scholar_project',
      'delta' => '0',
      'weight' => 20,
      'region' => 'header_left',
      'label' => 'Project Site Logo',
      'cache' => BLOCK_CACHE_CONTENT_CACHE,
      'cache_keys' => array(
        'node' => array(variable_get('scholar_content_type', 'vsite') => variable_get('scholar_content_type', 'vsite')),
        'os_og' => array('current' => 'current'),
      ),
    ),
    'scholar_project-1' => array(
      'module' => 'scholar_project',
      'delta' => '1',
      'weight' => 20,
      'region' => 'header_main',
      'label' => 'Project site info',
      'cache' => BLOCK_CACHE_CONTENT_CACHE,
      'cache_keys' => array(
        'node' => array(variable_get('scholar_content_type', 'vsite') => variable_get('scholar_content_type', 'vsite')),
        'os_og' => array('current' => 'current'),
      ),
    ),
  );

}

/**
 * Scholar Basic Info Widget Content
 * @return array
 */
function _scholar_project_basicinfo_wdgt(){
  $scholar = vsite_get_vsite();
  
  $block = array();
  if(!$scholar) return $block;
  
  $block['subject'] = t('');
  $block['content'] = l('Project Site (' . $scholar->group->purl . ')', $scholar->get_absolute_url());

  if(!strlen($scholar->group->title)) return $block;

  $output =  "<h1>" . l($scholar->group->title, $scholar->get_absolute_url()) . "</h1>".
  ((strlen($scholar->group->og_description)) ? "<h2>" . $scholar->group->og_description . "</h2>" : "" );

  $block['content'] = $output;
  return $block;
}

/**
 * Scholar Logo Widget Content
 * @return array
 */
function _scholar_project_logo_wdgt(){

  $block['subject'] = t(''); // intentionally blank

  $vsite = vsite_get_vsite();
  if($vsite && ($a_files = filefield_get_node_files($vsite->group,'field_project_logo')) && count($a_files)){
    $block['content'] = '<div id="logo"><a href="'.url("home").'">'.theme('vsite_logo',$vsite,'field_project_logo' ,false).'</a></div>';
  }//Only show content if an image exists

  return $block;
}

/**
 * Implementation of hook_form_alter()
 **/
function scholar_project_form_alter(&$form, $form_state, $form_id) {
  $scholar_content_type = variable_get('scholar_content_type', 'vsite');
  switch ($form_id) {
    case $scholar_content_type.'_node_form':
      //Customize the "Site Information" form
      if(arg(0) != 'cp') break;
      if(array_key_exists('title',$form)) $form['title']['#title'] = "Headline";
      if(array_key_exists('og_description',$form)){
      	$form['og_description']['#title'] = "Sub Headline";
      	$form['og_description']['#required'] = false;
      	$form['field_vsite_logo'][0]['#title'] = "Project Logo";
        $form['field_vsite_logo'][0]['#description'] = "Upload the logo of the project, if there is one. Note: Currently there is a set aspect-ratio to this image. First upload the image and then use the cropping tool to crop to the desired scaling.";
      }
      unset($form['body_field']['format']);
      _spaces_og_make_hidden($form['body_field']);
    break;
    default:

  }
}
