<?php

include_once('scholar_project.features.inc');

/**
 * hook strongarm
 */
function scholar_project_strongarm(){
  $conf = array();

  // User settings
  $conf['user_register'] = 0; // No registration is allowed; this is a closed group

  // this helps to show user the appropriate name for features
  // i.e. project_news
  $conf['openscholar_installation_mode'] = 'project';

  // the content type which powers this kind of web site.
  $conf['scholar_content_type'] = 'project';
  $conf['og_content_type_usage_project'] = 'group';

  // setting determines if a non admin user can create multiple sites
  $conf['scholar_create_multiple_sites'] = 1;

  // the default project site theme
  $conf['openscholar_vsite_default_theme'] = 'scholar_cayley';

  // list of themes, one will be randomly selected as default for new sites created
  $conf['openscholar_selected_themes'] = array( 'scholar_bunchy', 'scholar_cayley', 'scholar_nortony');

  $conf['spaces_default_presets'] = array(
    'og' => 'project'
  );

  $conf['spaces_disabled_presets'] = array(
    'og' => array(
      'private' => 1,
      'controlled' => 1,
      'public' => 1
    )
  );


  $conf['scholar_home_page_title'] = "IQSS Projects Access";

  $conf['scholar_default_preset'] = "project";

  // default theme
  //$conf['theme_default'] = 'scholar_projects_front';

  // site front page
  //$conf['site_frontpage'] = 'scholar_projects_home';

  // project node settings
  $conf['upload_project'] = FALSE;

  $conf["show_preview_changes_project"] = FALSE;
  $conf["show_diff_inline_project"] = FALSE;

  // Comments
  $conf['comment_project'] = COMMENT_NODE_DISABLED;
  return $conf;
}


function scholar_project_preprocess_page($vars){
  $vars['body_classes'] .= ' scholar-projects-distro';
}

/**
 * Define the project blocks with hook block
 */
function scholar_project_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Project site logo');
    $blocks[1]['info'] = t('Project site info');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        return _scholar_project_logo_wdgt();
      case 1:
       return _scholar_project_basicinfo_wdgt();
    }
  }
}

/**
 * Define the avalible vsite widgets
 * @return array
 */
function scholar_project_vsite_widgets(){

  return array(
    'scholar_project_0' => array(
      'module' => 'scholar_project',
      'delta' => '0',
      'weight' => 20,
      'region' => 'header_left',
      'status' => '0',
      'label' => 'Project Site Logo',
      'type' => 'context_ui',
    ),
    'scholar_project_1' => array(
      'module' => 'scholar_project',
      'delta' => '1',
      'weight' => 20,
      'region' => 'header_main',
      'status' => '0',
      'label' => 'Project site info',
      'type' => 'context_ui',
    ),
  );

}

/**
 * Scholar Basic Info Widget Content
 * @return array
 */
function _scholar_project_basicinfo_wdgt(){
  $scholar = vsite_get_vsite();

  $block = array();
  $block['subject'] = t('');
  $block['content'] = l('Project Site (' . $scholar->group->purl . ')', $scholar->get_absolute_url());

  if(!strlen($scholar->group->title)) return $block;

  $output =  "<h1>" . l($scholar->group->title, $scholar->get_absolute_url()) . "</h1>".
  ((strlen($scholar->group->og_description)) ? "<h2>" . $scholar->group->og_description . "</h2>" : "" );

  $block['content'] = $output;
  return $block;
}

/**
 * Scholar Logo Widget Content
 * @return array
 */
function _scholar_project_logo_wdgt(){

  $block['subject'] = t(''); // intentionally blank

  $vsite = vsite_get_vsite();
  if($vsite && ($a_files = filefield_get_node_files($vsite->group,'field_project_logo')) && count($a_files)){
    $block['content'] = '<div id="logo"><a href="'.url("home").'">'.theme('vsite_logo',$vsite,'field_project_logo' ,false).'</a></div>';
  }//Only show content if an image exists

  return $block;
}

/**
 * Implementation of hook_form_alter()
 **/
function scholar_project_form_alter(&$form, $form_state, $form_id) {
  $scholar_content_type = variable_get('scholar_content_type', 'vsite');
  switch ($form_id) {
    case $scholar_content_type.'_node_form':
      //Customize the "Site Information" form
      if(arg(0) != 'cp') break;
      if(array_key_exists('title',$form)) $form['title']['#title'] = "Headline";
      if(array_key_exists('og_description',$form)){
      	$form['og_description']['#title'] = "Sub Headline";
      	$form['og_description']['#required'] = false;
      	$form['field_vsite_logo'][0]['#title'] = "Project Logo";
        $form['field_vsite_logo'][0]['#description'] = "Upload the logo of the project, if there is one. Note: Currently there is a set aspect-ratio to this image. First upload the image and then use the cropping tool to crop to the desired scaling.";
      }
      unset($form['body_field']['format']);
      _spaces_og_make_hidden($form['body_field']);
    break;
    default:

  }
}
