<?php

include_once('scholar_presentations.features.inc');

/**
 * Implementation of hook_init().
 */
function scholar_presentations_init() {
  drupal_add_css(drupal_get_path('module', 'scholar_presentations') .'/theme/scholar_presentations.css');
}

/**
 * Implementation of hook_vsite_widgets()
 */
function scholar_presentations_vsite_widgets(){
  $items = array();
  $items['views-scholar_presentations-block_1'] = array(
        'module' => 'views',
        'delta' => 'scholar_presentations-block_1',
        'weight' => 10,
        'region' => false,
        'label' => 'Recent Presentations',
        'cache' => BLOCK_CACHE_CONTENT_CACHE,
		    'cache_keys' => array(
		      'node' => array('presentation' => 'presentation'),
		      'os_og' => array('current' => 'current'),
		    ),
      );

      return $items;
}
