<?php

include_once('vsite_widgets.features.inc');

/**
 * hook block
 */
function vsite_widgets_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Scholar site shield');
    $blocks[1]['info'] = t('Scholar site search');
    $blocks[2]['info'] = t('ShareThis Button - Allows you to share posts using popular online services');
    $blocks[3]['info'] = t('Google Translate');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
       return vsite_widgets_shield();
      case 1:
       return vsite_widgets_search();
      case 2:
      	return vsite_widgets_addthis();
      case 3:
      	return vsite_widget_googletranslate();
    }
  }
}

function vsite_widgets_search(){
  if (! module_exists('search') || ! user_access('search content')) {
    return;
  }

  $block['content'] = drupal_get_form('vsite_widgets_search_form');
  //$block['subject'] = "Search";
  return $block;

}

/**
 * Search form.
 */
function vsite_widgets_search_form($form_state) {
  if (arg(0) == 'sitesearch' && isset($_GET['keys'])) {
    $default = urldecode($_GET['keys']);
  }
  $search =
  $form = array();

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('vsite_widgets_search_form_submit'),
    //'#attributes' => array('class' => 'some-other-class'),
  );

  $form['search'] = array(
    '#type' => 'textfield',
    '#size' => 'auto',
    '#required' => true,
    '#default_value' => !empty($default) ? $default : '',
    //'#attributes' => array('class' => 'some-class'),
  );

  return $form;
}

/**
 * Search form submit handler.
 */
function vsite_widgets_search_form_submit($form, &$form_state) {
  $search = $form_state['values']['search'];
  drupal_goto('sitesearch', array('keys' => $search));
}

/**
 * Adds the addthis social networking link
 * @return array
 */
function vsite_widgets_addthis(){
  if (! module_exists('addthis') || ! user_access('view addthis')) {
    return;
  }
  
  if(!function_exists('_addthis_create_button')){
  	error_log("Unable to find addthis function Line:".__LINE__." File:".__FILE__);
  	return;
  }
  
  //For now we will just show this on node pages this may be customizable in the future
  $active_node = menu_get_object('node');
  if(!is_object($active_node)) return;
  
  $block['subject'] = t(''); //t('AddThis');
  $block['content'] = _addthis_create_button($active_node);
  return $block;

}

/**
 * A widget to allow translation of a page
 * @return array
 */
function vsite_widget_googletranslate(){
  global $language;
	$lang = ($language->language)?$language->language:'en';
	
	$block['subject'] = t(''); //Blank
  $block['content'] = '<div id="google_translate_element"></div><script>
												function googleTranslateElementInit() {
												  new google.translate.TranslateElement({
												    pageLanguage: \''.$lang.'\'
												  }, \'google_translate_element\');
												}
												</script><script src="http://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>';
  return $block;
	
}

function vsite_widgets_shield(){
  	$scholar = vsite_get_vsite();
	$output = '';
	if(array_key_exists('generic',$scholar->settings) && array_key_exists('disable_shield',$scholar->settings['generic']) && $scholar->settings['generic']['disable_shield']){
		return $output;
	}//Disabled?

	if(array_key_exists('generic',$scholar->settings) && array_key_exists('shield',$scholar->settings['generic'])){
		$s_filename = array_pop(explode('/',$scholar->settings['generic']['shield']));
		$output = '<div id="scholar-shield"><img src="/'.drupal_get_path('module','vsite_design')."/theme/shield/shields/".$s_filename.'" /> </div>';
	}

	$block['subject'] = t('');
	$block['content'] = $output;

	return $block;
}

function vsite_widgets_vsite_widgets(){

	return array(
  
    'vsite_widgets_2' => array(
      'module' => 'vsite_widgets',
      'delta' => '0',
      'weight' => 20,
      'region' => 'header_right',
      'status' => '0',
      'label' => 'Scholar site shield',
      'type' => 'context_ui',
    ),

   'vsite_widgets_3' => array(
      'module' => 'vsite_widgets',
      'delta' => '1',
      'weight' => -5,
      'region' => 'right',
      'status' => '0',
      'label' => 'Scholar search widget',
      'type' => 'context_ui',
    ),
    
//    'vsite_widgets_4' => array(
//      'module' => 'vsite_widgets',
//      'delta' => '1',
//      'weight' => 2,
//      'region' => 'right',
//      'status' => '0',
//      'label' => 'Add This Widget',
//      'type' => 'context_ui',
//    ),
    
    'vsite_widgets_5' => array(
      'module' => 'vsite_widgets',
      'delta' => '3',
      'weight' => 40,
      'region' => false,
      'status' => '0',
      'label' => 'Google Translate',
      'type' => 'context_ui',
    ),


    // Featured posts
    'views_vsite_featuredposts-block_1' => array(
      'module' => 'views',
      'delta' => 'vsite_featuredposts-block_1',
      'weight' => 0,
      'region' => false,
      'status' => '0',
      'label' => 'Featured posts',
      'type' => 'context_ui',
    ),
  );

}

/**
 * hook context_default_contexts
 * @return unknown_type
 */
function vsite_widgets_context_default_contexts() {
  $items = array ();
 
  $items [] = array (
      'namespace' => 'vsite',
      'attribute' => 'section',
      'value' => 'cp',
      'description' => 'Active when you are in the CP section of a vsite',
      'block' => array(),
   );
   $items [] = array (
      'namespace' => 'vsite',
      'attribute' => 'section',
      'value' => 'public',
      'description' => 'Active when you are in the public section of a vsite',
      'block' => module_invoke_all('vsite_widgets'),
   );

  return $items;
}


/**
 * Implementation of hook flag_default_flags
 * @return array - default flag
 */
function vsite_widgets_flag_alter(&$flag){
  if (!($viste = vsite_get_vsite()) || $flag -> name !== 'featuredposts'){
    return;
  }
  vsite_include('vsiteapi');

  $types = vsite_content_types();

  if (count($types)){
    $flag -> types = array_keys($types);
  }
}

/**
 * Implementation of hook_link().
 */
function vsite_widgets_vsite_admin_link($type, $object){
  $links = array();
  global $user;
  //check font page settings here, only execute if front page setting equals flag
  if(!($vsite = vsite_get_vsite()) || !is_object($vsite)){
    return $links;
  }

  if (//$vsite->settings['front']['frontpage'] !== 'flag' ||
      !($vsite->admin_access()) ||
      !flag_fetch_definition($type)){
    return $links;
  }

  // Get frontpage flags
  $flag = flag_get_flag('featuredposts');


  if (!$flag->applies_to_content_object($object)) {
    // Flag does not apply to this content.
    return false;
  }

  $content_id = $flag->get_content_id($object);
  // The flag links are actually fully rendered theme functions.
  // The HTML attribute is set to TRUE to allow whatever the themer desires.
  $links['flag-'. $flag->name] = array(
  'title' => $flag->theme($flag->is_flagged($content_id) ? 'unflag' : 'flag', $content_id),
  'html' => TRUE,
  );

  if (isset($links)) {
    return $links;
  }
}
