<?php

include_once('scholar_biocv.features.inc');

function scholar_biocv_menu(){
  $items = array();
  $items['bio'] = array(
    'title' => 'Bio',
    'page callback' => 'scholar_biocv_bio',
    'access callback' => 'spaces_feature_access',
    'access arguments' => array('scholar_biocv'), 
    'menu_name' => 'features',
  );
  
  return $items;
}

function scholar_biocv_bio(){
  $vsite = vsite_get_vsite();
  // load the bio node for the owner of this vsite
  // TODO probably an api function for getting the site owner
  $bio_node = content_profile_load('bio', $vsite -> group -> uid, $lang = '');
  if ($bio_node){
     return node_view($bio_node);
  }
  else {
    // an appropriate message and a link for the user to create their bio
    return l('ddd', 'node/1');
  }
}

function scholar_biocv_strongarm(){
  $conf = array();
  $conf['content_profile_use_bio'] = 1;
  $conf['content_profile_bio'] = array(
    'weight' => 0, 
    'user_display' => 'full', 
    'edit_link' => 0, 
    'edit_tab' => 0, 
    'add_link' => 0, 
    'registration_use' => 0, 
    'admin_user_create_use' => 0, 
    'registration_hide' => array(
      'other' 
    ) 
  );
  
  $conf['content_profile_use_cv'] = 1;
  $conf['content_profile_cv'] = array(
    'weight' => 0, 
    'user_display' => 'full', 
    'edit_link' => 0, 
    'edit_tab' => 0, 
    'add_link' => 0, 
    'registration_use' => 0, 
    'admin_user_create_use' => 0, 
    'registration_hide' => array(
      'other' 
    ) 
  );
  return $conf;
}

/**
 * Edit cv form to add checkbox for toggle
 */
function scholar_biocv_form_alter(&$form, $form_state, $form_id) {
  switch($form_id){
    case 'cv_node_form':
    	drupal_add_js(drupal_get_path('module', 'scholar_biocv') . '/theme/scholar_biocv.biocvToggleUsePDF.js');
    	$a_biocv_settings['biocvToggleUsePDF'] = array(
        'monitor' => "use_pdf_as_cv",
    	  'toggleOff' => array('title','body'),
      );
      drupal_add_js($a_biocv_settings, 'setting');
      
    	$form['use_pdf_as_cv'] = array(
			  '#type' => 'checkbox',
    	  '#weight' => -10,
			  '#title' => t('Use PDF upload as your CV'),
       	'#description' => t('When this is checked the pdf you upload will be displayed on the cv section of your site.'),
			);
    	
      $form['#submit'][] = 'scholar_biocv_cv_node_submit';
    break;
  }
}

/**
 * Save the setting that decides if they will be using thier PDF as thier CV
 * @param $form
 * @param $form_state
 */
function scholar_biocv_cv_node_submit($form, &$form_state) {
	
	
}
