<?php
// $Id: activityhistory.module,v 1.2 2008/05/06 14:32:49 sirkitree Exp $

function activityhistory_activityapi(&$activity, $op) {
  global $user;
  static $history = array();

  switch ($op) {
    case 'load':
      if (!isset($history[$activity['aid']][$user->uid])) {
        $new = db_result(db_query('SELECT ah.timestamp FROM {activity_history} ah WHERE aid = %d AND uid = %d', $activity['aid'], $user->uid));
        if (empty($new)) {
           $history[$activity['aid']][$user->uid] = theme('mark', MARK_NEW, 'activityhistory');
           // update to show that it has been seen
           @db_query('INSERT INTO {activity_history} (uid, aid, timestamp) VALUES (%d, %d, %d)', $user->uid, $activity['aid'], time());
        }
        else {
          $history[$activity['aid']][$user->uid] = '';
        }
      }
      $activity['activity_history_new'] = $history[$activity['aid']][$user->uid];
      break;
  }
}

if (!function_exists('phptemplate_activity')) {
  function phptemplate_activity($message, $item) {
    return $item['activity_history_new'] .' <span class="activity">'. $message .'</span>';
  }
}
