<?php

// $Id$

/**
 * @file
 *   Provides setup and configuration of common search widgets depending upon the currently installed search solution.  Supported options are
 *   Apache Solr and Search Lucene API.
 */

define('VSITE_SEARCH_SOLR', module_exists('apachesolr'));
define('VSITE_SEARCH_LUCENE', module_exists('luceneapi'));

/**
 * Implementation of hook_init()
 * 
 * Includes files that are specific to the currently enabled search solution.
 */
function vsite_search_init() {
	if(VSITE_SEARCH_SOLR) {
		require_once(drupal_get_path('module', 'vsite_search').'/apache_solr.inc');
	}
	
	if(VSITE_SEARCH_LUCENE) {
		require_once(drupal-get_path('module', 'vsite_search').'/luceneapi.inc');
	}
}

/**
 * Implementation of hook_block()
 * 
 * @param string $op
 * @param int $delta
 * @param mixed $edit
 */
function vsite_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
    	$blocks = array();
    	if(VSITE_SEARCH_SOLR) {
    		// Retrieve all of the facets defined by hook_facet()
    		$defined_facets = apachesolr_get_facet_definitions();
    		// Loop through the enabled facets, and create a block based on each facet.  This is so that these blocks can be displayed in any region and at any time.
    		foreach(apachesolr_get_enabled_facets() as $module => $facets) {
    			if(!empty($facets)) {
    				foreach($facets as $delta => $facet_name) {
              $blocks[]['info'] = $defined_facets[$module][$delta]['info'];
    				}
    			}
    		}
    	}
      return $blocks;
    case 'view':
    	if(VSITE_SEARCH_SOLR) {
    		/**
    		 * Get the enabled filter facet blocks, performing an empty search based on the content type as a filter.
    		 * @see http://drupal.org/node/457826
    		 */ 
	    	$blocks = apachesolr_search_browse(null, null, null, 'search/apachesolr_search');
	    	return array(
	    	  'subject' => $blocks[$delta]->subject,
	    	  'content' => $blocks[$delta]->content,
	    	);
    	}
  }
}

/**
 * Implementation of hook_vsite_widgets()
 * 
 * @return
 *   Associative array representing a widget
 */
function vsite_search_vsite_widgets(){
  $widgets = array();
  /**
   * Define a series of widgets for Search Lucene support, if the module is enabled
   */
  if(VSITE_SEARCH_LUCENE) {
    $widgets['luceneapi_facet'] = array(
      'module' => 'luceneapi_facet',
      'delta' => 'luceneapi_node',
      'weight' => 0,
      'region' => false,
      'status' => '0',
      'label' => t('Search Lucene Facets'),
      'type' => 'context_ui',
    );
  }
  
  /**
   * Define a series of widgets for Apache Solr support, if the module is enabled
   */
  if(VSITE_SEARCH_SOLR) {
  	$response = apachesolr_static_response_cache();
    if (empty($response)) {
      return;
    }
    $query = apachesolr_current_query();
    $block = apachesolr_facet_block($response, $query, 'apachesolr_og', $delta, $delta, t('Filter by Group'), 'apachesolr_og_group_name');
  	
  	$widgets['apachesolr_facet'] = array(
  	  'module' => 'apachesolr',
  	  'delta' => '0',
  	  'weight' => 0,
  	  'region' => 'right',
  	  'status' => '0',
  	  'label' => t('Apache Solr Facets'),
  	  'type' => 'context_ui',
  	);
  }  
  return $widgets;
}

/**
 * hook context_default_contexts
 * @return unknown_type
 */
function vsite_search_context_default_contexts() {
  $items = array ();
  
  /**
   * Define Search Lucene-specific contexts
   */
  if(VSITE_SEARCH_LUCENE) {
  	$items[] = array(
		  'namespace' => 'vsite',
		  'attribute' => 'search',
		  'value' => 'luceneapi_announcement_nodes',
		  'description' => 'Shows the LuceneAPI facets block depending on the node type',
		  'node' => array(
		    '0' => 'announcement',
		  ),
		  'block' => array(
		    'luceneapi_facet_luceneapi_node' => array(
		      'module' => 'luceneapi_facet',
		      'delta' => 'luceneapi_node',
		      'weight' => 0,
		      'region' => 'right',
		      'status' => '0',
		      'label' => 'Search Lucene Facets: Search Lucene',
		      'type' => 'context_ui',
		    ),
		  ),
		);
		$items[] = array(
		  'namespace' => 'vsite',
		  'attribute' => 'search',
		  'value' => 'luceneapi_announcement_views',
		  'description' => 'Shows the LuceneAPI facets block depending on the node type',
		  'views' => array(
		    '0' => 'scholar_announcements',
		  ),
		  'block' => array(
		    'luceneapi_facet_luceneapi_node' => array(
		      'module' => 'luceneapi_facet',
		      'delta' => 'luceneapi_node',
		      'weight' => 0,
		      'region' => 'right',
		      'status' => '0',
		      'label' => 'Search Lucene Facets: Search Lucene',
		      'type' => 'context_ui',
		    ),
		  ),
		);
  }
  
  /**
   * Define Apache Solr-specific contexts
   */
  if(VSITE_SEARCH_SOLR) {
  	$items[] = array(
	    'namespace' => 'vsite',
	    'attribute' => 'search',
	    'value' => 'apachesolr_search',
	    'system' => 0,
	    'description' => 'Context for searches performed through Apache Solr',
	    'path' => array(
	      'search/apachesolr_search' => 'search/apachesolr_search',
	      'search/apachesolr_search/*' => 'search/apachesolr_search/*',
	    ),
	    'block' => array(
	      // Cast as an object instead of using stdClass::__set_state() - http://drupal.org/node/584672
	      'apachesolr_mlt-001' => (object)(array(
	         'module' => 'apachesolr',
	         'delta' => 'mlt-001',
	         'weight' => 20,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr recommendations: More like this',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_mlt-001',
	      )),
	      'apachesolr_sort' => (object)(array(
	         'module' => 'apachesolr',
	         'delta' => 'sort',
	         'weight' => 21,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Core: Sorting',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_sort',
	      )),
	      'apachesolr_search_changed' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'changed',
	         'weight' => 22,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by updated date',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_changed',
	      )),
	      'apachesolr_search_currentsearch' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'currentsearch',
	         'weight' => 23,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Current search',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_currentsearch',
	      )),
	      'apachesolr_search_im_vid_1' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_1',
	         'weight' => 24,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy Scholar Taxonomy',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_1',
	      )),
	      'apachesolr_search_im_vid_2' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_2',
	         'weight' => 25,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy Sites Affiliation / Department',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_2',
	      )),
	      'apachesolr_search_im_vid_3' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_3',
	         'weight' => 26,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy Related Interests',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_3',
	      )),
	      'apachesolr_search_im_vid_4' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_4',
	         'weight' => 27,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy _vocabulary',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_4',
	      )),
	      'apachesolr_search_im_vid_5' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_5',
	         'weight' => 28,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy _vocabulary',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_5',
	      )),
	      'apachesolr_search_im_vid_6' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'im_vid_6',
	         'weight' => 29,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by taxonomy _vocabulary',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_im_vid_6',
	      )),
	      'apachesolr_search_type' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'type',
	         'weight' => 30,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by content type',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_type',
	      )),
	      'apachesolr_search_uid' => (object)(array(
	         'module' => 'apachesolr_search',
	         'delta' => 'uid',
	         'weight' => 31,
	         'region' => 'right',
	         'status' => '0',
	         'label' => 'Apache Solr Search: Filter by author',
	         'type' => 'context_ui',
	         'bid' => 'apachesolr_search_uid',
	      )),
	    ),
	    'type' => 2,
	    'status' => 1,
	  );
  }
  return $items;
}