<?php

/**
 * Implementation of hook_menu()
 */
function simport_menu() { 

  $items['admin/settings/simport'] = array(
    'title' => 'Simport',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simport_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'description' => 'Simport Settings',
    'file path' => drupal_get_path('module', 'simport') . '/includes',
    'file' => 'simport.admin.inc',
  );

  return $items;
}

/**
 * Batch Process iniitiation
 */
function simport_import(){

  $batch = array('operations' => array(),
  'finished' => 'simport_completed',
  'title' => t('Simport'),
  'init_message' => t('Initializing Import Process'),
  'progress_message' => t('Completed @current out of @total processes'),
  'error_message' => t('An error occurred'),
  );

  // Add an array declaring the callback function for your
  // batch process and an array of callback arguments
  $batch['operations'][] = array('simport_import_sites', array());
  $batch['operations'][] = array('simport_import_types', array(0)); //all non-biblio nodes
  $batch['operations'][] = array('simport_import_types', array(1)); //biblio nodes
  $batch['operations'][] = array('simport_import_logo', array());
  $batch['operations'][] = array('simport_import_frontpage', array());
  $batch['operations'][] = array('simport_get_files', array());
  $batch['operations'][] = array('simport_sync_themes', array());
  $batch['operations'][] = array('simport_set_menu_links', array());
  $batch['operations'][] = array('simport_cleanup', array());
  // add whatever logic you need
  //$batch['operations'][] = array('another_batch_function', array($arg1, $arg2));

  if (!empty($batch['operations'])) {
    batch_set($batch);
    // batch_process() only needed if not inside a form _submit handler :
    batch_process();
  }
}

function simport_completed($success, $results, $operations){
$message = ($success) ? 'Import Process Completed' : 'Errors Durring Import Process';
drupal_set_message($message);
drupal_goto('admin');
}

/**
 * Initial function to begin import script
 * @return unknown
 */
function simport_import_sites(&$context){ 
  $context['message'] = 'Created Scholar Users and Sites';

    //import the table with serialized D5 scholars site data
  if(db_table_exists('scholar_export_data')){
    db_drop_table(&$ret, 'scholar_export_data');       
    }
    _simport_exportdata();

  //setting a few path related system vars
  variable_set('simport_current_path', _simport_get_fileroot());
 // variable_set('simport_remote_path', '/nfs/www/edu-harvard-iq-test2');
  variable_set('simport_remote_path', '/nfs/www/edu-harvard-iq-scholar');  
  variable_set('file_directory_path', conf_path() .'/files');

  //PHASE 1 - Load the VSITE And Settings
 $testing = db_query("TRUNCATE TABLE {simport}"); //empty the table each time
 
  vsite_include('vsiteapi');
  $roles = variable_get('scholar_manager_role', 'scholar admin');

  //test one node
 // $sql = db_query("SELECT * FROM {scholar_export_data} WHERE id = %d AND type = '%s'", 136, 'admin_scholar');
  
  //first create the new vsites
  $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s'", 'admin_scholar');
  while ($data = db_fetch_object($sql)) {

    //get the old site node object
    $old = unserialize($data ->data); 
   
    //define the domain for the new site
    $domain = $old -> title;

    //get old user object
    $user_old = unserialize(db_result(db_query("SELECT data from {scholar_export_data} WHERE type = '%s' AND id = %d", 'user', (int)$old ->uid)));

    //create new user based on the old user info
    $user = simport_create_user($user_old->name, $user_old->mail, $user_old->pass, $roles);

    //create new site
    $new_site_info = simport_create_site($user, $domain);

    //write to the simport table mapping old site to new site
    $sql_map_sites = db_query("INSERT INTO {simport} (old, new) VALUES (%d, %d)", (int)$old -> nid, (int)$new_site_info ->nid);

    if($new){
      unset($new);
    }
    
    //get a spaces object for new site so we can modify and save with the functions below
    $new = spaces_load ( 'og', $new_site_info ->nid, TRUE );
    
    //set theme
    simport_set_theme($old, $new);

    //set shield
    simport_set_shield($old, $new);
    
    //turn on some features
    $new->features['scholar_links'] = 2;
    $new->features['scholar_pages'] = 2;
    $new->features['scholar_announcements'] = 2;    

    //save all the changes/additions to the space
    spaces_save($new);
    
    //define position to be set as og_description
    $position = isset($old -> scholar_position) ? $old -> scholar_position : 'Scholar';
    //define site title - firstname lastname (if not set just user the username)
    $site_title = (isset($old -> scholar_firstname) && isset($old -> scholar_lastname)) ? 
    $old -> scholar_firstname . ' ' . $old -> scholar_lastname : $new -> group -> name;
    //update og_description in db
    db_query("UPDATE {og} SET og_description = '%s' WHERE nid = %d", $position, (int) $new ->sid);
    //Update site name to new site name convention
    db_query("UPDATE {node} SET title = '%s' WHERE nid = %d", $site_title, (int) $new ->sid);
    db_query("UPDATE {node_revisions} SET title = '%s' WHERE nid = %d", $site_title, (int) $new ->sid);
  }
}
  //PHASE 2 - Load And Save The Content
function simport_import_types($biblio = 0, &$context){

  if ($biblio == 1){
    $context['message'] =  'Created Biblio Content';
    //define content type(s)
    $types = array('biblio' => 'biblio');

    //create custom biblio type - Working Paper
    $working_paper = simport_create_biblio_type;
  }
  else{
    $context['message'] =  'Created Non-Biblio Scholar Content';
    //define content type(s)
    $types = _simport_map_content_types();
  }
  
  foreach ($types as $oldtype => $newtype){
   $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s'", $oldtype);
 // $sql = db_query("SELECT * FROM {scholar_export_data} WHERE  id = %d", 24);
    while ($data = db_fetch_object($sql)) {
      $old = unserialize($data ->data);
      $new = new stdClass();
       
      //set generic values
      simport_set_generic($old, $new);     

      //set taxonomy term values
       simport_set_terms($old, $new);

      //deal with any custom fields specific to the content type;
      switch ($old -> type){

        case 'scholar_announcement':
          simport_set_announcement($old, $new);
          break;

        case 'scholar_bio':
          simport_set_page($old, $new); //import to page
          break;
          
        case 'biblio':          
           simport_set_biblio($old, $new);           
          break;   

        case 'scholar_page':
          simport_set_page($old, $new); //import to page also
          break;

        case 'scholar_blog':
          //no blogs to import
          break;

        case 'scholar_link':
          simport_set_link($old, $new);
          break;

        case 'scholar_class':
          simport_set_class($old, $new);
          break;
       }
  
      //save the node
      node_save($new);
                
      //I've found that this way works the best (instead of db_last_insert_id or node_load)      
      $last = db_result(db_query("SELECT MAX(nid) FROM {node}"));
      
      //insert new and old node ids into simport table 
     db_query("INSERT INTO {simport} (old, new) VALUES (%d, %d)", (int)$old -> nid, (int)$last);
    }    
  }
}

function simport_import_logo(&$content){
  $context['message'] = 'Retrieved logos';
  //PHASE 3 - Set The logo
  //$sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s' AND id = %d", 'scholar_photo', 4);
  $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s'", 'scholar_photo');
  while($data = db_fetch_object($sql)){
    $old = unserialize($data -> data);
    if($old -> field_photo[0]['fid'] > 0){
      simport_set_logo($old);
    }
  }
}
  
  //PHASE 4 - Set The Front Page
  //loop thorugh all the admin_scholar types now that all nodes have been imported
  
  function simport_import_frontpage(){

    $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s'", 'admin_scholar');
    while($data = db_fetch_object($sql)){

      //get the old site node object
      $old = unserialize($data ->data);

      if ($old->scholar_admin_site_front_node){
        //load the new vsite
        $vsite = simport_get_new_vsite($old -> nid);

        //lget the new frontpage nid
        $new_front_nid =  simport_get_new_nid($old->scholar_admin_site_front_node);

        //set frontpage value after content created
        simport_set_frontpage($old, $vsite, $new_front_nid, $old->scholar_admin_site_front_node);

        //save the vsite settings for front page
        spaces_save($vsite);
      }
    }
  }

/**
 * Create the user
 */
function simport_create_user($name, $mail, $password_hash, $roles){
  install_include(array( 'user' ));
  $password =  user_password();
  $user = install_add_user($name, $password, $mail, $roles = array($roles), $status = 1);

  if (!$user){
    //TODO: add watchdog message
    //watchdog();
  }

  else{
    //change the password back to the original
    $sql_revert_password = db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", $password_hash, (int)$user ->uid);
  }
  //return the new user object
  return $user;
}

/**
 * Create the site
 */
function simport_create_site($user, $domain){
  vsite_include('vsiteapi');
  //create the site
  return vsite_vsite_create($user->name, $user->mail, $domain);
}

/**
 * 
 * @param $old og node from the old site
 * @param $new the new vsite
 */
function simport_set_theme($old, &$new){

  $og_theme_map = array(
  'fac01' => 'scholar_theme_06',
  'fac02' => 'scholar_theme_01',
  'fac03' =>'scholar_theme_03',
  'fac04' => 'scholar_theme_06',
  'fac05' => 'scholar_theme_05',
  'fac06' => 'scholar_theme_04',
  'fac07' => 'scholar_theme_07',
  );
  //set the new theme
  $new->settings['theme'] = $og_theme_map[$old -> og_theme];
  
  //TODO: need to make change here
   $new-> og_theme = $og_theme_map[$old -> og_theme];
}

/**
 * Set the frontpage value
 *
 * @param unknown_type $old
 * @param unknown_type $new
 */
function simport_set_frontpage($old, &$vsite, $new_front_nid, $old_front_nid){ 
  //get the old frontpage node
  $old_frontpage = simport_get_old_node($old_front_nid);
  //set frontpage to bio page
  if ( $old_frontpage  -> type == 'scholar_bio'){
  $vsite->settings['bio']['nid'] = $new_front_nid; 
  $vsite->settings['front']['frontpage']= 'bio'; 
  }
  else{
  //set the front page to an individual node
  $vsite->settings['front']['frontpage']= 'html'; 
  $vsite->settings['front']['front_nid'] = $new_front_nid;  
  //  not using this function anymore -  _simport_map_content_types($old_frontpage  -> type);
  }
}

/**
 * Transfer the logo
 *
 * @param unknown_type $old
 * @param unknown_type $new
 */
function simport_set_logo($old){
  $path = drupal_get_path('module', 'vsite_design') . '/includes/vsite_design.settings.logo.inc' ;
  include_once($path);
  
  //get the corresponding vsite
  $vsite = simport_get_new_vsite($old -> og_groups[0]);
  
  //not sure if this is nessary, should always be true
    $file = $old -> field_photo[0];
    
    if ($file['filepath']){
    //define source and destination directories
    $source = variable_get('simport_remote_path', '') . '/' .  $file['filepath']; 
    }
    
    else{
      //no filepath defined means this will not work, so return
      watchdog('simport', 'logo filepath not present %filename.', array('%filename' => basename($source)), WATCHDOG_NOTICE);
      return;
    }    
    
    if (file_exists($source)){        
      
      $tmp_path = '/tmp/' . basename($source);
      
      //delete temp file if exists
      if(file_exists($tmp_path)){
      file_delete($tmp_path);
      }

      //copy to temp dir
     file_copy($source, '/tmp');   
    
    $file = new stdClass();
    $file -> uid = $vsite-> group -> uid;
    $file -> filename = basename($tmp_path);
    $file -> filepath = $tmp_path;
    $file -> filemime = file_get_mimetype($source);
    $file -> filesize = filesize($source);
    $file -> status =1;
    $file -> timestamp = filemtime($source);
    
    //write to the files table
    drupal_write_record('files', $file);
      
    //copy the file to the new location
    //file_copy($source, $dest);
    
    //NOW DEAL WITH CP LOGO
     $dest = variable_get('simport_current_path', '') . '/' . variable_get('file_directory_path', '') . '/vsite_design_logo/' . $vsite ->purl;
    
        //create directory  
      file_check_directory($dest, $mode = 1, $form_item = NULL);
     
    //replacing the file name but keeping file ext
    $filename = explode('.', basename($source)); 
    $new_filename = $vsite ->purl . '.' . $filename[1];
    
    //if(!file_exists($dest . '/' . $new_filename)){
    //copy file to vsite_design_logo dir
    file_copy($source, $dest . '/' . $new_filename, $replace = FILE_EXISTS_REPLACE);
    //}
      
    //add file to og node
    vsite_design_settings_logo::add_imagefield_image($dest . '/' . $new_filename, 'field_vsite_logo',$vsite->group);
    
    
    //define new path for logo
    $new_path = variable_get('file_directory_path', '') . '/vsite_design_logo/' . $vsite ->purl . '/' . $new_filename; 
    
    //now set in the vsite settings
    $vsite ->settings['logo']['current_logo'] = $new_path;
    //save the vsite settings
    spaces_save($vsite);
    }
    else{
      //watchdog('simport', 'logo file does not exist in source location:  %filename.', array('%filename' => basename($source)), WATCHDOG_NOTICE);
    }
    return;
}

/**
 * Set the shield selection
 *
 * @param unknown_type $old
 * @param unknown_type $new
 */
function simport_set_shield($old, &$new){
  //all D5 site themes use the same shield - TODO: maybe not shepsle and bates sites???
  //shield setting now offered on old site, so set sheild to default
  $new ->settings['sheild'] = drupal_get_path('module','vsite_design')."/theme/shields/harvard_shield.png";
}

/**
 * Import the terms to the proper vocabulary and set them in the node object
 *
 * @param unknown_type $old
 * @param unknown_type $new
 */
function simport_set_terms($old, &$new){
  vsite_include('vsiteapi');
  //include_once(dirname(__FILE__) . '/simport.api.inc');

  //check to see of any terms are set in old node
  if (count($old -> tags)){
    $vsite = simport_get_new_vsite($old -> og_groups[0]);

    foreach($old -> tags as $vocab_id => $values){
      //NOTE: vocab id 6 is the global vocabularyon the D5 scholars site
      if ($vocab_id !== 6){
        foreach($values as $old_term){
          //get vocab(s) for the vsite
          $vocab_list = vsite_get_vocabs($vsite, $new -> type);

          foreach($vocab_list as $vocab){                      
            //check to see if terms already exists
            $tid = simport_import_term_exists($old_term->name, $vocab->vid);
                    
            //term already exists
            if ($tid){
              //add term id to node object
              $new -> taxonomy[$tid] = taxonomy_get_term($tid);
              return;
            }
              
            if (!$tid){
              //if term does not exist within vocab, then add it
              $term['vid'] = $vocab -> vid;
              $term['name'] = $old_term -> name;
              $term['description'] = empty($old_term -> description) ? NULL : $old_term -> description;
              //$term['weight'] = mt_rand(0,10);

              $status = taxonomy_save_term($term); 

              //get the newly created term id. TODO: is this the best way???           
             $tid = db_result(db_query("SELECT MAX(tid) FROM {term_data}"));
//print $tid; die;
              //now add the terms to the $new node object
              $new -> taxonomy[$tid] = taxonomy_get_term($tid);
            }
          }
        }
      }
    }
  }
}

/**
 * Pass it the old site nid and it returns current vsite object
 */
function simport_get_new_vsite($old_site_nid){
  $space_new = db_result(db_query("SELECT new FROM {simport} WHERE old = %d", $old_site_nid));
  $vsite = spaces_load ( 'og', $space_new, TRUE );
  return $vsite;
}


/**
 * Pass it the old nid and it returns current nid
 */
function simport_get_new_nid($old_nid){
  return db_result(db_query("SELECT new FROM {simport} WHERE old = %d", (int)$old_nid));
}

/**
 * Returns old NODE information
 *
 * @param unknown_type $nid
 * @return unknown
 */
function simport_get_old_node($nid){
  $data = db_result(db_query("SELECT data FROM {scholar_export_data} WHERE id  = %d AND type != '%s'", (int)$nid, 'user'));
  return unserialize($data);
}

/**
 * Returns old USER information
 *
 * @param unknown_type $nid
 * @return unknown
 */
function simport_get_old_user($uid){
  $data = db_result(db_query("SELECT data FROM {scholar_export_data} WHERE id  = %d AND type = '%s'", (int)$uid, 'user'));
  return unserialize($data);
}


function simport_set_generic($old, &$new){

 $vsite = simport_get_new_vsite($old -> og_groups[0]);

  //set the generic node data
  $new -> title = $old -> title;
  $new -> type = _simport_map_content_types($old -> type);
  $new -> status = $old -> status;
  $new -> created = $old -> created;
  $new -> changed = $old -> changed;
  $new->promote = $old ->promote;
  $new->sticky = $old ->sticky;
  $new->format = isset($old ->format)? $old ->format : 0; // Filtered HTML . check d5
  $new->language = 'en';
  $new -> uid = $vsite -> group -> uid;
  $new -> name = $vsite -> group -> name;
  
  $new -> og_public =1;
  $new -> og_initial_groups = array($vsite->sid => (int)$vsite->sid);
  $new -> og_groups[0] = (int)$vsite->sid;
  $new -> og_nodeapi = '';
  $new -> spaces_og = array('gid' =>  (int)$vsite->sid);
  
  
  //$new -> og_groups[$vsite -> group -> nid] = $vsite -> group -> nid; //double check on this
  //$new -> og_groups_both[$vsite -> group -> nid] = $vsite -> title;
}

function simport_set_announcement($old, &$new){  
  //no custom fields
  $new -> body = $old -> body;
}

function simport_set_page($old, &$new){  
  //no custom fields
  $new -> body = $old -> body;
}

function simport_set_class($old, &$new){ 
  
   $new -> body = $old -> body;
  
  //TODO: These 3 fields do NOT EXIST YET. Change them accordinly once they are created.
  //set year
  if(!empty($old ->field_scholar_year[0]['value'])){
    $new -> field_class_year[0]['value'] = $old ->field_scholar_year[0]['value'];
  }

  //set semester
  if(!empty($old ->field_scholar_semester[0]['value'])){
    $new -> field_class_semester[0]['value'] = $old ->field_scholar_semester[0]['value'];
  }
}

function simport_set_link($old, &$new){ 
  //set the link
  if (!empty($old -> field_link[0]['url'])){
    $new -> field_link_href[0]['url'] = $old -> field_link[0]['url'];
  }  
}

/**
 * Import biblio nodes
 *
 * @param unknown_type $old
 * @param unknown_type $new
 */
function simport_set_biblio($old, &$new){

  //a list of D5 biblio author fields
  $author_fields = array(
  'biblio_authors', 
  'biblio_secondary_authors', 
  'biblio_tertiary_authors', 
  'biblio_corp_author', 
  'biblio_other_author_affiliations'
  );

   //set to contributors to empty array to begin
   $new -> biblio_contributors = array();
  
  //convert old node to array
  $properties = get_object_vars($old);
  foreach($properties as $key => $val){

    //clear $matches for next loop because it is passed by reference
    if(isset($matches)){
      unset($matches);
    }
    //check if biblio field
    if (count(preg_match( '/^biblio_/', $key, $matches))){
      if (!in_array($key, $author_fields)){
        //not an author field, so set the property verbatim
        $new -> $key = $val;
      }

      else{
         //deal with author fields      
     
           
      switch($key){
        case 'biblio_authors':
          if(!empty($val)){
            $new -> biblio_contributors =  simport_create_biblio_authors($val, 1);
          }
        break;

        case 'biblio_secondary_authors':
          if(!empty($val)){
            $new -> biblio_contributors =  simport_create_biblio_authors($val, 2);
          }
          break;

        case 'biblio_tertiary_authors':
          if(!empty($val)){
            $new -> biblio_contributors =  simport_create_biblio_authors($val, 3);
          }
          break;

        case  'biblio_other_author_affiliations':
          //Subsidiary Author is auth_type 4
          //TODO: not sure where this maps to???
          break;

        case 'biblio_corp_author':
          if(!empty($val)){
            $new -> biblio_contributors =  simport_create_biblio_authors($val, 5);
          }
          break;
      }
      }
    }
  }
  //do some cleanup of the node properties.  TODO: should be cleaner???
  unset($new->nid);
  unset($new->vid);
  $vsite = simport_get_new_vsite($old -> og_groups[0]);
  $new -> uid = $vsite -> group -> uid;
  $new -> name = $vsite -> group -> name;
  
}

function simport_create_biblio_authors($val, $auth_type, $i = 0){
  $authors = _simport_fix_biblio_authorstr($val);
  foreach($authors as $author){
    $value[$auth_type][$i] = array(
    'name' => $author,
    'auth_type' => $auth_type,
    'rank' => $i,
    );
    $i++;
  }
  return $value;
}

/**
 * Helper function to fix author(s) string inconsistancies
 * 
 * @param string $val - author string
 * @return  returns an array of author names
 */
function _simport_fix_biblio_authorstr($val){
  //look for these patterns in the author string and replace them with a semi-colon
  $patterns = array( '/\sand\s/',  '/\swith\s/', '/\,/', '/\;;/'); 
  
  for ($i = 0; $i < count($patterns); $i++){ 
  $replace[] = ';';
  }
  return explode(';', preg_replace($patterns, $replace, $val));
}

/**
 *Function which creates custom biblio type
 */
function simport_create_biblio_type(){
  //create biblio type - Working Paper
  db_query("INSERT INTO {biblio_types} (tid, name, description, weight, visible) VALUES (%d, '%s' , '%s', %d, %d)", 1000,  'Working Paper', 'Scholar Working Paper', 0,1);
}

/**
 * Save files after nodes have been saved
 */
function simport_get_files(){
  module_load_include('inc', 'simport', 'simport.api');

  //list of old types => filefield that have files
  $types = array(
  'scholar_link',
  );

  foreach ($types as $type) {
    $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s'", $type);
    //$sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s' AND id = %d", $type, 26);
    while ($data = db_fetch_object($sql)){
      //get the old site node object
      $old = unserialize($data ->data);

      switch($data -> type){

        case 'scholar_link':
          //check if file(s) exist
          if ($old -> field_image[0]['fid'] > 0){
            
            //load the new node
            $node = node_load(array('nid' => simport_get_new_nid($old -> nid)));           
            
            //load the vsite
            $vsite =  spaces_load ( 'og', key($node -> og_groups), TRUE );

            foreach($old -> field_image as $old_file){
              //define full path to file
              $source = variable_get('simport_remote_path', '') . '/' . $old_file['filepath'];
              
              //unset old info for fid and nid
              unset($old_file['nid']);
              unset($old_file['fid']);

             //call api function to import file
              $file = simport_import_file($node, $source, (object)$old_file, $vsite);
              
              //If file had description text add it here
             $file->description =  isset($old_file -> description) ? $old_file -> description : $file -> filename; 
             $file->list = 1;
                  
              // upload_save($node);
               
              //taken from upload_save()
              db_query("INSERT INTO {upload} (fid, nid, vid, list, description, weight) VALUES (%d, %d, %d, %d, '%s', %d)", $file->fid, $node->nid, $node->vid, $file->list, $file->description, $file->weight);
      file_set_status($file, FILE_STATUS_PERMANENT);
      
      
              //not using filefield anymore - no longer called
             // simport_node_add_imagefield_image($source, 'field_link_image', $node);
            }
          }
          break;
      }
    }
  }
}

/**
 * Returns vocabulary information specific to site and content type
 * @param $sid- site id
 * @param $type- content type
 */
function simport_get_site_vocabularies($sid, $type){
  $vocabs = taxonomy_get_vocabularies($type);
 return $vocabs[$sid];
}

/**
 * Correlate old content types to new content types
 * NOT INCLUDING biblio or scholar_admin (biblio nodes to be handled seperately)
 */
function _simport_map_content_types($old_type = NULL){

  $types = array(
  'scholar_link' => 'link',
  'scholar_announcement' => 'announcement',
  'scholar_bio' => 'page',
  'scholar_class' => 'class',
  'scholar_page' => 'page',  //both scholar_bio and scholar_page import to page
  //'biblio' => 'biblio', 
 
  // 'scholar_cv' => '', //ONLY 1 Submit it manually
 // 'scholar_photo' => '', //already dealt with in simport_set_logo()
 ); 
  //if a specific type is specified as an argument, then just return the equivilent for that type
  if ($old_type){    
    return $types[$old_type];
  }
  //otherwise return array with equivilents for all types
  return $types;
}

/**
 * Import serialized data from the D5 scholar site
 */
function _simport_exportdata(){
  global $db_url;

  $db_conn = array();
  //get the connection params  
  $db_arr = explode('/', $db_url);
  $db_user = explode(':', $db_arr[2]);
  $db_pass = explode('@', $db_user[1]);   
  
  $db_conn['user'] = $db_user[0];
  $db_conn['name'] = $db_arr[3];
  $db_conn['pass'] = $db_pass[0];
  $db_conn['host'] = $db_pass[1];
    
  $cmd = 'mysql -u' . $db_conn['user'] . ' -p' . $db_conn['pass']. ' ' .  $db_conn['name'] . ' < ' . 
  dirname(__FILE__) .  '/export/scholar_export_data.sql';
  
  //execute command to import table
  shell_exec($cmd);
}

function simport_sync_themes(){
  $sql = db_query("SELECT * FROM {og}");
  while($data = db_fetch_object($sql)){
   $space = spaces_load ( 'og', $data->nid, TRUE );
   //dpm (trim($space -> settings['theme']));
   $theme = trim($space -> settings['theme']);
   $sql_ins = db_query("UPDATE {og} SET og_theme = '%s' WHERE nid = %d", $theme, $data->nid);
  }
}

/**
 * Returns file system path before Drupal
 */
function _simport_get_fileroot(){
  $s = dirname(__FILE__);
  $end_str = strstr($s, '/sites');
  $fileroot= explode($end_str, $s);
  return $fileroot[0]; 
}

/**
 * Do some clean up tasks - such as remove the D5 scholar site automated welcome nodes
 */
function simport_cleanup(){
  $str = 'Welcome to my new site%';
  $sql = db_query("SELECT nid, title, type FROM {node} WHERE title LIKE '%s' AND type = '%s'",$str, 'announcement');
  while ($data = db_fetch_object($sql)){

    $node = node_load($data -> nid);

    //removing "Welcome" nodes
    db_query('DELETE FROM {node} WHERE nid = %d', $node->nid);
    db_query('DELETE FROM {node_revisions} WHERE nid = %d', $node->nid);

    // Clear the page and block caches.
    cache_clear_all();

    // Remove this node from the search index if needed.
    if (function_exists('search_wipe')) {
      search_wipe($node->nid, 'node');
    }
  }
}

/**
 * Check if term exists in a vocab
 */
function simport_import_term_exists($term, $vid){  
    //returns string $tid of term or false
  return db_result(db_query("SELECT tid FROM {term_data} WHERE vid = %d AND (LCASE(name) LIKE LCASE( '%s'))", (int)$vid, $term));
}


/**
 * Import any custom menu links
 */
function simport_set_menu_links(&$context){
  module_load_include('inc', 'simport', 'simport.menu_links');

  $context['message'] = 'Created Custom Menu Links';

  $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s' ORDER BY id ASC", 'admin_scholar' );
 // $sql = db_query("SELECT * FROM {scholar_export_data} WHERE type = '%s' AND id = %d", 'admin_scholar', 2);
  while ($data = db_fetch_object($sql)) {

    //get the old site node object
    $old = unserialize($data ->data);
    //get custom links
    $custom_links = simport_get_menu_links($old); //return dpm($custom_links);

    if (count($custom_links)){

      foreach($custom_links as $link){
        //get new nid
        $nid = simport_get_new_nid($link['nid']);

        //now create the custom menu links!!!
        simport_add_custom_menu_links($link, $nid, (int)$link['primary']);
      }
    }
  }
}

/**
 * Checks to see if feature is enabled, if not them enable it
 *
 * @param unknown_type $type
 * @param unknown_type $vsite
 */
function simport_check_feature($type, $vsite){
	
}