<?php
include_once('iqss_openscholar_front.features.inc');

/**
 * hook strongarm
 */
function iqss_openscholar_front_init(){
  global $conf;

  // Site mission; to be displayed in the front page
  $scholar_mission = '<p><strong>Scholars at Harvard</strong> is a free web site building tool available to faculty, graduate students and visiting scholars at Harvard. It is one of two main Harvard installations of <strong>OpenScholar</strong> and a creation of Harvard’s <em>Institute for Quantitative Social Science.</em></p><p><strong>Scholars at Harvard</strong> (and the project-oriented <strong>Projects at Harvard</strong>) provide simple web site creation and management with a suite of features tailored to the particular needs of academics.</p>';

  $project_mission = '<p><strong>Projects at Harvard</strong> is a free web site building tool available to groups at Harvard wishing to create a site for their project. It is one of two main Harvard installations of <strong>OpenScholar</strong> and a creation of Harvard’s <em>Institute for Quantitative Social Science.</em></p><p><strong>Projects at Harvard</strong> (and the personal site-oriented <strong>Scholars at Harvard</strong>) provide simple web site creation and management with a suite of features tailored to the particular needs of academics.</p><p class="big-button">'. openscholar_front_getyoursitebutton() . '</p>';

  $conf['site_mission'] = variable_get('openscholar_installation_mode', 'scholar') == 'scholar' ? $scholar_mission : $project_mission;
}


/**
 * Implementation of hook_menu_alter
 * We need to do some stuff immediately after
 * the installation if finished; Alter the 'node' callback
 */
function iqss_openscholar_front_menu_alter(&$items){
  $items['welcome']['page callback'] = 'iqss_openscholar_front_homepage';
}

/**
 * Callback for 'welcome' menu entry
 */
function iqss_openscholar_front_homepage(){
  $s_content = theme('iqss_openscholar_front_content');
  return $s_content;
}

/**
 * Implementation of hook_theme
 */
function iqss_openscholar_front_theme(){

  // load a different template file depending on the installation mode
  $install_mode = variable_get('openscholar_installation_mode', 'scholar');

  $items["iqss_openscholar_front_content"] = array(
    'arguments' => array('tree' => array()),
    'template' => "iqss-openscholar-front-${install_mode}-content",
  );

  return $items;
}

/**
 * implementation of hook_context_default_contexts_alter
 */
function iqss_openscholar_front_context_load_alter(&$context){
  // add some extra links (block) in the 'sitewide_front'
  if ($context->name == 'openscholar-section-sitewide_front') {

    $context->reactions['block']['blocks']['iqss_openscholar_front-top_links'] = array(
      'module' => 'iqss_openscholar_front',
      'delta' => 'top_links',
      'weight' => 37,
      'region' => 'header_main',
      'status' => 0,
      'label' => 'OpenScholar: Top links',
      'type' => 'context_ui'
    );

	  //Remove the blocks that are moved to the content region
	  unset($context->reactions['block']['blocks']['openscholar_front-top_links']);
	  unset($context->reactions['block']['blocks']['openscholar_front-site_mission']);
	  //Site Mission Statement
	  unset($context->reactions['block']['blocks']['openscholar_front-video_info']);
	  //Video

	  $context->reactions['block']['blocks']['iqss_openscholar_front-search'] = array(
	    'module' => 'search',
	    'delta' => 0,
	    'weight' => 37,
	    'region' => 'header_right',
	    'status' => 0,
	    'label' => '',
	    'type' => 'context_ui'
	  );

  }

  if ($context->name == 'openscholar-section-sitewide' && count($context->reactions)) {
  	if(isset($context->reactions['block']['blocks']['openscholar_front-top_links'])){
  	  //Remove the add site block from the iqss page, it is in the tpl
      unset($context->reactions['block']['blocks']['openscholar_front-top_links']);
  	}
  }
}

/**
 * Implementation of hook_block().
 */
function iqss_openscholar_front_block($op = 'list', $delta = 0) {
  switch ($op) {
    case 'list':
      $info = array(
        'top_links' => array('info' => t('OpenScholar: Top links')),
      );

      return $info;
    case 'view':

      $function = "_iqss_openscholar_front_block_{$delta}";
      if (function_exists($function)) {
        return call_user_func($function);
      }
      break;
  }
}

/**
 * hook preprocess page
 */
function iqss_openscholar_front_preprocess_page(&$vars){
  //Add the footer copyright message for iqss sites
  if (context_isset('context','openscholar-section-sitewide_front')) {
    $vars['footer_message'] = t("&copy; President &amp; Fellows Harvard University. <a class='iqss-link' href='http://iq.harvard.edu'>Institute for Quantitative Social Science</a> ") . l('Contact Us','http://openscholar.harvard.edu/contact',array('attributes'=> array('class'=>'iqss-link')));
    }
}

/**
 * callback function for top_links block
 */
function _iqss_openscholar_front_block_top_links(){
  $block = array();
  $block['subject'] = t('');
  $block['content'] = theme_iqss_openscholar_front_block_top_links();
  return $block;
}

/**
 * Generate content of the top_links block
 */
function theme_iqss_openscholar_front_block_top_links(){ // @todo make it a real theme function
  $items = array();

  global $user;
  $items[] = array(
    'title' => $user -> uid ? 'Log out' : 'Log in',
    'href' =>  $user -> uid ? 'logout' : 'user',
  );

  $vsites = vsite_get_vsite_by_owner($user->uid);
  if (!scholarregister_vsite_exists_access($vsites)) {
    if($vsites){
	    $items[] = array(
		    'title' => ((count($vsites) > 1) ? 'Go to your sites' : "Go to your site"),
		    'href' => ((count($vsites) > 1) ? 'user' : "node/".$vsites[0] -> id),
		  );
    } //No sites ora ablility to create one
  }else{
  	//Create a site
  	$items[] = array(
	    'title' => ((count($vsites) > 1)?"Create a web site.":'Get your web site!'),
	    'href' => 'site/register',
	  );
  }

  $txt = 'Need a Site for a Project?';
  $url = 'http://projects.iq.harvard.edu';
  $mode = variable_get('openscholar_installation_mode', 'scholar');

  if ($mode == 'project'){
    $txt = 'Need a Personal Site?';
    $url = 'http://scholar.harvard.edu';
  }

  $items[] = array(
    'title' => $txt,
    'href' =>  $url,
  );

  $attributes = array('id' => 'top-front');
  return theme('links', $items, $attributes);
}

