<?php

include_once('scholar_image_gallery.features.inc');

/**
 * Implementation of hook_init().
 */
function scholar_image_gallery_init() {
  drupal_add_css(drupal_get_path('module', 'scholar_image_gallery') .'/scholar_image_gallery.css');
}

function scholar_image_gallery_link_alter(&$links, $node){
  if(isset($links['image_field_gallery'])){
    unset($links['image_field_gallery']);
  }
}

/**
 * hook  vsite_content_types_alter
 */
function scholar_image_gallery_vsite_content_types_alter(&$content_types){
  unset($content_types['image']);
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_image_gallery_context_links_alter(&$links){
  if (! empty($links['image'])) {
    unset($links['image']);
  }
}


/**
 * hook strongarm
 * @return unknown_type
 */
function scholar_image_gallery_strongarm(){
  $conf = array();
  $conf['upload_image'] = 0;
  $conf['upload_gallery'] = 0;
  
  $conf["show_preview_changes_gallery"] = FALSE;
  $conf["show_diff_inline_gallery"] = FALSE;
  $conf["show_preview_changes_image"] = FALSE;
  $conf["show_diff_inline_image"] = FALSE;
  
  // Comments
  $conf['comment_image'] = COMMENT_NODE_DISABLED;
  $conf['comment_gallery'] = COMMENT_NODE_DISABLED;

  // Pathauto (optional) settings
  $conf["pathauto_node_image_pattern"] = "[space-og-path]/galleries/[field_gallery-path]/[title-raw]";
  $conf["pathauto_node_gallery_pattern"] = "[space-og-path]/galleries/[title-raw]";
  
  return $conf;
}

/**
 * hook vsite_sidgets
 * @return unknown_type
 */
function scholar_image_gallery_vsite_widgets(){
  $items = array();
  $items['scholar_image_gallery-block_1'] = array(
    'module' => 'scholar_image_gallery',
    'delta' => 'scholar_image_gallery-block_1',
    'weight' => 20,
    'region' => false,
    'status' => '0',
    'label' => 'Recent images',
    'type' => 'context_ui'
  );
  return $items;
}

/**
 * hook vsite_taxonomy_content_types_alter
 * @return unknown_type
 */
function scholar_image_gallery_vsite_taxonomy_content_types_alter(&$types){
  // no taxonomy for gallery/images
  unset($types['gallery']);
  unset($types['image']);
}


/**
 * Hook nodeapi
 * Used to trickle deltes to an image galleries dependent image childern
 */
function scholar_image_gallery_nodeapi(&$node, $op, $a3, $a4){
	if($node->type != 'gallery') return;
  switch($op){
    case 'delete':
    	vsite_include('vsite');
    	$a_referers = vsite_get_referrers($node->nid,array(),array('image'));
    	foreach ($a_referers as $nid => $info) node_delete($nid);
    break;
  }
}

/**
 * implementation of hook_views_pre_render
 * @param unknown_type $view
 */
function scholar_image_gallery_views_pre_render(&$view){
  if ($view->name == 'scholar_image_gallery') {
    if ($view->current_display == 'node_content_1' || $view->current_display == 'node_content_2') {
      
      // ask nodreference_url module for the correct link
      $link = nodereference_url_build_all_links($view->current_node, FALSE);
      $link = theme('links', $link, $attributes = array('class' => 'image-upload'));
      
      // display a series of links depending on the number of images in the gallery
      $links = array();
      $count = count($view->result);
      
      switch ($count) {
        case 0 :
          $links = $link . $link . $link;
          break;
        case 1 :
          $links = $link . $link;
          break;
        default :
          $links = $link;
      }
      
      // looks like attachment_after happens only if there is result already
      if ($count) {
        $view->attachment_after = $links;
      }
      else {
        $view->display['default']->handler->options['empty'] = $links;
      }
    }
  }
}
