<?php

function iqss_scholar_init() {
  
  //Important since we use page-caching in production and have the vsite home pages as the logout desitnation
  if(user_is_logged_in() && !headers_sent()){
    //Change to no-store
    header("Cache-Control: no-store, no-cache, must-revalidate");
  }//Fixes issue where firefox caches logged-in page after logout
  
}

/**
 * implement hook strongarm
 *
 * This should be used for IQSS only settings
 * @return array
 */
function iqss_scholar_strongarm(){
  require_once drupal_get_path('module','iqss_scholar').'/iqss_scholar.defaults.inc';

  $conf = array();
  $conf = array_merge($conf,_iqss_scholar_config_variables());
  $conf = array_merge($conf,_iqss_scholar_config_by_domain());

  //if the Scholar Profile has been installed
  if (module_exists('cite_distribute')){
    $submodules = cite_distribute_installed_mods();
    foreach ($submodules as $module){

      switch($module['name']){
        case 'repec_meta':
          $conf['repec_meta_inst_name'] = 'The Institute for Quantitative Social Science';
          $conf['repec_meta_archive_code'] = 'qsh';
          $conf['repec_meta_archive_path'] = '/nfs/www/edu-harvard-iq-repec/RePEc/qsh/';
          $conf['repec_meta_provider_institution'] = 'RePEc:edi:cbrssus';
          $conf['repec_meta_archive_url'] = 'http://repec.iq.harvard.edu/RePEc/qsh/';
          $conf['repec_meta_provider_homepage'] = 'http://scholar.harvard.edu';
          $conf['repec_meta_maintainer_name'] = 'Jon Sagotsky';
          $conf['repec_meta_maintainer_email'] = 'jsagotsky@iq.harvard.edu';

          break;
        case 'cs_meta':
          $conf['cs_meta_inst_name'] = 'The Institute for Quantitative Social Science';
          $conf['cs_meta_archive_path'] = '/nfs/www/edu-harvard-iq-repec/cs';
          break;

        case 'googlescholar_meta':
          //no system settings needed for googlescholar_meta
          break;
      }
    }
  }
  return $conf;
}

/**
 * Alter Mollom Settings
 */
function iqss_scholar_mollom_form_info_alter(&$form_info, $form_id){
	$a_mollom_forms = array('contact_mail_page','contact_mail_user','user_register','user_pass','comment_form','vsite_support_contact_mail_owner');

	//Mollom only for logged out users
	if(cp_access_cp()) $form_info['bypass access'][] = 'access content'; //adding a permission everyone has always
	
  $form_info['mode'] = (in_array($form_id,$a_mollom_forms))? MOLLOM_MODE_CAPTCHA:MOLLOM_MODE_DISABLED;
}

define(IQSS_DEV,0);
define(IQSS_LOCAL_DEV,1);
define(IQSS_STAGING,2);
define(IQSS_PRODUCTION,3);
define(IQSS_PROJECT_PRODUCTION,4);

function isqq_scholar_current_location(){
	
	if($_SERVER['SCRIPT_FILENAME'] && strpos($_SERVER['SCRIPT_FILENAME'],'/nfs/www/edu-harvard-iq-projects') === 0) return IQSS_PROJECT_PRODUCTION;
	
	switch($_SERVER['HTTP_HOST']){
		case 'projects.iq.harvard.edu':
      return IQSS_PROJECT_PRODUCTION;
		case 'scholar-test.iq.harvard.edu':
		  return IQSS_STAGING;
		case 'scholar-dev1.iq.harvard.edu':
		case 'scholar-dev2.iq.harvard.edu':
		case 'scholar-dev3.iq.harvard.edu':
      return IQSS_DEV;
    case 'localhost':
      return IQSS_LOCAL_DEV;
	}
	
  switch($_SERVER['SERVER_ADDR']){
    case '127.0.0.1':
    case '::1':
      return IQSS_LOCAL_DEV;
  	case '140.247.115.239':
    default:
      return IQSS_PRODUCTION;
  }
}
