<?php

include_once('iqss_scholar.features.inc');

function iqss_scholar_init() {

  //Important since we use page-caching in production and have the vsite home pages as the logout desitnation
  if(user_is_logged_in() && !headers_sent()){
    //Change to no-store
    header("Cache-Control: no-store, no-cache, must-revalidate");
  }//Fixes issue where firefox caches logged-in page after logout

}

/**
 * Alter Mollom Settings
 */
function iqss_scholar_mollom_form_info_alter(&$form_info, $form_id){
	$a_mollom_forms = array('contact_mail_page','contact_mail_user','user_register','user_pass','comment_form','vsite_support_contact_mail_owner');

	//Mollom only for logged out users
	if(cp_access_cp()) $form_info['bypass access'][] = 'access content'; //adding a permission everyone has always

  $form_info['mode'] = (in_array($form_id,$a_mollom_forms))? MOLLOM_MODE_CAPTCHA:MOLLOM_MODE_DISABLED;
}

define(IQSS_DEV,0);
define(IQSS_LOCAL_DEV,1);
define(IQSS_STAGING,2);
define(IQSS_PRODUCTION,3);
define(IQSS_PROJECT_PRODUCTION,4);

function isqq_scholar_current_location(){

	if($_SERVER['SCRIPT_FILENAME'] && strpos($_SERVER['SCRIPT_FILENAME'],'/nfs/www/edu-harvard-iq-projects') === 0) return IQSS_PROJECT_PRODUCTION;

	switch($_SERVER['HTTP_HOST']){
		case 'projects.iq.harvard.edu':
      return IQSS_PROJECT_PRODUCTION;
		case 'scholar-test.iq.harvard.edu':
		  return IQSS_STAGING;
		case 'scholar-dev1.iq.harvard.edu':
		case 'scholar-dev2.iq.harvard.edu':
		case 'scholar-dev3.iq.harvard.edu':
      return IQSS_DEV;
    case 'localhost':
      return IQSS_LOCAL_DEV;
	}

  switch($_SERVER['SERVER_ADDR']){
    case '127.0.0.1':
    case '::1':
      return IQSS_LOCAL_DEV;
  	case '140.247.115.239':
    default:
      return IQSS_PRODUCTION;
  }
}

function iqss_scholar_strongarm_alter(&$export) {
        
  $strongarm = new stdClass;
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'upload_extensions_default';
  $strongarm->value = 'jpg jpeg gif png txt doc docx gz xls pdf ppt pps odt ods odp tex tgz xml zip';
  $export['upload_extensions_default'] = $strongarm;
		  
	switch (isqq_scholar_current_location()) {
		case IQSS_DEV:
	    //PINSERVER Config Variables
	    $strongarm = new stdClass;
		  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
		  $strongarm->api_version = 1;
		  $strongarm->name = 'pinserver_app_name';
		  $strongarm->value = 'FAS_IQSS_SCHOLARSWEB_DEV';
		  $export['pinserver_app_name'] = $strongarm;
		  
		  $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_gpg_dir';
      $strongarm->value = '/nfs/www/edu-harvard-iq-scholar-dev3/' . '.gnupg';
      $export['pinserver_gpg_dir'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'error_level';
      $strongarm->value = 1; //Log to screen and log;
      $export['error_level'] = $strongarm;
	  break;
		case IQSS_LOCAL_DEV:
			//PINSERVER Config Variables
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_app_name';
      $strongarm->value = 'FAS_IQSS_SCHOLARSWEB_DEV';
      $export['pinserver_app_name'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_gpg_dir';
      $strongarm->value = '/tmp/' . '.gnupg';
      $export['pinserver_gpg_dir'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'error_level';
      $strongarm->value = 1; //Log to screen and log;
      $export['error_level'] = $strongarm;
		break;
		case IQSS_STAGING:
			//PINSERVER Config Variables
			$strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_app_name';
      $strongarm->value = 'FAS_IQSS_SCHOLARSWEB_TEST';
      $export['pinserver_app_name'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_gpg_dir';
      $strongarm->value = '/nfs/www/edu-harvard-iq-scholar-test/' . '.gnupg';
      $export['pinserver_gpg_dir'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'error_level';
      $strongarm->value = 0;  //Log in background only
      $export['error_level'] = $strongarm;
	  break;
		case IQSS_PRODUCTION:
			//PINSERVER Config Variables
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_app_name';
      $strongarm->value = 'FAS_IQSS_SCHOLARSWEB';
      $export['pinserver_app_name'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_gpg_dir';
      $strongarm->value = '/nfs/www/edu-harvard-iq-scholar/' . '.gnupg';
      $export['pinserver_gpg_dir'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'error_level';
      $strongarm->value = 0;  //Log in background only
      $export['error_level'] = $strongarm;

      // mollom settings
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'mollom_private_key';
      $strongarm->value = '32a73b2d09c7576f1a5d4ca73ca9dead';
      $export['mollom_private_key'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'mollom_public_key';
      $strongarm->value = 'fa9e0e813449535e5fcf06d6dda0d0f3';
      $export['mollom_public_key'] = $strongarm;

	  break;
		case IQSS_PROJECT_PRODUCTION:
			//PINSERVER Config Variables
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_app_name';
      $strongarm->value = 'FAS_IQSS_SCHOLARSWEB_PROJECTS';
      $export['pinserver_app_name'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'pinserver_gpg_dir';
      $strongarm->value = '/nfs/www/edu-harvard-iq-projects/' . '.gnupg';
      $export['pinserver_gpg_dir'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'error_level';
      $strongarm->value = 0;  //Log in background only
      $export['error_level'] = $strongarm;

      // mollom settings
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'mollom_private_key';
      $strongarm->value = '89a61a5f00b4f996c0133e16dc9cb857';
      $export['mollom_private_key'] = $strongarm;
      
      $strongarm = new stdClass;
      $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
      $strongarm->api_version = 1;
      $strongarm->name = 'mollom_public_key';
      $strongarm->value = '8429265e3d1b10dccc1a62ebf3eddb78';
      $export['mollom_public_key'] = $strongarm;
		break;
	}
}
