<?php

include_once('scholar_classes.features.inc');

/**
 * hook link_alter (admin at the end of links)
 */
function scholar_classes_link_alter(&$links, $node){
  if (isset($links['class_material_field_class'])) {
    $old = $links['class_material_field_class'];
    $old['attributes']['class'] = 'context-button';
    
    $links['class_material_field_class'] = array(
      'title' => theme('context_links', array(
        $old 
      )), 
      'html' => TRUE 
    );
  }
  
  /* 
   * If a class_material node, we want all the children
   * to be of class_material type too. But the default 
   * child type is set to 'book'. Alter here
   */
  if (empty($links['book_add_child'])) {
    return;
  }
  $links['book_add_child']['href'] = 'node/add/class-material';
}




/**
 * hook  vsite_content_types_alter
 */
function scholar_classes_vsite_content_types_alter(&$content_types){
  unset($content_types['class_material']);
}


/**
 * Implementation of hook_context_links_alter().
 */
function scholar_classes_context_links_alter(&$links) {
  if (!empty($links['class'])) {
    //$links['class']['query'] = drupal_get_destination();
  }
  
  if (!empty($links['class_material'])) {
    unset($links['class_material']);
  }
}


/**
 * Hook nodeapi
 * Used to trickle deltes to an classes dependent class-materials
 */
function scholar_classes_nodeapi(&$node, $op, $a3, $a4){
  if($node->type != 'class') return;
  switch($op){
    case 'delete':
      vsite_include('vsite');
      $a_referers = vsite_get_referrers($node->nid,array(),array('class_material'));
      foreach ($a_referers as $nid => $info) node_delete($nid);
    break;
  }
}

/**
 * Implementation of hook_strongarm().
 */
function scholar_classes_strongarm() {

  // class 
   
  $conf['node_options_class'] = array('status', 'revision');
  $conf['upload_class'] = TRUE;
 
  // Comments
  $conf['comment_class'] = COMMENT_NODE_DISABLED;
 
  // Disable preview button
  $conf["show_preview_changes_class"] = FALSE;
  $conf["show_diff_inline_class"] = TRUE;
 

  // Pathauto (optional) settings
  $conf["pathauto_node_class_pattern"] = "[space-og-path]/classes/[title-raw]";
 
  
  // class meterial 
  $conf['node_options_class_material'] = array('status', 'revision');
  $conf['upload_class_material'] = TRUE;
 
  // Comments
  $conf['comment_class_material'] = COMMENT_NODE_DISABLED;
 
  // Disable Diff button
  $conf["show_preview_changes_class_material"] = FALSE;
  $conf["show_diff_inline_class_material"] = TRUE;
 

  // Pathauto (optional) settings
  $conf["pathauto_node_class_material_pattern"] = "[space-og-path]/classes/[field_class-path]/materials/[title-raw]"; 
  
  return $conf;
}


