<?php
//$Id: citeseer_meta.module,v 1.1.1.1 2008/11/21 20:42:34 jweiner Exp $ 

/**
* @file
*  This is a custom module to allow the CiteSeerX respository to collect metadata from posted content, 
*  such as research papers and articles.
*
*/
	

function citeseer_meta_cite_distribute_register(){
$module_info[] = array(
'name'       => 'citeseer_meta',
'repository' => 'CiteSeerX Repository',
 );

return $module_info;
}

  
/**
* Implementation of hook_menu().
*
*/

function citeseer_meta_menu() {
  $items = array();

  $items['citeseer_meta/test/api'] = array(
  'title'              	=> t('Test citeseer meta api'),
  'type' 			 	=> MENU_CALLBACK,
  'page callback'           	=> 'citeseer_meta_api',
  'access callback' => user_access('administer cite distribute')
  );
  
  $items['citeseer_meta/widget'] = array(
  'page callback'           => 'citeseer_meta_widget_process',
  'access callback'             => TRUE,
  );
  
  
  $items['admin/settings/cite_distribute/citeseer_meta'] = array(
  'title' => t('CiteSeerX Meta'),
  'type' => MENU_LOCAL_TASK ,
  'page callback' => 'drupal_get_form',
  'page arguments' => array('citeseer_meta_config'),	
  'weight' => 1,
  'access callback' => user_access('administer repec settings')
  );  
  return $items;
}
  
/**
* Implementation of hook_perm()
*
*/
function citeseer_meta_perm(){
    return array('submit content to citeseer repository');
}


  
/**
* citeseer_meta_info()
* 
* @return 	Returns the system settings form for citeseer_meta 'Configuration' page
*/
function citeseer_meta_config(){
  
  
  $form['citeseer_meta'] = array( 
      '#type' => 'fieldset', 
      '#title' => t('Enter CiteSeerX Information'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE, 
      ); 
  
    $form['citeseer_meta']['citeseer_inst_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Institution Name'),
      '#default_value' => variable_get('citeseer_meta_inst_name',''),
      '#description' => t('Enter your institution\'s Name'),
      );
      
  $form['citeseer_meta']['citeseer_archive_path'] = array(
      '#type' => 'textfield',
      '#title' => t('Archive Root Path'),
      '#required' => TRUE,
      '#default_value' => variable_get('citeseer_meta_archive_path',''),
      '#description' => t('Enter the absolute path to the root of your citeseer_meta archive root.
       <br /> For example: /nfs/test/archive' )
       
  	);

  return system_settings_form($form);
}
  
function citeseer_meta_per_submission($node, $edit_val = NULL) {
  
  
  //make template here and place it 
  
}



  

