<?php


function simport_import(){
  // loop throgh all og nodes in the old database
  // and get the minimum information to create a new
  // vsite.
  // create the vsite and pass it on each of the vunction
  // below for a chance to modify it. ..
  
}


/**
 * 
 * @param $old og node from the old site
 * @param $new the new vsite
 */
function simport_set_theme($old, &$new){

}


function simport_set_logo($old, &$new){

}


function simport_set_shield($old, &$new){
  
}


function simport_import_class($old, &$new){

}


function simport_import_biblio($old, &$new){

}


function simport_import_front($old, &$new){

}



