<?php

include_once('scholar_blog.features.inc');


/**
 * Implementation of hook_context_links_alter().
 */
function scholar_blog_context_links_alter(&$links) {
  if (!empty($links['blog'])) {
    $links['blog']['query'] = drupal_get_destination();
  }
}

/**
 * hook link_alter (admin at the end of links)
 */
function scholar_blog_link_alter(&$links, $node){
  
  if (isset($links['blog_usernames_blog'])) {
    unset($links['blog_usernames_blog']);
  }
}


/**
 * Implementation of hook_strongarm().
 */
function scholar_blog_strongarm() {
  $conf = array();
 
  $conf['node_options_blog'] = array('status', 'revision');
  $conf['upload_blog'] = TRUE;
 
  // Comments
  $conf['comment_blog'] = COMMENT_NODE_READ_WRITE;
  $conf['comment_default_mode_blog'] = COMMENT_MODE_THREADED_EXPANDED;
  $conf['comment_default_order_blog'] = COMMENT_ORDER_OLDEST_FIRST;
  $conf['comment_default_per_page_blog'] = 20;
  $conf['comment_controls_blog'] = COMMENT_CONTROLS_HIDDEN;
  $conf['comment_subject_field_blog'] = 0;
  $conf['comment_preview_blog'] = COMMENT_PREVIEW_OPTIONAL;
  $conf['comment_form_location_blog'] = COMMENT_FORM_BELOW;
  //$conf['comment_upload_blog'] = TRUE;
 
  // diff / preview
  $conf["show_preview_changes_blog"] = TRUE;
  $conf["show_diff_inline_blog"] = FALSE;
  
  // Pathauto settings
  $conf["pathauto_node_blog_pattern"] = "[space-og-path]/blog/[yyyy]/[mm]/[title-raw]";
 
  $conf['node_submitted_info_blog'] = TRUE;
  return $conf;
}
