<?php

function vsite_filter_menu() {
  $menu = array();
  $menu['admin/settings/filters/reset'] = array(
    'title' => 'Reset to OpenScholar Default',
    'page callback' => 'vsite_filter_reset',
    'access callback' => TRUE,
    'weight' => 10,
    'type' => MENU_NORMAL_ITEM,
  );

  return $menu;
}

function vsite_filter_translated_menu_link_alter(&$item, $map) {
  if ($item['href'] == 'admin/settings/filters/reset') {
    $item['localized_options']['query'] = drupal_get_destination();
  }
}

function vsite_filter_reset() {
  $format = db_result(db_query("SELECT format FROM {filter_formats} WHERE name = 'Filtered HTML'"));
  $q = db_query("SELECT * FROM {filters} WHERE format = %d", $format);
  $data = array();
  while ($r = db_fetch_object($q)) {
    $data[] = $r;
  }

  foreach ($data as $d) {
    if ($d->module == 'oembed') {
      $d->weight = -9;
    }
    elseif ($d->module == 'filter') {
      switch ($d->delta) {
        case 0:
          $d->weight = -10;
          break;
        case 1:
          $d->weight = -7;
          break;
        case 2:
          $d->weight = -8;
          break;
        case 3:
          $d->weight = -6;
      }
    }

    drupal_write_record('filters', $d, array('fid'));
  }
  dpm('Filters have been reset to OpenScholar defaults.');
  drupal_goto();
}