<?php

include_once('scholar_pages.features.inc');


/**
 *  hook_strongarm().
 */
function scholar_pages_strongarm() {

 
  $conf['node_options_page'] = array('status', 'revision');
  $conf['upload_page'] = TRUE;
 
  // Comments
  $conf['comment_page'] = COMMENT_NODE_DISABLED;
 
  // Pathauto (optional) settings
  $conf["pathauto_node_page_pattern"] = "[space-og-path]/pages/[title-raw]";
 
  return $conf;
}