<?php

/**
 * Implementaton of hook_enable().
 */
function vsite_domain_enable() {
  // Now that vsites are enabled clear the cached processors
  // This will allow vsite_domain etc to add to the ctools cache
  cache_clear_all('plugins:purl:processor','cache');
}

function vsite_domain_install() {
  //Set the default domain typically the one you are installing with, otherwise you will need to change this in the settings
  variable_set('purl_base_domain', $_SERVER['HTTP_HOST']);
}
