<?php

include_once('vsite_front.features.inc');

function vsite_front_init(){
  $active_menu = menu_get_item();
  if ($active_menu['path'] == 'cp/settings/front'){
    drupal_add_css(drupal_get_path('module', 'vsite_front') .'/theme/vsite_front.css');
  }
}

function vsite_front_menu(){
  $items = array();
  $items['home'] = array(
    'type' => MENU_CALLBACK,
    'title' => '',
    'page callback' => 'vsite_front_home',
    'file' => 'vsite_front.pages.inc',
    'access arguments' => array('access content'),
    'weight' => 0,
  );
  return $items;
}

/**
 * Implementation of hook_spaces_settings().
 */
function vsite_front_spaces_settings(){
  return array(
    'front' => array(
      'class' => 'vsite_front_settings_front', 
      'file' => drupal_get_path('module', 'vsite_front') . '/vsite_front.settings.inc' 
    ),
    'home' => array(
      'class' => 'vsite_front_settings_home',
      'file' => drupal_get_path('module', 'vsite_front') .'/vsite_home.settings.inc',
    ),
  );
}


/**
 * Implementation of hook flag_default_flags
 * @return array - default flag
 */
function vsite_front_flag_default_flags(){
  //vsite_include('vsiteapi');
  //$scholar_types = array_keys(vsite_content_types());
  $types = og_get_types('group_post');
  $flags = array();
  $flags[] = array(
    'content_type' => 'node', 
    'name' => 'vsite_frontpage', 
    'title' => 'Save to Front Page', 
    'types' => $types, 
    'roles' => array(
      0 => '2' 
    ), 
    'global' => TRUE, 
    'flag_short' => 'Save to Front', 
    'flag_long' => 'Save post to front page', 
    'flag_confirmation' => 'Saved to Front Page', 
    'unflag_short' => 'Remove from Front', 
    'unflag_long' => 'Remove post from Front Page', 
    'flag_message' => 'Saved to Front Page!',
    'unflag_message' => 'Removed from Front Page',
    'status' => TRUE, 
    'show_on_page' => FALSE, 
    'show_on_teaser' => FALSE, 
    'show_on_form' => FALSE, 
    'link_type' => 'toggle',  //normal, toggle, confirm
    'locked' => array(
      'types',
      'name', 
      'show_on_page', 
      'show_on_teaser', 
      'show_on_form', 
      'global' 
    ) 
  );
  
  return $flags;
}


/**
 * Implementation of hook_link().
 */
function vsite_front_scholar_admin_link($type, $object){
  $links = array();
  global $user;
  //check font page settings here, only execute if front page setting equals flag
  $vsite = vsite_get_vsite();
  if ($vsite->settings['front']['frontpage'] !== 'flag' || 
      !($vsite -> admin_access()) ||
      !flag_fetch_definition($type)){
    return $links;
  }



  // Get frontpage flags
  $flag = flag_get_flag('vsite_frontpage');


  if (!$flag->applies_to_content_object($object)) {
    // Flag does not apply to this content.
    return false;
  }

  $content_id = $flag->get_content_id($object);
  // The flag links are actually fully rendered theme functions.
  // The HTML attribute is set to TRUE to allow whatever the themer desires.
  $links['flag-'. $flag->name] = array(
  'title' => $flag->theme($flag->is_flagged($content_id) ? 'unflag' : 'flag', $content_id),
  'html' => TRUE,
  );

  if (isset($links)) {
    return $links;
  }
}

