<?php
include_once('scholar_dvn.features.inc');

/**
 * Implementation of hook_init().
 */
function scholar_dvn_init() {
  drupal_add_css(drupal_get_path('module', 'scholar_dvn') .'/scholar_dvn.css');
}

function scholar_dvn_menu(){
  $items = array();
  $items['data'] = array(
    'title' => 'data',
    'page callback' => 'scholar_dvn_data',
    'access callback' => 'spaces_feature_access',
    'access arguments' => array('scholar_dvn'),
    'menu_name' => 'features',
  );

  return $items;
}

function scholar_dvn_data(){
  $output = "<object id=\"feature-dataverse\" type=\"text/html\" data =\"" . "http://dvn.iq.harvard.edu/dvn/dv/thailanddataverse" . "\">
  </object>";

  return $output;

  // not used
  $vsite = vsite_get_vsite();
  if (array_key_exists('scholar_dvn', $vsite->settings)) {
    // simply redirect to dvn
    $dvn_alias = $vsite -> settings['scholar_dvn']['dvn_alias'];
    $path = "http://dvn.iq.harvard.edu/dvn/dv/" . $dvn_alias;
    $http_response_code = '302';
    header('Location: ' . $path, TRUE, $http_response_code);
    exit();
  }
  elseif ($vsite->admin_access()) {
    $l1 = l('feature', "cp/features");
    $l2 = l('http://dvn.iq.harvard.edu', 'http://dvn.iq.harvard.edu', array('absolute' => TRUE));
    $result = "<p>No dataverse alias was found. Please set up your dataverse alias in your \"scholar dvn\" " . $l1 . " settings </p>";
    $result .= "<p> If you don't have a dataverse, go to " .$l2.  " to create your own dataverse to upload your data </p>";
    return $result;
  }
  else {
    return t('no dataverse available yet');
  }

}

/**
 * Implementation of hook_spaces_settings().
 */
function scholar_dvn_spaces_settings() {
  return array(
    'scholar_dvn' => array(
      'class' => 'scholar_dvn_settings_feature',
      'file' => drupal_get_path('module', 'scholar_dvn') .'/scholar_dvn.settings.feature.inc',
    ),
  );
}