<?php
/**
 * hook menu
 */
function vsite_support_menu(){
  $items = array();
  
  $items['cp/support'] = array(
    'title' => 'Support', 
    'page callback' => 'cp_route',
    'weight' => 5 
  );
  
  $items['cp/support/questions'] = array(
    'title' => 'Collaborative FAQ', 
    'page callback' => 'vsite_support_questions',
    'weight' => 0,
  );
  
  $items['cp/support/featurerequests'] = array(
    'title' => 'Feature requests', 
    'page callback' => 'vsite_support_feature_requests',
    'weight' => 1,
  );
  
  // make them all part of 'cp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'cp';
    $items[$path]['access callback'] = 'cp_access_cp'; 
  }

  return $items;
}

function vsite_support_questions(){
  return views_page($view_name = 'vsite_support_questions', $display = 'default');
}

function vsite_support_feature_requests(){
  return '(tbd)';
}

/**
 * Implementation of hook flag_default_flags
 * @return array - default flag
 */
function vsite_support_flag_default_flags(){
  $flags = array();
  $flags[] = array(
    'content_type' => 'node', 
    'name' => 'vsite_support_question_like', 
    'title' => 'Support question flag', 
    'types' => array('support_question'), 
    'roles' => array(
      0 => '2' 
    ), 
    'global' => TRUE, 
    'flag_short' => 'like', 
    'flag_long' => 'This is a good question', 
    'flag_confirmation' => 'Your vote is registered', 
    'unflag_short' => 'Undo', 
    'unflag_long' => 'Your vote is canceled', 

    'status' => TRUE, 
    'show_on_page' => TRUE, 
    'show_on_teaser' => TRUE, 
    'show_on_form' => FALSE, 
    'link_type' => 'toggle',  //normal, toggle, confirm
    'locked' => array(
      'types',
      'name', 
      'show_on_page', 
      'show_on_teaser', 
      'show_on_form', 
      'global' 
    ) 
  );
  
  return $flags;
}