<?php

include_once('os_wysiwyg.features.inc');

/*
 * come back later if I have time
 * do something about the fact that copying URLS from the address bar in Chrome
 * causes an anchor tag to be copied.
function os_wysiwyg_form_alter(&$vars) {
  static $init = false;
  if (!$init) {
    drupal_add_js('
    $(document).load(function () {
      $("iframe").each(function (i) {

      });
    	window.addEventListener("paste", function (e) {
    		console.log(e);
    	});
    });',
    'inline');
    $init = true;
  }
}*/

function os_wysiwyg_preprocess_node(&$vars) {
  static $inserted = false;
  if ($inserted) return;
  if (strpos($vars['content'], '<div class="oembed">') !== FALSE) {
    drupal_add_js('
    	$(document).ready(function() {
    		$(".oembed iframe").each(function (i) {
    			this.style.width = this.width+"px";
    			this.style.height = this.height+"px";
    		});
    	});
    ', 'inline');
    $inserted = true;
  }
}

function os_wysiwyg_install() {
  _os_wysiwyg_config();
}


/**
 * wysiwyg configurations
 */
function _os_wysiwyg_config(){
  $wysiwyg_presets = _openscholar_wysiwyg_presets();
  foreach ( $wysiwyg_presets as $filter_name => $settings ) {
    $settings = serialize($settings);

    $query = "SELECT format FROM {filter_formats} WHERE name='%s'";
    $format = db_result(db_query($query, $filter_name));
    $query = "INSERT INTO {wysiwyg} (format, editor, settings) VALUES ('%d', '%s', '%s')";
    db_query($query, $format, 'tinymce', $settings);
  }
}

function _os_wysiwyg_presets(){
  $settings = array();


  $settings['Filtered HTML'] = array(
    'default' => 1,
    'user_choose' => 0,
    'show_toggle' => 1,
    'theme' => 'advanced',
    'language' => 'en',
    'buttons' => array(
      'default' => array(
        'bold' => 1,
        'italic' => 1,
        'strikethrough' => 1,
        'bullist' => 1,
        'numlist' => 1,
        'link' => 1,
        'unlink' => 1,
        'image' => 1,
        'code' => 1,
        'cut' => 1,
        'copy' => 1,
        'paste' => 1,
        'charmap' => 1,
        'style' => 1
      ),

      'font' => array(
        'formatselect' => 1
      ),
      'fullscreen' => array(
        'fullscreen' => 1
      ),
      'paste' => array(
        'pastetext' => 1
      ),
      'table' => array(
        'tablecontrols' => 1
      ),
      'safari' => array(
        'safari' => 1
      ),
      'drupal' => array(
        'break' => 1
      )
    ),

    'toolbar_loc' => 'top',
    'toolbar_align' => 'left',
    'path_loc' => 'bottom',
    'resizing' => 1,
    'verify_html' => 1,
    'preformatted' => 0,
    'convert_fonts_to_spans' => 1,
    'remove_linebreaks' => 1,
    'apply_source_formatting' => 0,
    'paste_auto_cleanup_on_paste' => 1,
    'block_formats' => 'p,address,pre,h2,h3,h4,h5,h6',
    'css_setting' => 'theme',
    'css_path' => '',
    'css_classes' => 'Quotation=quote' . "\n" .
                      'Float Image Left=img-flL' . "\n" .
                      'Float Image Right=img-flR'
  );

  return $settings;
}