<?php

/**
 * The current openscholar version.
 */
define('OPENSCHOLAR_VERSION', '2.0-BETA9');

include_once('openscholar_front.features.inc');
include_once('openscholar_front.blocks.inc');

/**
 * Implementation of hook init
 */
function openscholar_front_init(){
  $vsite = vsite_get_vsite();
  if (!$vsite && !drupal_is_front_page()
      && arg(0) != 'admin'){
    //If we are not in admin set the context
    context_set('openscholar', 'section', 'sitewide');
  }
}

/**
 * Implementation of hook_strongarm()
 */
function openscholar_front_strongarm(){
    // Comments
  $conf['comment_sitewide_page'] = COMMENT_NODE_DISABLED;

  return $conf;
}


/**
 * Implementation of hook menu
 */
function openscholar_front_menu(){
  $items = array();
  $items['welcome'] = array(
    'type' => MENU_CALLBACK,
    'title' => '',
    'page callback' => 'openscholar_front_welcome',
    'access arguments' => array(
      'access content'
    ),
    );

  return $items;
}

/**
 * This is the default content body for the homepage, currently empty
 *
 * To add custom content your module can override the menu entry to call the function of your choosing
 */
function openscholar_front_welcome(){
  return '';
}


/**
 * Implementation of hook_block().
 */
function openscholar_front_block($op = 'list', $delta = 0) {
  switch ($op) {
    case 'list':
      $info = array(
        'top_links' => array('info' => t('OpenScholar: Top links')),
        'site_info' => array('info' => t('OpenScholar: Site info')),
        'video_info' => array('info' => t('OpenScholar: Video info')),
        'site_mission' => array('info' => t('OpenScholar: Mission Statement')),
        'site_activity' => array('info' => t('OpenScholar: Public Site Activity')),
        'recent_publications' => array('info' => t('OpenScholar: Recent Publications')),
      );

      return $info;
    case 'view':
      //Functions defined in openscholar_front.blocks.inc
      $function = "_openscholar_front_block_{$delta}";
      if (function_exists($function)) {
        return call_user_func($function);
      }
      break;
  }
}

/**
 * Logic for displaying the button used to create a users site
 */
function openscholar_front_getyoursitebutton() {
  if (!module_exists('scholarregister')) return;
  global $user;

  //we always allow admin and users with "vsite create access" to see site registration button.
  //and we allow anonymous users to create a new user account and new site
  if ( node_access('create', variable_get('scholar_content_type', 'vsite' )) || in_array('anonymous user', $user -> roles)) {
    $allow = TRUE;
  }

  // all authenticated users
  else{
    // site-owners
    if ($vsites = vsite_get_vsite_by_owner($user->uid)){
      $allow = scholarregister_vsite_exists_access($vsites);
      $site_link = (count($vsites) > 1) ? 'user' : $vsites[0] -> purl;
    }
    //  non-site owners
    else{
      $allow = TRUE;
    }
  }
  
  //link for front page button
  return  ($allow) ? l('Get your web site!', 'site/register') : l('Go to your site', $site_link);

}