<?php

function vsite_users_menu(){
  $items = array();
  
  $items['cp/users'] = array(
    'title' => 'Users',
    'page callback' => 'cp_route', 
    'weight' => 2, 
  );
  
  $items['cp/users/members'] = array(
    'title' => 'Members',
    'page callback' => 'vsite_users_members',
    'access arguments' => array('access content'),
    'file' => 'vsite_users.pages.inc',
  );  
  
  // make them all part of 'cp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'cp';
    $items[$path]['access callback'] = 'cp_access_cp'; 
  }
  return $items;
}