<?php

function vsite_generic_settings_init() {
  $active_menu = menu_get_item();
  if ($active_menu['page_callback'] == 'drupal_get_form' && 
    is_array($active_menu['page_arguments']) &&
    in_array('cp_settings_form', $active_menu['page_arguments']) && 
    in_array('generic', $active_menu['page_arguments'])) {
    $a_settings = module_invoke_all('vsite_generic_settings', vsite_get_vsite(), array());
    
    foreach ($a_settings as $s_key => $setting) {
      //Add form Css
      if (array_key_exists('css', $setting)) foreach ($setting['css'] as $css) drupal_add_css($css);
      
      //Add form JS
      if (array_key_exists('js', $setting)) foreach ($setting['js'] as $js) drupal_add_js($js);
    } 
  }
}

/**
 * Implementation of hook_spaces_settings().
 */
function vsite_generic_settings_spaces_settings() {
  return array(
    'generic' => array(
      'class' => 'vsite_generic_settings_settings', 
      'file' => drupal_get_path('module', 'vsite_generic_settings') . '/includes/vsite_generic_settings.settings.inc' 
    ) 
  );
}
