<?php

/**
 * Implementation of hook_install().
 */
function cp_install() {
  db_query("INSERT INTO {menu_custom} (menu_name, title, description) VALUES ('%s', '%s', '%s')", 'cp', 'Scholar CP', 'Scholar CP links');
}


/**
 * Update 6001: Create admin menu.
 */
function cp_update_6001() {
  $return = array();
  $return[] = update_sql("INSERT INTO {menu_custom} (menu_name, title, description) VALUES ('cp', 'Scholar CP', 'Scholar CP links')");
  return $return;
}




