<?php
define('CPTHEME', 'cp_theme');

function cp_init(){
   // TODO We can get the active space here. 
   // add this only if in active space + user is admin of space + users wants the toolbar anywhere
   drupal_add_css(drupal_get_path('module', 'cp') .'/theme/cp-toolbar.css');

   // define some contexts (TODO can we group them all together in scholar.module ?
   
   // controlcp context
  if (arg(0) == 'cp' || (arg(0) == 'node' && (arg(1) == 'add' || arg(2) == 'edit'))) {
    context_set('scholar', 'section', 'cp');
    // since we are here .. initialize cp theme
    _cp_init_theme();
  }
  
  else {
  	$space = spaces_get_space();
  	if ($space -> type == 'og'){
  	  context_set('scholar', 'section', 'vsite');
  	  og_set_theme($space -> group); // TODO why dont you get it from space settings
  	}
  }
}

/**
 * Implementation of hook_spaces_settings().
 */
function cp_spaces_settings() {
  return array(
   'site' => array(
      'class' => 'cp_setting_site',
      'file' => drupal_get_path('module', 'cp')  .'/settingsinc/cp.setting.site.inc',
    ),
    'theme' => array(
      'class' => 'cp_setting_theme',
      'file' => drupal_get_path('module', 'cp') .'/settingsinc/cp.settings.theme.inc',
    ),
    'logo' => array(
      'class' => 'cp_setting_logo',
      'file' => drupal_get_path('module', 'cp') .'/settingsinc/cp.settings.logo.inc',
    ),
    'front' => array(
      'class' => 'cp_setting_front',
      'file' => drupal_get_path('module', 'cp') .'/settingsinc/cp.settings.front.inc',
    ),
    'bio' => array(
      'class' => 'cp_setting_bio',
      'file' => drupal_get_path('module', 'cp') .'/settingsinc/cp.settings.bio.inc',
    ),
    'menus' => array(
      'class' => 'scholarmenu_menus',
      'file' => drupal_get_path('module', 'scholarmenu') .'/scholarmenu.menus.inc',
    ),
    'layout' => array(
      //handled by scholar layout module
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function cp_views_api() {
  return array(
    'api' => 2,
  );
}


function cp_menu(){
	$spaces_path = drupal_get_path('module', 'spaces');
  //$items = spaces_active_space_menu('og', FALSE, 'cp/settings');

  $items = array();

  // content
  // TODO fix its not working: trying to make the children menu as local task
  $items['cp/content'] = array(
    'title' => 'Content',
    'page callback' => 'cp_route',
    'weight' => 1,    
    );

  $items['cp/content/all'] = array( 	 
    'title' => 'All',
    //'type' => MENU_DEFAULT_LOCAL_TASK,	
    'page callback' => 'cp_content',  
    'file' => 'cp.content.inc',
    'file path' => drupal_get_path('module', 'cp'). '/includes', 	 
    );
  
  // a menu entry for each content type
  scholar_include('scholarapi');
  $content_types = scholar_content_types();
  foreach($content_types as $type => $name){
    $items['cp/content/'.$type] = array(
      'title' => $name,
    	//'type' => MENU_LOCAL_TASK,	
      'page callback' => 'cp_content',
      'page arguments' => array($type, $name),
      'file' => 'cp.content.inc',
      'file path' => drupal_get_path('module', 'cp'). '/includes', 	 
    );    
  }
  
  $items['cp/users'] = array(
    'title' => 'Users',
    'page callback' => 'cp_route', 
    'weight' => 2, 
  );
  
  $items['cp/users/members'] = array(
    'title' => 'Members',
    'page callback' => 'cp_user_members',
    'access arguments' => array('access content'),
    'file' => 'cp.users.inc',
    'file path' => drupal_get_path('module', 'cp'). '/includes', 
  );

  $items['cp/news'] = array(
    'title' => 'News',
    'page callback' => 'cp_cp',
    'weight' => 3,
  ); 
  
  $items['cp/support'] = array(
    'title' => 'Support',
    'page callback' => 'cp_cp',
    'weight' => 4,
  );
  
  $items['cp/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'cp_route',
    'weight' => 0,
  );  
  
  // other setting by classess
  $space = spaces_get_space();
  //dpm(spaces_settings($space->type, TRUE));
  // we go on all settings and make a menu entry for all of them
  foreach (spaces_settings($space->type, TRUE) as $setting) {
    $setting_value = isset($space->settings[$setting->id]) ? $space->settings[$setting->id] : NULL;
    $setting_form = $setting->form($space, $setting_value);
    if (!empty($setting_form)) {
      $items['cp/settings/'. $setting -> id] = array(
        'title' => $setting_form['#title'],
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cp_settings_form', $setting -> id),
        'file' => 'cp.settings.inc',
        'file path' => drupal_get_path('module', 'cp'). '/includes', 
      );
    }
  }
  
  $items["cp/settings/features"] = array(
    'title' => 'Features',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spaces_features_form'),
    //'access callback' => 'spaces_admin_access',
    //'access arguments' => array('og', 'features'),
    'file' => 'spaces_admin.inc',
    'file path' => $spaces_path,
    'weight' => 0,
  );
  
  $items["cp/settings/features/%"] = array(
    'title' => 'Features',
    'page callback' => 'schlarcp_feature_customize',
    'page arguments' => array(3),
    //'page callback' => 'drupal_get_form',
    //'page arguments' => array('spaces_customize_form', NULL, 3),
    'file' => 'spaces_admin.inc',
    'file path' => $spaces_path,
    'weight' => 1,
  );
  
  // make them all part of 'cp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'cp';
    $items[$path]['access arguments'] = array('access content'); //TODO fix this 
  }

  return $items;
}


function cp_cp(){
  return '(tbd)';
}

function cp_route(){
  $tree = menu_tree_page_data('cp');
  foreach ($tree as $item) {
    if (cp_in_active_trail($item['link']['href']) && !empty($item['below'])) {
    	$a_settings =  array_shift($item['below']);
    	return menu_execute_active_handler($a_settings['link']['href']);
    }
  }
  
  return MENU_NOT_FOUND;
}


/**
 * callback function for our popup forms
 */
function schlarcp_feature_customize($feature_name){
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();
  
  $form_state = array(
    're_render' => TRUE,
    'ajax' => TRUE,
  );

  // pass all arguments needed by the callback function (ctools thing)
  $form_state['args'] = array(NULL, $feature_name);

  $output = ctools_modal_form_wrapper('spaces_customize_form', $form_state);

  if (empty($output)) {
    $output = array();
    $output[] = ctools_modal_command_dismiss();
  }
  
  ctools_ajax_render($output);
}


/**
 * hook form_alter
 */
function cp_form_alter(&$form, $form_state, $form_id) {

  /*
   * we'd like to remove the space settings from 'spaces_features_form'
   * and make 'settings' link as a popup link
   */
  if (arg(0) == 'cp' && $form_id == 'spaces_features_form'){

    // we dont need settings here
    unset($form['settings']);
    $site = $form['space']['#value'];
    // we would like to change the "customize" link to "settings" 
    // and display the form in the popup
    foreach (array_keys($site -> features) as $f_name){
      if (isset($form['customize'][$f_name])){ 
        ctools_include('ajax');
        ctools_include('modal');
        ctools_modal_add_js();
        $link = ctools_modal_text_button('settings', 'cp/settings/features/'. $f_name, 'whatever');
        $form['customize'][$f_name]['#value'] = $link;
      }
    }
  }
}

function cp_form_views_exposed_form_alter(&$form, $form_state, $form_id = 'views_exposed_form'){

  if($form['#id'] == 'views-exposed-form-cp-content-default'){
  //TODO: Is there a better way to get the content type argument???
  $type = arg(2);
  //set action to current url
  $form['#action'] = request_uri();

  $options = array(
  'All' => check_plain('<Any>'),
  1 => 'Yes',
  0 => 'No',
  );

  //get the site information
  $site = scholar_get_scholar();
  //get the vocabularies vid's associated with this site
  $site_vocabs = array_keys(og_vocab_get_vocabularies($site -> group ->nid));
  //get the vocabularies vid's associated with content type
  $type_vocabs = array_keys(taxonomy_get_vocabularies ($type));

  if (count($site_vocabs) &&  count($type_vocabs)){
    //merge common vids
    $vid = array_intersect($site_vocabs, $type_vocabs);
  }

  //if no vocabulary, then do no show select box
  if(empty($vid)){
    //remove Categores selection box
    unset($form['#info']['filter-tid']);
    unset($form['tid']);
  }
  else{
    //NOTE just passing the first element of the array here because it is assumed
    //1 vocab per type
    $terms = taxonomy_get_tree($vid[0]);
  }
    
    //if no terms, then do no show select box
  if(empty($terms)){
       //remove Categores selection box
    unset($form['#info']['filter-tid']);
    unset($form['tid']);
    }

    else{       
    //now we have the terms for this site, create an array formatted
    //for the taxonomy options in the exposed filter.
    //TODO: for now we just are going to use 1 vocabulary, but perhaps
    //should nest loops so it can deal with multiple vocabs????
    foreach($terms as $term){
      $taxonomy_options[$term -> tid]  =  $term -> name;
    }
  //taxonomy terms flter
  $form['tid']['#options'] = $taxonomy_options;
  //5 terms max shown per select box
  $form['tid']['#size'] = count($taxonomy_options) < 6 ? count($taxonomy_options) : 5;
  }
  
  //promoted to front page filter
  $form['promote']['#type'] = 'radios';
  $form['promote']['#options'] = $options;

  //published status filter
  $form['status']['#type'] = 'radios';
  $form['status']['#options'] = $options;

  //sticky on top of lists filter
  $form['sticky']['#type'] = 'radios';
  $form['sticky']['#options'] = $options;
  }
}
  

/**
 * Implementation of hook_theme().
 */
function cp_theme($cache, $type, $theme, $path) {
  $path = drupal_get_path('module', 'cp') .'/theme';
  
  $items['cp_toolbar'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'cp-toolbar',
    'path' => $path,
    'file' => 'theme.inc',
  );
  
  $items['cp_theme_picker'] = array(
    'arguments' => array('info' => array()),
    'template' => 'cp-theme-picker',
    'path' => $path,
    'file' => 'theme.inc',
  );
  
  return $items;
}



/**
 * Preprocess function for for intorducing "cp_toolbar"
 * and "cp_left" variables
 */
function cp_preprocess_page(&$vars) {  
  // 2 new variables for top and left menus
  $vars['cp_toolbar'] = 
  $vars['cp_left'] = '';
  
  if (scholar_get_scholar() && user_access('configure spaces features')) { 
    $links = cp_toolbar_menu_links();
    $links = theme('cp_toolbar', $links);
    $vars['cp_toolbar'] = $links;
    
    $links = cp_left_menu_links();
    $vars['cp_left'] = theme('links', $links);
  }
}

/**
 * return links for the toolbar menu
 */
function cp_toolbar_menu_links(){
  $links = array();
  // Retrieve the admin menu from the database.

  $tree = menu_tree_all_data('cp');
  $links[0]['toolbar'] = cp_menu_navigation_links($tree);

  // Add user-specific links
  global $user;
  $user_links = array();
  $user_links[] = array(
    'title' => t('Hello <strong>!username</strong>', array('!username' => $user->name)),
    'href' => 'user',
    'html' => TRUE
  );
  $user_links[] = array('title' => t('Logout'), 'href' => "logout");
  $links[0]['user'] = $user_links;

  return $links;
}

/**
 * Return links for the left side menu
 */
function cp_left_menu_links(){
  //return menu_navigation_links('cp',1);
  
  
  $tree = menu_tree_page_data('cp');

  
  foreach ($tree as $item) {
    if (cp_in_active_trail($item['link']['href']) && !empty($item['below'])) {
      return cp_menu_navigation_links($item['below'],true);
    }
  }
  
}



/**
 * Generate a links array from a menu tree array.
 */
function cp_menu_navigation_links($tree, $b_highlight_first_submenu = false) {
  $links = array();
  foreach ($tree as $item) {
    $class = '';
    $id = str_replace('/', '-', $item['link']['href']);

    $l = $item['link']['localized_options'];
    $l['href'] = $item['link']['href'];
    $l['title'] = "<span class='icon'></span>". $item['link']['title'];
    $l['attributes'] = array('id' => 'admin-link-'. $id);
    $l['html'] = TRUE;

    $class = ' path-'. $id;
    if (cp_in_active_trail($item['link']['href'])) {
    	$b_highlight_first_submenu = false;
      $class .= ' active-trail';
    }

    $links['menu-'. $item['link']['mlid'] . $class] = $l;
  }
  
  if($b_highlight_first_submenu){
    $s_key = key($links);
    $l = array_shift($links);
    $links = array_merge(array("{$s_key} active-trail" => $l),$links);
  }
  return $links;
}


/**
 * Checks whether an item is in the active trail. 
 */
function cp_in_active_trail($path, $reset = FALSE) {
  // Gather active paths
  static $active_paths;
  if (!isset($active_paths) || $reset) {
    $active_paths = array();
    $trail = menu_get_active_trail();
    foreach ($trail as $item) {
      if(is_array($item['map'])){
        $path_makup = "";
        foreach ($item['map'] as $path_component) {
        	$path_makup = trim($path_makup."/".$path_component,"/");
        	if(!in_array($path_makup,$active_paths)) $active_paths[] = $path_makup;
        }
      }elseif (!empty($item['href'])) {
        $active_paths[] = $item['href'];
      }
    }
  }
  return in_array($path, $active_paths);
}

/**
 * Implements hook user
 */
function cp_user($op, &$edit, &$account, $category = null) {
  switch($op){
  	case 'after_update':
  		if($account->mail && isset($account->og_groups) && count($account->og_groups)){
  			foreach ($account->og_groups as $a_grp){
  				if($a_grp['uid'] != $account->uid) continue;
  				$space = spaces_load('og',$a_grp['nid']);
  				$space->settings['site']['contact']['email'] = $account->mail;
  				spaces_save($space);
  			}
  		}
  		$a =$b;
  	break;
  }  
}

/**** Helper function ****/

/**
 * initialize admin theme
 */
function _cp_init_theme(){
	global $custom_theme;
  $custom_theme = CPTHEME;
}

/**
 * Implementation of hook flag_default_flags
 * @return array - default flag
 */
function cp_flag_default_flags() {
  scholar_include('scholarapi');
  $scholar_types = array_keys(scholar_content_types());
 
  $flags = array();
  $flags[] = array(
  'content_type' => 'node',
  'name' => 'frontpage',
  'title' => 'Save to Front Page',
  'types' => $scholar_types, 
  'roles' => array(
  0 => '2',
  ),
  'global' => TRUE,
  'flag_short' => 'Save to Front Page',
  'flag_long' =>  'Save to Front Page',
  'flag_confirmation' => 'Saved to Front Page',
  'unflag_short' => 'Remove from Front Page',
  'unflag_long' => 'Remove from Front Page',
  //   'unflag_confirmation' => 'Are you sure you want to remove?',
  'status' => TRUE,
  'show_on_page' => FALSE,
  'show_on_teaser' => FALSE,
  'show_on_form' => FALSE,
  'link_type' => 'toggle', //normal, toggle, confirm
  'locked' => array('name', 'show_on_page', 'show_on_teaser', 'show_on_form', 'global'),
  );
  
  $flags[] = array(
  'content_type' => 'node',
  'name' => 'featuredposts',
  'title' => 'Featured Posts',
  'types' => $scholar_types, 
  'roles' => array(
  0 => '2',
  ),
  'global' => TRUE,
  'flag_short' => 'Make this a Featured Post',
  'flag_long' =>  'Make this a Featured Post',
  'flag_confirmation' => 'Saved as a Featured Post',
  'unflag_short' => 'Remove as a Featured Post',
  'unflag_long' => 'Remove as a Featured Post',
  //   'unflag_confirmation' => 'Are you sure you want to remove?',
  'status' => TRUE,
  'show_on_page' => TRUE,
  'show_on_teaser' => TRUE,
  'show_on_form' => FALSE,
  'link_type' => 'toggle', //normal, toggle, confirm
  'locked' => array('name', 'show_on_page', 'show_on_teaser', 'show_on_form', 'global'),
  );
  
  return $flags;
}

/**
 * Implementation of hook_link().
 */
function cp_link($type, $object, $teaser = FALSE){

  //check font page settings here, only execute if front page setting equals flag
  $site = scholar_get_scholar();
  //
  if ($site->settings['front']['frontpage'] !== 'flag'){
    return false;
  }

  if (!isset($object) || !flag_fetch_definition($type)) {
    return;
  }

  global $user;
  // Anonymous users can't create flags with this system.
  if (!$user->uid) {
    return;
  }

  // Get frontpage flags
  $flag = flag_get_flag('frontpage');

  if (!$flag->user_access($user)) {
    // User has no permission to use this flag.
    return false;
  }

  if (!$flag->applies_to_content_object($object)) {
    // Flag does not apply to this content.
    return false;
  }

  $content_id = $flag->get_content_id($object);
  // The flag links are actually fully rendered theme functions.
  // The HTML attribute is set to TRUE to allow whatever the themer desires.
  $links['flag-'. $flag->name] = array(
  'title' => $flag->theme($flag->is_flagged($content_id) ? 'unflag' : 'flag', $content_id),
  'html' => TRUE,
  );

  if (isset($links)) {
    return $links;
  }
}

/**
 * Implementation of hook_imagecache_default_presets().
 */
function cp_imagecache_default_presets() {
  $presets = array();
  $presets['default_scholar_logo'] = array (
    'presetname' => 'default_scholar_logo',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_image',
        'data' => array (
          'width' => '700',
          'height' => '600',
        ),
      ),
    ),
  );
  $presets['square_scholar_logo'] = array (
    'presetname' => 'square_scholar_logo',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '140',
          'height' => '140',
        ),
      ),
    ),
  );
  $presets['landscape_scholar_logo'] = array (
    'presetname' => 'landscape_scholar_logo',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '180',
          'height' => '140',
        ),
      ),
    ),
  );
  $presets['portrait_scholar_logo'] = array (
    'presetname' => 'portrait_scholar_logo',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '140',
          'height' => '180',
        ),
      ),
    ),
  );
  return $presets;
}