<?php

/**
 * implementation of hook_menu()
 * provides a page for ajax to call so we can retrieve info from drupal
 */
function pathauto_extra_menu() {
  $items['pathauto_extra/alias_js/%/%'] = array(
    'page callback' => 'pathauto_extra_alias_js',
  	'page arguments' => array(2,3),   
    'type' => 'MENU_CALLBACK', 
    'access arguments' => array('access content'), 
  );
  $items['pathauto_extra/validate_js/%/%'] = array(
    'page callback' => 'pathauto_extra_validate_js',
  	'page arguments' => array(2,3), 
    'type' => 'MENU_CALLBACK', 
    'access arguments' => array('access content'),  
  );
  
  //test entry.
    $items['pathauto_extra/ctools_ajax/%/%'] = array(
    'page callback' => 'pathauto_extra_ctools_ajax', 
    'page arguments' => array(2,3),
    'type' => 'MENU_CALLBACK', 
    'access arguments' => array('access content'),  
  );
  return $items;
}

/**
 * implementation of hook_form_alter()
 * attaches javascript to node edit forms
 */
function pathauto_extra_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id ) {
    ctools_include('ajax');
    ctools_add_js('ajax-responder');
    
    $vsite=vsite_get_vsite();   
    $gid = $vsite->id;
    $type = arg(2); 
    
    ctools_ajax_associate_url_to_element($form, $form['title'], url('pathauto_extra/alias_js/'.$gid.'/'.$type), 'ctools-use-ajax-onchange');
    ctools_ajax_associate_url_to_element($form, $form['path']['path'], url('pathauto_extra/validate_js/'.$gid.'/'.$type), 'ctools-use-ajax-onchange');
  }
}

/**
 * @function pathauto_extra_alias_js()
 * 
 * gets the pattern for formatting urls for this node type, tries to apply it
 * returns expected url alias.
 */
function pathauto_extra_alias_js($gid, $type) {
  //get pattern for this node type
  $pattern = trim(variable_get('pathauto_node_' . $type . '_pattern', FALSE));
  if (empty($pattern)) {
    $pattern = trim(variable_get('pathauto_node_pattern', FALSE));
  }
  
  //if applicable, process this pattern for tokens
  if (isset($pattern) && strlen($pattern) > 0 ) {
    //Fake a simple node object to pass to path auto
    $node = array(
      'title' => $_POST['ctools_changed'],
      'type' => $type,
      'spaces_og' => array('gid' => $gid),
    );
    
    $node = (object)$node;
    module_load_include('inc', 'node', 'node.pages');
    node_object_prepare($node);
    
    //let pathauto apply tokens to path given our fake node
    module_load_include('inc', 'pathauto');
    $placeholders = pathauto_get_placeholders('node', $node);
    $path = pathauto_create_alias('node', 'return', $placeholders, null, null, $node->type, null);
  }

  pathauto_extra_ctools_value('#edit-path', $path);
}

/**
 * @function pathauto_extra_validate_js()
 *
 * checks if a user supplied URL alias is valid.
 */
function pathauto_extra_validate_js($gid, $type) {
  $path = $_POST['ctools_changed'];
  $errors = array();
  
  //begins with slash
  if (strpos($path, '/') === 0) {
    $errors[] = 'URL can not begin with a forward slash.';
  }
  
  //existing url
  $spaces_name = db_result(db_query('SELECT value FROM {purl} WHERE id = %s', $_GET['gid']));  
  $db = db_result(db_query('SELECT pid FROM {url_alias} WHERE dst = "%s/%s"', $spaces_name, $path));
  if ($db) {
    $errors[] = 'This URL is already in use.';
  }
  
  //return to json
  drupal_json( array(
    'errors' => $errors,
  ));
}

/**
 * wrapper function for executing ajax commands
 * @param $id  the html selector (id)
 * @param $message the message to insert on the div with id=$id
 * @param $class  the class to apply to the div
 */
function pathauto_extra_ctools_message($id, $message, $class = 'error'){
  ctools_include( 'ajax');
  ctools_add_js('ajax-responder');
  
  $commands = array();
  $commands[] = ctools_ajax_command_html($id, $message);
  $commands[] = ctools_ajax_command_attr($id, 'class', $class);
  
  ctools_ajax_render($commands);
}

/**
 * warpper function for ajax commands
 * changes value attribute of #$id
 */
function pathauto_extra_ctools_value($id, $value) {
  ctools_include( 'ajax');
  ctools_add_js('ajax-responder');
  
  $commands = array();
  $commands[] = ctools_ajax_command_attr($id, 'value', $value);
  
  ctools_ajax_render($commands);  
}

