<?php

include_once('scholar_links.features.inc');

/**
* Implementation of hook_strongarm().
*/
function scholar_links_strongarm() {
  //module_load_include('inc', 'scholar_link', 'includes/scholar_link.settings_default');
  $conf = array();
  
  // standard group post
  $conf['og_content_type_usage_link'] = 'group_post_standard';
  
  // no comments
  $conf['comment_link'] = 0;
  
  // no diff, no preview 
  $conf['show_preview_changes_link'] = 0;
  $conf['show_diff_inline_link'] = 0;
  
  // make it part of the features menu TODO not here
  //$conf['menu_primary_links_source'] = 'features';
  
  // publish by default

  $conf['node_options_link'] = array('status');

  
  return $conf;
}

function scholar_links_scholar_vocabulary_defaults() {
  return array (
    0 => array (
    'name' => 'link_categories', 
    'content_types' => array ('link' => 1), 
    'properties' => array (), 
    'terms' => array (
      0 => array (
    	'name' => 'Statistics', 
    	'desription' => 'Statistics', 
    	'properties' => array () 
      ), 
      1 => array (
    	'name' => 'Political Economy', 
    	'desription' => 'Political Economy', 
    	'properties' => array () 
      ),
      2 => array (
    	'name' => 'Data', 
    	'desription' => 'Data', 
    	'properties' => array () 
      ),  
      3 => array (
    	'name' => 'Economics', 
    	'desription' => 'Economics', 
    	'properties' => array () 
      ), 
      4 => array (
    	'name' => 'Goverment', 
    	'desription' => 'Economics', 
    	'properties' => array () 
      ) 
    ) 
  ) 
 );
}