<?php


/**
 * Implementation of hook_ctools_plugin_api().
 */
function os_boxes_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function os_boxes_boxes_plugins() {
  $info = array();
  $info['os_boxes_default'] = array(
    'handler' => array(
      'class' => 'os_boxes_default',
      'file' => 'os_boxes_default.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'box',
    ),
  );
  $info['os_boxes_simple'] = array(
    'title' => 'Text',
    'description' => 'Simple custom text',
    'tags' => array('Basic'),
    'handler' => array(
      'parent' => 'box',
      'class' => 'boxes_simple',
      'file' => 'boxes_simple.inc',
      'path' => drupal_get_path('module', 'boxes') .'/plugins',
    ),
  );
  
  $info['os_boxes_feedreader'] = array(
    'title' => 'Feed Reader',  // i.e. view
    'description' => 'List of feed items',
    'tags' => array('Content'),
    'handler' => array(
      'class' => 'os_boxes_feedreader',
      'file' => 'os_boxes_feedreader.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'os_boxes_default',
    ),
  );
  
  $info['os_boxes_rss'] = array(
    'title' => 'RSS feed',  // i.e. view
    'description' => 'RSS feed ??',
    'tags' => array('Social'),
    'handler' => array(
      'class' => 'os_boxes_feedreader',
      'file' => 'os_boxes_feedreader.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'os_boxes_default',
    ),
  );
  
  $info['os_boxes_twitterfeed'] = array(
    'title' => 'Twitter feed CUSTOM BOX',  // i.e. view
    'description' => 'List of latest tweets',
    'tags' => array('Social'),
    'handler' => array(
      'class' => 'os_boxes_twitterfeed',
      'file' => 'os_boxes_twitterfeed.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'os_boxes_default',
    ),
  );
  
  $info['os_boxes_cclicense'] = array(
    'title' => 'CC License',  // i.e. view
    'description' => 'Displays CC license widget',
    'tags' => array('Other'),
    'handler' => array(
      'class' => 'os_boxes_cclicense',
      'file' => 'os_boxes_cclicense.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'os_boxes_default',
    ),
  );
  
  $info['os_boxes_oembed'] = array(
    'title' => 'Media Embed',  // i.e. view
    'description' => 'Embed Media',
    'tags' => array('Media', 'Social'),
    'handler' => array(
      'class' => 'os_boxes_oembed',
      'file' => 'os_boxes_oembed.inc',
      'path' => drupal_get_path('module', 'os_boxes') .'/plugins',
      'parent' => 'os_boxes_default',
    ),
  );

  return $info;
}

/**
 * hook vsite_sidgets
 */
function os_boxes_vsite_widgets(){
  $items = array();
  
  /**
   * Avalible block defintions
   */
  ctools_include('plugins');
  $plugins = ctools_get_plugins('boxes', 'plugins');

  $items = array();
  foreach ( $plugins as $key => $info ) {
    if (isset($info['title'])) {
      $items["boxes-boxes_add__$key"] = array(
        'module' => 'boxes',
        'delta' => "boxes_add__$key",
        'weight' => -10,
        'region' => false,
        'label' => $info['title'],
        'block_config' => "cp/osboxes/nojs/{$key}",
      );
    }
  }
  
  /**
   * Block instances for this site
   */
  $boxes = boxes_load();
  foreach ($boxes as $box) {
  	if(!$box->delta) continue;
    $items["boxes-{$box->delta}"] = array(
      'module' => 'boxes',//$info['module'],
      'delta' => $box->delta,
      'weight' => 20,
      'region' => false,
      'label' => $box->title,
      'cache' => BLOCK_CACHE_CONTENT_CACHE,
    );
  }

  return $items;
}


/**
 * Implementation of hook_menu().
 */
function os_boxes_menu() {
  $items = array();
  ctools_include('plugins');
  $plugins = ctools_get_plugins('boxes', 'plugins');
    $path = drupal_get_path('module', 'boxes');
  foreach ($plugins as $key => $info) {
    if (isset($info['title'])) {
      $items['cp/osboxes/%ctools_js/'. $key] = array(
        'title' => 'Add '. strtolower($info['title']),
        'page callback' => 'os_boxes_box_modal',
        'page arguments' => array( 2,3),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,

        //'file' => 'boxes.admin.inc',
        //'file path' => $path
      );
    }
  }
  
  $items['osboxestest'] = array(
    'title' => 'somettite',
    'page callback' => 'os_boxes_test',
    'access callback' => TRUE
  
  );
  return $items;
}

function os_boxes_test(){
  //dpm(vsite_get_vsite());
  ctools_include('ajax');
  ctools_include('modal');

  ctools_modal_add_js();

  $output = ctools_modal_text_button('simplebox', 'cp/osboxes/nojs/simple', 'simplebox', 'context-button');
  
  return $output;
}

/**
 * A modal login callback.
 */
function os_boxes_box_modal($js = NULL, $delta){
  module_load_include('inc', 'boxes', 'boxes.admin');
  module_load_include('inc', 'boxes', 'plugins/boxes_box');
  
  // Fall back if $js is not set.
  if (! $js) {
    return drupal_get_form('boxes_add_form', $delta);
  }
  
  ctools_include('modal');
  ctools_include('ajax');
  ctools_include('form');
  $plugin_key = str_replace('boxes_add__', '', $delta);
  $identifier = (module_exists('spaces') && $space = spaces_get_space()) ? "{$space->type}-{$space->id}" : 'box';
  $hash = boxes_create_hash($identifier);
  $delta = $identifier . "-" . $hash;
  $box = boxes_factory($plugin_key, array(
    'delta' => $delta
  ));
  $form_state = array(
    'box' => $box,
    'plugin_key' => $plugin_key,
    'custom_action' => TRUE,
    'ajax' => 'TRUE',
    'no_redirect' => TRUE
  );
  $form = ctools_build_form('boxes_box_form', $form_state);
 // dpm($form);
  
  $output = ctools_modal_form_render($form_state, $form);
  
  if (empty($output)) {
    // empty $output signifies success, so we'll use it as our $commands
    // array.
    $output = array();
    $inplace = ctools_ajax_text_button(t('remain here'), 'ctools_ajax_sample/nojs/login/inplace', t('Go to your account'));
    $account = ctools_ajax_text_button(t('your account'), 'ctools_ajax_sample/nojs/login/user', t('Go to your account'));
    $output[] = ctools_modal_command_display(t('Login Success'), '<div class="modal-message">Login successful. You can now choose whether to ' . 'inplace' . ', or go to ' . 'account' . '.</div>');
  }
  ctools_ajax_render($output);
}

function os_boxes_boxes_load_alter(&$box, $delta) {
  //dpm($box);
  //dpm($delta);
}
