<?php

/**
 * hook strongarm
 */
function iqss_openscholar_front_strongarm(){
  $conf = array();

  // Site mission; to be displayed in the front page
  $scholar_mission = ' Harvard Scholars: Create a dynamic feature-full personal
                       web site in seconds. For free! <span>(No, there’s no catch.)</span>';

  $project_mission = ' Academic Projects: Create a dynamic feature-full web site
                       in seconds. For free! <span>(No, there’s no catch.)</span>';

  $install_mode = variable_get('openscholar_installation_mode', 'scholar');


  $conf['site_mission'] = $install_mode == 'scholar' ? $scholar_mission : $project_mission;

  return $conf;
}


/**
 * Implementation of hook_menu_alter
 * We need to do some stuff immediately after
 * the installation if finished; Alter the 'node' callback
 */
function iqss_openscholar_front_menu_alter(&$items){
  $items['welcome']['page callback'] = 'iqss_openscholar_front_homepage';
}

/**
 * Callback for 'welcome' menu entry
 */
function iqss_openscholar_front_homepage(){
  $s_content = '<div id="content-row-2">'.theme('iqss_openscholar_front_content') . '</div>' ;
  return $s_content;
}

/**
 * Implementation of hook_theme
 */
function iqss_openscholar_front_theme(){

  // load a different template file depending on the installation mode
  $install_mode = variable_get('openscholar_installation_mode', 'scholar');

  $path = drupal_get_path('module', 'iqss_openscholar_front_scholar') . '/' . $install_mode;

  $items["iqss_openscholar_front_content"] = array(
    'arguments' => array('tree' => array()),
    'template' => "iqss-openscholar-front-${install_mode}-content",
  );

  return $items;
}

/**
 * implementation of hook_context_default_contexts_alter
 */
function iqss_openscholar_front_context_default_contexts_alter(&$contexts){
  // add some extra links (block) in the 'sitewide_front'
  if (isset($contexts['openscholar-section-sitewide_front'])) {

    $contexts['openscholar-section-sitewide_front']->block['iqss_openscholar_front_top_links'] = array(
      'module' => 'iqss_openscholar_front',
      'delta' => 'top_links',
      'weight' => 37,
      'region' => 'header_main',
      'status' => 0,
      'label' => 'OpenScholar: Top links',
      'type' => 'context_ui'
    );

    if (variable_get('openscholar_installation_mode', 'scholar') == 'project' ){
      unset($contexts['openscholar-section-sitewide_front']->block['views_openscholar_sites-block_2']);
    }
  }
}

/**
 * Implementation of hook_block().
 */
function iqss_openscholar_front_block($op = 'list', $delta = 0) {
  switch ($op) {
    case 'list':
      $info = array(
        'top_links' => array('info' => t('OpenScholar: Top links')),
      );

      return $info;
    case 'view':
      $function = "_iqss_openscholar_front_block_{$delta}";
      if (function_exists($function)) {
        return call_user_func($function);
      }
      break;
  }
}

/**
 * callback function for top_links block
 */
function _iqss_openscholar_front_block_top_links(){
  $block = array();
  $block['subject'] = t('');
  $block['content'] = theme_iqss_openscholar_front_block_top_links();
  return $block;
}

/**
 * Generate content of the top_links block
 */
function theme_iqss_openscholar_front_block_top_links(){ // @todo make it a real theme function
  $items = array();
  $items[] = array(
    'title' => 'About OpenScholar',
    'href' => 'http://openscholar.harvard.edu',
  );

  global $user;
  $items[] = array(
    'title' => $user -> uid ? 'Log out' : 'Log in',
    'href' =>  $user -> uid ? 'logout' : 'user',
  );

  $txt = 'Need a Site for a Project?';
  $url = 'http://projects.iq.harvard.edu';
  $mode = variable_get('openscholar_installation_mode', 'scholar');

  if ($mode == 'project'){
    $txt = 'Need a Personal Academic Site?';
    $url = 'http://scholar.harvard.edu';
  }

  $items[] = array(
    'title' => $txt,
    'href' =>  $url,
  );

  $attributes = array('id' => 'top-front');
  return theme('links', $items, $attributes);
}

