<?php

include_once('scholar_announcements.features.inc');

/**
 * Implementation of hook_strongarm()
 */
function scholar_announcements_strongarm(){
  $conf = array();
  // standard group post
  $conf['og_content_type_usage_announcement'] = 'group_post_standard';
  $conf['content_extra_weights_announcement'] = array(
    'title' => '-5', 
    'body_field' => '-4', 
    'attachments' => '-3', 
    'revision_information' => '-1', 
    'comment_settings' => '1', 
    'menu' => '-4', 
    'path' => '0', 
    'og_nodeapi' => '2' 
  );

  // Disable preview button
  $conf["show_preview_changes_announcement"] = FALSE;
  $conf["show_diff_inline_announcement"] = FALSE;  
 
  $conf['node_options_announcement'] = array('status', 'revision');
  $conf['upload_announcement'] = TRUE;
 
  // Comments
  $conf['comment_announcement'] = COMMENT_NODE_DISABLED;
 
  // Pathauto (optional) settings
  $conf["pathauto_node_announcement_pattern"] = "[space-og-path]/announcements/[title-raw]";
 
  return $conf;
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_announcements_context_links_alter(&$links) {
  if (!empty($links['announcement'])) {
    $links['announcement']['query'] = drupal_get_destination();
  }
}

/**
 * hook vsite_widgets
 */
function scholar_announcements_vsite_widgets(){
  $items = array();
  $items['views_scholar_announcements-block_1'] = array(
        'module' => 'views',
        'delta' => 'scholar_announcements-block_1',
        'weight' => -21,
        'region' => false,
        'status' => '0',
        'label' => 'Latest Announcements',
        'type' => 'context_ui',
      );
  return $items;
}