<?php

/**
 * extend class space_og. We would want to override 
 * some of the methods. 
 * TODO funciont spaces_load in spaces.module is modified
 * because it's initiating an object of type space_og 
 * How do you tell it to initiate an object of class "scholar"
 * How to find all the subclasses of space_og class ?
 * TODO I submitted for this http://drupal.org/node/511914
 * @see scholar_spaces_types_alter
 */


class scholar extends space_og implements space {
	
	function redirect($op = 'home') {
		dpm ( 'hello from scholar class' );
		switch ($op) {
			case 'home' :
				if (! empty ( $this->purl )) {
					// Use the menu path of the selected feature as homepage
					if ($home = $this->settings ['home']) {
						if (menu_get_item ( $home )) {
							purl_goto ( $home, array ('purl' => array ('provider' => 'spaces_og', 'id' => $this->sid ) ) );
						}
					}
					// The previous checks fail, there is no valid homepage set
					if ($this->admin_access () && user_access ( 'configure spaces features' )) {
						drupal_set_message ( t ( "Please setup your group by choosing a homepage setting." ) );
						purl_goto ( "scholarcp/settings/features", array ('purl' => array ('provider' => 'spaces_og', 'id' => $this->sid ) ) );
					}
				} else {
					drupal_goto ( 'node/' . $this->sid . '/edit' );
				}
				menu_set_active_item ( 'spaces-access-denied' );
				break;
			case 'features' :
				purl_goto ( "scholarcp/settings/features", array ('purl' => array ('provider' => 'spaces_og', 'id' => $this->sid ) ) );
				break;
		}
	}
}

/**
 * Implements hook spaces_types_alter
 *
 * @see http://drupal.org/node/511914
 */
function scholar_spaces_types_alter(&$items){
	$items['og']['class'] = 'scholar';
}


/**
 * hook spaces_presets
 */
function scholar_spaces_presets(){
	$items = array();
	$items['scholarsite'] = array(
  'name' => 'Scholar site preset',
  'description' => 'Scholar site preset',
  'preset' => array(
    'features' => array(
      'scholar_links' => '2',


    ),
    'settings' => array(
      'home' => 'links',
    ),
    'locked' => array(
      'features' => array(
        'scholar_announcements' => 0,
        'scholar_blog' => 0,
      ),
      'settings' => array(
        'home' => 0,
      ),
    ),
    'og' => array(
      'og_selective' => '3',
      'og_register' => 0,
      'og_directory' => 1,
      'og_private' => 0,
    ),
  ),
  'type' => 'og',
);

	return $items;
}