<?php 

/**
 * @file
 * Class for sword plugin
 */

class citation_distribute_service_sword extends citation_distribute_service {
	
	
	/*
	 * Implementation of citation_distribute_service::save()
	 */
	public function save() {
		
	}
	
	/*
	 * Implementation of citation_distribute_service::render()
	 */
	public function render() {
		
	}
	
	/*
	 * Implementation of citation_distribute_service::map_metadata()
	 */
	public function map_metadata(){
		
	}
}