<?php
define('CPTHEME', 'scholar_admin');

function scholarcp_init(){	
  if (arg(0) == 'scholarcp'){
  	_scholarcp_init_theme();
  } else {
  	$space = spaces_get_space();
  	if ($space -> type == 'og'){
  		og_set_theme($space -> group);
  	}
  }

}

function scholarcp_menu(){
	$spaces_path = drupal_get_path('module', 'spaces');
  //$items = spaces_active_space_menu('og', FALSE, 'scholarcp/settings');

  $items = array();
  
  $items['scholarcp/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'scholarcp_cp',
    'access arguments' => array('administer site configuration'),
  );
  
  $items["scholarcp/settings/themes"] = array(
    'title' => 'Themes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scholarcp_themes_form'),
    'access callback' => 'spaces_admin_access',
    'access arguments' => array('og', 'features'),
    'file' => 'scholarcp.pages.inc',
  );
  
  $items["scholarcp/settings/features"] = array(
    'title' => 'Features',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spaces_features_form'),
    'access callback' => 'spaces_admin_access',
    'access arguments' => array('og', 'features'),
    //'access arguments' => array('access content'),
    'file' => 'spaces_admin.inc',
    'file path' => $spaces_path,
    'weight' => 1,
  );
  
  $items["scholarcp/settings/features/%"] = array(
    'title' => 'Features',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spaces_customize_form', NULL, 3),
    'access callback' => 'spaces_admin_access',
    'access arguments' => array('og', 'features'),
    'file' => 'spaces_admin.inc',
    'file path' => $spaces_path,
    'weight' => 1,
  );

  $items['scholarcp/content'] = array(
    'title' => 'Content',
    'page callback' => 'scholarcp_cp',
    'access arguments' => array('access content'),
  );
  
  $items['scholarcp/users'] = array(
    'title' => 'Users',
    'page callback' => 'scholarcp_cp',
    'access arguments' => array('access content'),
  );

  $items['scholarcp/news'] = array(
    'title' => 'News',
    'page callback' => 'scholarcp_cp',
    'access arguments' => array('access content'),
  ); 
  
  $items['scholarcp/support'] = array(
    'title' => 'Support',
    'page callback' => 'scholarcp_cp',
    'access arguments' => array('access content'),
  );
  
  // make them all part of 'scholarcp' menu
  foreach($items as $path => $item) {
    $items[$path]['menu_name'] = 'scholarcp';
  }

  return $items;
}

function scholarcp_cp(){
  return '(tbd)';
}

/**
 * Implementation of hook_theme().
 */
function scholarcp_theme($cache, $type, $theme, $path) {
  $path = drupal_get_path('module', 'scholarcp') .'/theme';
  
  $items['scholarcp_toolbar'] = array(
    'arguments' => array('tree' => array()),
    'template' => 'scholarcp-toolbar',
    'path' => $path,
    'file' => 'theme.inc',
  );

  return $items;
}


/**
 * initialize admin theme
 */
function _scholarcp_init_theme(){
	global $custom_theme;
  $custom_theme = CPTHEME;
}


/**
 * Preprocess function for for intorducing "scholarcp_toolbar"
 * and "scholarcp_left" variables
 */
function scholarcp_preprocess_page(&$vars) {
  $vars['scholarcp_toolbar'] = 
  $vars['scholarcp_left'] = '';
  
  if (scholar_get_scholar() && user_access('configure spaces features')) { 
    $links = scholarcp_toolbar_menu_links();
    $links = theme('scholarcp_toolbar', $links);
    $vars['scholarcp_toolbar'] = $links;
    
    $links = scholarcp_left_menu_links();
    $vars['scholarcp_left'] = theme('links', $links);
  }
}

/**
 * return links for the toolbar menu
 */
function scholarcp_toolbar_menu_links(){
  $links = array();
  // Retrieve the admin menu from the database.

  $tree = menu_tree_all_data('scholarcp');
  $links[0]['toolbar'] = scholarcp_menu_navigation_links($tree);

  // Add user-specific links
  global $user;
  $user_links = array();
  $user_links[] = array(
    'title' => t('Hello <strong>!username</strong>', array('!username' => $user->name)),
    'href' => 'user',
    'html' => TRUE
  );
  $user_links[] = array('title' => t('Logout'), 'href' => "logout");
  $links[0]['user'] = $user_links;

  return $links;
}

/**
 * Return links for the left side menu
 */
function scholarcp_left_menu_links(){
  $tree = menu_tree_page_data('scholarcp');
    foreach ($tree as $item) {
      if (scholarcp_in_active_trail($item['link']['href']) && !empty($item['below'])) {
        return scholarcp_menu_navigation_links($item['below']);
      }
    }
}



/**
 * Generate a links array from a menu tree array.
 */
function scholarcp_menu_navigation_links($tree) {
  $links = array();
  foreach ($tree as $item) {
      $class = '';
      $id = str_replace('/', '-', $item['link']['href']);

      $l = $item['link']['localized_options'];
      $l['href'] = $item['link']['href'];
      $l['title'] = "<span class='icon'></span>". $item['link']['title'];
      $l['attributes'] = array('id' => 'admin-link-'. $id);
      $l['html'] = TRUE;

      $class = ' path-'. $id;
      if (scholarcp_in_active_trail($item['link']['href'])) {
        $class .= ' active-trail';
      }

      $links['menu-'. $item['link']['mlid'] . $class] = $l;
    }
  return $links;
}


/**
 * Checks whether an item is in the active trail. 
 */
function scholarcp_in_active_trail($path, $reset = FALSE) {
  // Gather active paths
  static $active_paths;
  if (!isset($active_paths) || $reset) {
    $active_paths = array();
    $trail = menu_get_active_trail();
    foreach ($trail as $item) {
      if (!empty($item['href'])) {
        $active_paths[] = $item['href'];
      }
    }
  }
  return in_array($path, $active_paths);
}



