<?php

include_once('os.features.inc');

function os_init(){
$vsite = spaces_load("og", 5);
$vsite = spaces_get_space();
}




/**
 * Includes different inc files
 */
function os_include($inc_files){
  $inc_files = is_array($inc_files) ? $inc_files : array(
    $inc_files
  );

  $path = dirname(__FILE__);

  foreach ( $inc_files as $inc ) {
    if (file_exists("$path/includes/$inc.inc")) {
      include_once "$path/includes/$inc.inc";
    }
  }
}
