<?php

include_once('scholar_events.features.inc');



/**
 * Implementation of hook_strongarm().
 */
function scholar_events_strongarm() {
  $conf = array();

  foreach (array('event') as $type) {


    // Comments
    $conf['comment_'. $type] = COMMENT_NODE_DISABLED;

    // Disable Diff button
    $conf['show_preview_changes_'. $type] = FALSE;
    $conf['show_diff_inline_'. $type] = FALSE;

    // Pathauto (optional) settings
    $conf["pathauto_node_{$type}_pattern"] = "[space-og-path]/{$type}/[title-raw]";
  }


  // Uploads only on events
  $conf['upload_event'] = TRUE;


  return $conf;
}


/**
 * Implementation of hook_block().
 */
function scholar_events_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array('mini' => array('info' => t('Atrium calendar: Mini calendar')));
    default:
      $function = "_scholar_events_block_{$delta}";
      if (function_exists($function)) {
        return $function($op, $edit);
      }
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function scholar_events_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'view':
      // Confirm we are actually on a page of relevance
      if (menu_get_object() === $node && !empty($node->field_date)) {
        $from = date_convert($node->field_date[0]['value'], DATE_ISO, DATE_OBJECT);
        context_set('node', 'field_date', $from);
      }
      break;
  }
}

/**
 * Block: contextual mini calendar block
 */
function _scholar_events_block_mini($op, $edit) {
  if ($op == 'view') {
    $block = array();
    $date = context_get('node', 'field_date');
    if ($date) {
      $year = date_format($date, 'Y');
      $month = date_format($date, 'm');
      $args = "$year-$month";
      $block['content'] = views_embed_view('scholar_events', 'block_1', $args);
    }
    return $block;
  }
}
