<?php

function scholar_feature_settings_init(){
  $space = scholar_get_scholar();
  
  if(array_key_exists('scholar_style',$space->customizer) && $space->customizer['scholar_style']){
    global $conf;
    $conf['biblio_style'] = $space->customizer['scholar_style'];
  }
  
}

/**
 * Implementation of hook_spaces_customizers().
 */
function scholar_feature_settings_spaces_customizers() {
  return array(
    'scholar_style' => array(
      'class' => 'scholar_feature_settings_customizer_style',
      'file' => drupal_get_path('module', 'scholar_feature_settings') .'/include/customizer.style.inc',
    ),
//    'block' => array(
//      'class' => 'space_customizer_block',
//      'file' => drupal_get_path('module', 'spaces') .'/spaces.spaces.inc',
//    ),
  );
}
