<?php

function scholar_feature_settings_init(){
  $space = scholar_get_scholar();
  
  if($space){
    global $conf;
    spaces_customizers();
    scholar_feature_settings_customizer_style::customize($space, $conf['biblio_style']);
    scholar_feature_settings_customizer_bkn::customize($space,'bkn_contrib_lookup_allow_autocomplete',$conf['bkn_contrib_lookup_allow_autocomplete']);
    scholar_feature_settings_customizer_bkn::customize($space,'bkn_contrib_lookup_mode',$conf['bkn_contrib_lookup_mode']);
  }
}

/**
 * Implementation of hook_spaces_customizers().
 */
function scholar_feature_settings_spaces_customizers() {
  return array(
    'scholar_style' => array(
      'class' => 'scholar_feature_settings_customizer_style',
      'file' => drupal_get_path('module', 'scholar_feature_settings') .'/include/customizer.style.inc',
    ),
    'scholar_bkn' => array(
      'class' => 'scholar_feature_settings_customizer_bkn',
      'file' => drupal_get_path('module', 'scholar_feature_settings') .'/include/customizer.bkn.inc',
    ),
//    'block' => array(
//      'class' => 'space_customizer_block',
//      'file' => drupal_get_path('module', 'spaces') .'/spaces.spaces.inc',
//    ),
  );
}
